### ISSUE TITLE
this socket has been ended by the other part

### ISSUE THREAD

**Issue by UtillYou** [brianc/node-postgres#1012]
After the app started 12 ~ 24 hours, it came across such an error. The stack trace listed bellow:

```
[Error] Error: This socket has been ended by the other party
Reed-0 (err):     at Socket.writeAfterFIN [as write] (net.js:278:12)
Reed-0 (err):     at Connection.query (/home/www/reed/node_modules/pg/lib/connection.js:189:15)
Reed-0 (err):     at Query.submit (/home/www/reed/node_modules/pg/lib/query.js:115:16)
Reed-0 (err):     at Client._pulseQueryQueue (/home/www/reed/node_modules/pg/lib/client.js:298:24)
Reed-0 (err):     at Client.query (/home/www/reed/node_modules/pg/lib/client.js:326:8)
Reed-0 (err):     at /home/www/reed/node_modules/thinkjs/node_modules/thinkit/lib/index.js:47:10
Reed-0 (err):     at Promise._execute (/home/www/reed/node_modules/thinkjs/node_modules/bluebird/js/release/debuggability.js:272:9)
Reed-0 (err):     at Promise._resolveFromExecutor (/home/www/reed/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:473:18)
Reed-0 (err):     at new Promise (/home/www/reed/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:77:14)
Reed-0 (err):     at /home/www/reed/node_modules/thinkjs/node_modules/thinkit/lib/index.js:46:12
Reed-0 (err):     at _class._callee3$ (/home/www/reed/node_modules/thinkjs/lib/adapter/socket/postgresql.js:207:25)
Reed-0 (err):     at tryCatch (/home/www/reed/node_modules/babel-runtime/regenerator/runtime.js:88:40)
Reed-0 (err):     at GeneratorFunctionPrototype.invoke [as _invoke] (/home/www/reed/node_modules/babel-runtime/regenerator/runtime.js:341:22)
Reed-0 (err):     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/www/reed/node_modules/babel-runtime/regenerator/runtime.js:121:21)
Reed-0 (err):     at step (/home/www/reed/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
Reed-0 (err):     at /home/www/reed/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
```

Does anybody know what's going on ? Thanks!

**Comment by ktrzeciaknubisa** [comment]
Same as https://github.com/brianc/node-postgres/issues/725#issuecomment-269624547 . If you check the linked comment you will find reproducible sample.

**Comment by aaronryden** [comment]
Hey there,

I just ran into this due to a crashed pg instance

```
2017-05-06 03:47:43 UTC [11320-3] xxx@xxx HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2017-05-06 03:47:43 UTC [28769-2] WARNING:  terminating connection because of crash of another server process
2017-05-06 03:47:43 UTC [28769-3] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2017-05-06 03:47:43 UTC [28769-4] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2017-05-06 03:47:43 UTC [3594-25] LOG:  all server processes terminated; reinitializing
2017-05-06 03:47:43 UTC [12817-1] LOG:  database system was interrupted; last known up at 2017-05-06 03:45:24 UTC
2017-05-06 03:47:43 UTC [12817-2] LOG:  database system was not properly shut down; automatic recovery in progress
2017-05-06 03:47:43 UTC [12817-3] LOG:  redo starts at 9/98717168
2017-05-06 03:47:43 UTC [12817-4] LOG:  invalid record length at 9/98F875D8: wanted 24, got 0
2017-05-06 03:47:43 UTC [12817-5] LOG:  redo done at 9/98F875B0
2017-05-06 03:47:43 UTC [12817-6] LOG:  last completed transaction was at log time 2017-05-06 03:47:42.537368+00
2017-05-06 03:47:44 UTC [12817-7] LOG:  MultiXact member wraparound protections are now enabled
2017-05-06 03:47:44 UTC [3594-26] LOG:  database system is ready to accept connections
2017-05-06 03:47:44 UTC [12821-1] LOG:  autovacuum launcher started
```

and the following stack from the nodejs + sequelize server

```
03:47:45 05-06-17 { Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:291:12)
    at Connection.query (/root//node_modules/pg/lib/connection.js:204:15)
    at Query.submit (/root//node_modules/pg/lib/query.js:138:16)
    at Client._pulseQueryQueue (/root//node_modules/pg/lib/client.js:307:24)
    at Client.query (/root//node_modules/pg/lib/client.js:335:8)
    at Query.run (/root//node_modules/sequelize/lib/dialects/postgres/query.js:62:106)
    at /root//node_modules/sequelize/lib/sequelize.js:849:20
    at /root//node_modules/retry-as-promised/index.js:40:21
    at Promise._execute (/root//node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/root/node_modules/bluebird/js/release/promise.js:481:18)
```

is there a preferred place to catch this and/or reconnect or even force the app server to restart? anything is better than the process sitting, accepting connections, not responding , but also not trying to reconnect.

**Comment by charmander** [comment]
The original issue here might have been pool misuse, but it’s hard to say for sure without further detail.

@aaronryden, are you still able to reproduce that? It might have been a sequelize pool bug.
