### ISSUE TITLE
Error when using native and node 6

### ISSUE THREAD

**Issue by Brakkar** [brianc/node-postgres#1078]
When I use native pg let pg = require( 'pg' ).native, on node 6 and launch the app, I get:

```
....../node_modules/pg/lib/index.js:107
        throw err;
        ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (...../node_modules/pg-native/node_modules/libpq/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (....../node_modules/pg-native/node_modules/libpq/index.js:1:108)
    at Module._compile (module.js:541:32)
```

When I remove native as let pg = require( 'pg' ) it works ok.

**Comment by vitaly-t** [comment]
Delete your `node_modules` folder, do `npm install` again, that should fix it ;)

**Comment by brianc** [comment]
yup yup - whenever you change versions of node any compiled modules *must* be recompiled, so you gotta nuke the node_modules & reinstall. Thanks @vitaly-t!
