### ISSUE TITLE
ERROR Mesage for: error: syntax error at or near "," at connection.js:551:11

### ISSUE THREAD

**Issue by BernhardLenz** [brianc/node-postgres#1079]
I'm trying to connect to connect to postgres from inside an aws lambda function but get below error

`2016-07-15T13:59:17.892Z```	520fef8b-4a94-11e6-b716-2f2fe2863b8d	error: syntax error at or near ","
    at Connection.parseE (/var/task/node_modules/pg/lib/connection.js:551:11)
    at Connection.parseMessage (/var/task/node_modules/pg/lib/connection.js:378:17)
    at Socket.<anonymous> (/var/task/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:77:13)`

I believe my problem has to do with my IAM access privileges but think that the error message should be more descriptive than `syntax error at or near ","`

**Comment by brianc** [comment]
Without more info I am not able to tell you what's wrong there. Very likely its something wrong with your connection information or query, depending on when its happening.  That error message is directly from postgres; if you want more info you can do `console.log(JSON.stringify(err))`, but node-postgres doesn't do anything to the error message, just passes it on through.

**Comment by BernhardLenz** [comment]
Hi Brian, thanks for the quick reply. It turned out the error was actually from the query call and not the connect. I did not pass the correct parameter objects to the query function and therefore the little "weird" message. I suppose this is a javascript typing issues and not related to node-postgres, hence closing the issue. 
Greetings
Bernie

**Comment by abhiindia** [comment]
/var/lib/deepstream/deepstream.io-storage-postgres/src/connector.js:364
          throw error
          ^

error: syntax error at or near "NOT"
    at Connection.parseE (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

I am getting same error..could anyone help me on this?

**Comment by abenhamdine** [comment]
Your error is a SQL syntax error and had probably nothing to do with this library.
And please open a new issue if you think there's is a problem with this module, don't comment a closed issue.

**Comment by jjhidalgo1991** [comment]
MyError???
{"name":"error","length":83,"severity":"ERROR","code":"42601","position":"48","file":"scan.l","line":"1083","routine":"scanner_yyerror"}

**Comment by charmander** [comment]
@jjhidalgo1991 You’ll want to look at the error’s `message`. It’s a non-enumerable property, so `JSON.stringify` won’t include it.
