### ISSUE TITLE
error with promise while executing

### ISSUE THREAD

**Issue by zerr0s** [brianc/node-postgres#1087]
Hi, forgive me for my bad english. I'm using the module pg to connect to a postgresql database. On my laptop, I have no problem with the module. But when I push my application on a server, the module throw an error:

`/USR/deploy/apps/ihm/node_modules/pg/node_modules/pg-pool/index.js:11
  this.Promise = this.options.Promise || Promise
                                         ^
ReferenceError: Promise is not defined
    at module.exports (/USR/deploy/apps/ihm/node_modules/pg/node_modules/pg-pool/index.js:11:42)
    at new BoundPool (/USR/deploy/apps/ihm/node_modules/pg/lib/pool-factory.js:12:10)
    at new dbClass (/USR/deploy/apps/ihm/class/dbClass.js:22:16)
    at logClass.writeToLog (/USR/deploy/apps/ihm/class/logClass.js:16:15)
    at Object.<anonymous> (/USR/deploy/apps/ihm/bin/daemon.js:11:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
`
I have tried to reinstall the module, install pg-promise, but the problem persists. Is there a way to resolve this ?

Thanks in advance for your help.

**Comment by brianc** [comment]
Please read this: https://github.com/brianc/node-pg-pool#bring-your-own-promise

You need to polyfill a promise if you're using node <= v4

**Comment by vitaly-t** [comment]
@zerr0s correction on Brian's post, in case you are using [pg-promise](https://github.com/vitaly-t/pg-promise), see [parameter promiseLib](https://github.com/vitaly-t/pg-promise#promiselib)

**Comment by zerr0s** [comment]
thans a lot. It was a conflict of version between a old node version installed on root and another nodejs in a single user :))))
