### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by talentedmrripley** [brianc/node-postgres#1108]
Posting here on the recommendation of @Brideau.  
https://github.com/Brideau/pokelyzer/issues/77

```
TypeError: undefined is not a function
    at Pool.connect (/home/ripley/pokelyzer/node_modules/pg/node_modules/pg-pool/index.js:55:10)
    at /home/ripley/pokelyzer/app.js:57:12
    at Layer.handle [as handle_request] (/home/ripley/pokelyzer/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ripley/pokelyzer/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/ripley/pokelyzer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ripley/pokelyzer/node_modules/express/lib/router/layer.js:95:5)
    at /home/ripley/pokelyzer/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/ripley/pokelyzer/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ripley/pokelyzer/node_modules/express/lib/router/index.js:271:10)
    at /home/ripley/pokelyzer/node_modules/body-parser/lib/read.js:129:5
```

**Comment by talentedmrripley** [comment]
Turns out it was a node version issue, I need 4.x.  Issue resolved.
