### ISSUE TITLE
error: invalid message format

### ISSUE THREAD

**Issue by vivekreghunath** [brianc/node-postgres#1121]
Cant connect to PG 9.4. Tried with Node versions : 6.4,4.5,4.47, 0.10.36.

Following is the error:

error: invalid message format
    at Connection.parseE (path_to_nodemodules/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (path_to_nodemodules/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (path_to_nodemodules/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)

**Comment by abenhamdine** [comment]
Hi,

It's difficult to help you without seeing your code and your connexion string/config...

**Comment by harshitgupta** [comment]
I m having the same issue. I got this error when I was trying to insert '\u0000' into a column with character(1) type. 
I agree that sql is wrong. But I think if error should helpful. One can only find the issue why running the sql query in some client and figuring out the column.

thanks

**Comment by vkiselyov** [comment]
Hi. I have same problem
My Flow
![image](https://user-images.githubusercontent.com/35599680/36776388-a39452a8-1c76-11e8-947b-2f6a66f4adcf.png)

msg.output looks like 

SELECT public.parse_packet({"time":"2018-02-28T08:00:14.233536Z","address":"11223344","temp":2520,"pres":10069922,"hum":26107,"alt":87,"lat":676055,"lon":445222,"ax":1156,"ay":5692,"az":14420,"gx":14420,"gy":81,"gz":-256})

Error From Log:
 [error] [postgres:dc4fbe0e.8b0a6] error: invalid message format
{ error: invalid message format
    at Connection.parseE (/root/.node-red/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/root/.node-red/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/root/.node-red/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:598:20)
  name: 'error',
  length: 81,
  severity: 'ERROR',
  code: '08P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'pqformat.c',
  line: '682',
  routine: 'pq_getmsgend' }
SELECT public.parse_packet('{"time":"2018-02-28T07:56:24.004451Z","address":"11223344","temp":2517,"pres":10069192,"hum":26767,"alt":87,"lat":446055,"lon":335222,"ax":1048,"ay":5840,"az":14380,"gx":14380,"gy":127,"gz":-256}')

If I use this sql script on DB it work.

What's wrong?

**Comment by vkiselyov** [comment]
Hardcode msg
msg.payload = "SELECT public.parse_packet('{\"time\":\"2018-02-28T07:37:53.985745Z\",\"address\":\"11223344\",\"temp\":2417,\"pres\":10071257,\"hum\":26342,\"alt\":87,\"lat\":666055,\"lon\":445222,\"ax\":540,\"ay\":4624,\"az\":14924,\"gx\":14924,\"gy\":90,\"gz\":-256}')"
return msg;

works to.

**Comment by charmander** [comment]
@vkiselyov What is the non-hard-coded message?

**Comment by vkiselyov** [comment]
I'm sorry. I found problem. Value in my query was byte array, but looks like string. It contained zero byte in the middle of string and it was cause of fail. I fix it and it work now.
I'm sorry for disturb.
