### ISSUE TITLE
Connection Error crashes program

### ISSUE THREAD

**Issue by christiansaiki** [brianc/node-postgres#1165]
Hey guys I'm getting the following error

events.js:141
      throw er; // Unhandled 'error' event
Error: Connection terminated
    at null.<anonymous> (/home/ec2-user/database-deploy/node_modules/pg/lib/client.js:198:29)
    at g (events.js:260:16)
    at emitNone (events.js:72:20)
    at emit (events.js:166:7)
    at Socket.<anonymous> (/home/ec2-user/database-deploy/node_modules/pg/lib/connection.js:78:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:486:12)

What should I do to treat this error?  Also how can I debug to check what is causing this error?
Thanks in advance

**Comment by davidskuza** [comment]
The same goes with queries. If we try to insert wrong type of data then it crashes the same way instead of returning an error.

**Comment by christiansaiki** [comment]
And apparently this issue only happens at AWS EC2, it never happened in my computer yet so it is hard to detect what is happening

**Comment by christiansaiki** [comment]
Perhaps I need to use 
```
client.on('end', function () {
 // treat my error here
}
```
I've checked the error is happening in line 198 of client.js and after that it is emitting an end event.

Am I doing the right approach?
Thanks

**Comment by charmander** [comment]
This should be fixed by brianc/node-pg-pool#31. pg itself still depends on pg-pool 1.\*, though, so you might need to install pg-pool@1.6 explicitly.

**Comment by dks-ait** [comment]
I am getting the same issue, while using the pg-cursor and pg. I am not using pool as I need only 2 connections. Any idea on how this can be solved. I am using pg@7.0.2. 

The error that I am getting is (after I have explicitly called cursor.end()) :- 

`Uncaught Error: Connection terminated unexpectedly
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)`

**Comment by eduardobcastro** [comment]
`ALTER role my_user SET tcp_keepalives_idle = 30;`
