### ISSUE TITLE
Utilizing Promise.then to close connection

### ISSUE THREAD

**Issue by Nopzen** [brianc/node-postgres#1167]
Hello people.

Im brand new to Postgres & Database & node in general, but i've been searching abit about my current issue is, i query the endpoint twice it works the first time but not the second time.

### Setup of pg.client
```js
const pg = require('pg');

const dbConfig = {
  user: 'postgres',
  database: 'db',
  password: '*******',
  host: 'localhost',
  port: 5432,
};

const dbClient = new pg.Client(dbConfig);

exports.client = dbClient;
```
### Usage
```js
const database = require('./database.js');

database.client.connect(err => {
          if (err) {
            throw err;
          }

          Promise.all([
            database.client.query(`
              SELECT *
              FROM groceries_lists
              WHERE id = ${req.params.listId}
            `),
            database.client.query(`
              SELECT p.*
              FROM groceries AS g
              JOIN products AS p ON p.id = g.product_id
              WHERE g.list_id = ${req.params.listId}
            `)
          ]).then(results => {
            const data = results[0].rows.map(entity => {
              return {
                id: entity.id,
                type: entity.type,
                attributes: {
                  listName: entity.list_name,
                  completed: entity.completed
                }
              }
            });

            const included = results[1].rows.map(entity => {
              return {
                id: entity.id,
                type: entity.type,
                attributes: {
                  name: entity.name,
                  price: entity.price
                }
              }
            });

            return ({
              data,
              included
            });
          }).then(results => {
            database.client.end();
            res(results);
          });
        });
```

The error thrown by the node server is:

### Error
```log
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:896:11)
    at WriteWrap.afterWrite (net.js:786:14)
larsfalcon@Larss-MacBook-Pro-2 server $
```

It seems to me like the database client dosent end when calling it im not sure if im during it all wrong but i cant seem to get it right, i hope some one could help me on this :)

**Comment by Nopzen** [comment]
Sorry i figured, i was referencing the same connection and did not open a new for ever new API call.

I fixed this with `const dbClient  = new pg.Client(database.config)` and there for open a new Client for every.

My mistake for not understanding the correct usage of the tool! 

Closing.
