### ISSUE TITLE
TypeError: this._types.getTypeParser is not a function

### ISSUE THREAD

**Issue by pasupulaphani** [brianc/node-postgres#1175]
```
»  app web.1 - - /app/node_modules/pg/lib/type-overrides.js:35
» - - return this.getOverrides(format)[oid] || this._types.getTypeParser(oid, format);
»  app web.1 - - ^
»  app web.1 - -
»  app web.1 - - TypeError: this._types.getTypeParser is not a function at TypeOverrides.getTypeParser (/app/node_modules/pg/lib/type-overrides.js:35:56) at Result.addFields (/app/node_modules/pg/lib/result.js:102:23) at Query.handleRowDescription (/app/node_modules/pg/lib/query.js:80:16) at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:112:24) at emitOne (events.js:96:13) at Connection.emit (events.js:188:7) at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:121:12) at emitOne (events.js:96:13) at TLSSocket.emit (events.js:188:7) at readableAddChunk (_stream_readable.js:176:18) at TLSSocket.Readable.push (_stream_readable.js:134:10) at TLSWrap.onread (net.js:551:20)
»  app web.1 - - {"name":"ps-api","hostname":"*******","pid":18,"level":30,"msg":"worker 34 died","time":"2016-11-30T11:34:06.847Z","v":0}
»  app postgres.**** - - [XXXX] could not receive data from client: Connection reset by peer
```

Any insights on how this could happen? This is happening a lot on our prod env. (couldn't reproduce locally)

**Comment by pasupulaphani** [comment]
Having some major issues with this on production.

**Comment by MichaelErmer** [comment]
How did u resolve this?

**Comment by LouysPatriceBessette** [comment]
This issue is still valid. I experienced it in localhost on 14 prepared queries out of 16 (2 were working by chance) when using the `types: ['string'] property of the object to pass to `client.query()`.

Solution: I simply removed them all.

**Comment by brianc** [comment]
can you provide self-contained steps to reproduce? If so, I should be able to take a look at it & either fix it in the code or provide insight/pointers on to what's going on. 🙏

**Comment by LouysPatriceBessette** [comment]
On both VPS and localhost, I have:

- Ubuntu: 24.04 LTS
- Node: v18.19.1

Postgres is installed on the VPS.
- psql (PostgreSQL) 16.6 (Ubuntu 16.6-0ubuntu0.24.04.1)


Here is the code where I still can reproduce it:

    module.exports = {
        todoGet: async function (dbo, userId) {
            const thisFunctionName = 'todoGet'
            console.log('\ntodoFunction', thisFunctionName)
			
            const result = []
            const prepared_SELECT_todos = {
                name: `SELECT_todos`,
                text: `SELECT * FROM todo WHERE owner_id=$1 ORDER BY order_in_group;`,
                values: [userId],
                types: ['int'],    // This line is the issue
            }

            console.log(prepared_SELECT_todos)    // Values is an array of one integer, see below.
			
            try {
                const queryResult = await dbo.query(prepared_SELECT_todos)
				
                // some code
            }catch(e){
                // some code
            }
        }
    }

`dbo.query()` is another module function:

    const pg = require('pg')
    const { Client } = pg

    const santiago = {
        user: process.env.SANTIAGOUSER,
        password: process.env.SANTIAGOPASSWORD,
        host: process.env.SANTIAGOHOST,
        port: process.env.SANTIAGOPORT,
        database: process.env.SANTIAGODATABASE,
    }

    module.exports = {
        query: async function (query) {
            const client = new Client(santiago)
            await client.connect()
            const result = (await client.query(query)).rows
            client.end()

            return result
        },
    }
		
Here is the result in localhost:

	Listening on port 5000 - DB time: Tue Jan 14 2025 13:54:54 GMT-0500 (Eastern Standard Time)


	2025-01-14 13:55:30
	=== Route: todo
	=== req.body:
	{ a: 'get', sessionToken: '' }

	todoFunction todoGet
	{
	  name: 'SELECT_todos',
	  text: 'SELECT * FROM todo WHERE owner_id=$1 ORDER BY order_in_group;',
	  values: [ 2 ],
	  types: [ 'int' ]
	}
	/path/to/code/node_modules/pg/lib/result.js:98
	    this._parsers[i] = this._types.getTypeParser(desc.dataTypeID, desc.format || 'text')
										   ^

	TypeError: this._types.getTypeParser is not a function
		at Result.addFields (/path/to/code/node_modules/pg/lib/result.js:98:40)
		at Query.handleRowDescription (/path/to/code/node_modules/pg/lib/query.js:78:18)
		at Client._handleRowDescription (/path/to/code/node_modules/pg/lib/client.js:361:22)
		at Connection.emit (node:events:517:28)
		at /path/to/code/node_modules/pg/lib/connection.js:116:12
		at Parser.parse (/path/to/code/node_modules/pg-protocol/dist/parser.js:36:17)
		at Socket.<anonymous> (/path/to/code/node_modules/pg-protocol/dist/index.js:11:42)
		at Socket.emit (node:events:517:28)
		at addChunk (node:internal/streams/readable:368:12)
		at readableAddChunk (node:internal/streams/readable:341:9)

	Node.js v18.19.1

Let me now if you need more detail.

**Comment by LouysPatriceBessette** [comment]
I just made a quick test with two console logs just before the two last stack traces like so:

- Added a console log above line #98 in result.js
![image](https://github.com/user-attachments/assets/04c4f1a4-d12d-4530-8dd8-c3dbcf8e7ced)

- Added a console.log above line # 78 in query.js
![image](https://github.com/user-attachments/assets/3c115a3a-ba9f-4707-8181-ed032a25d39c)

Here is what happens starting node:

	user@mypc:~/path/to/code/server$ node server.js
	msg.fields [
	  Field {
		name: 'now',
		tableID: 0,
		columnID: 0,
		dataTypeID: 1184,
		dataTypeSize: 8,
		dataTypeModifier: -1,
		format: 'text'
	  }
	]
	this._types TypeOverrides {
	  _types: {
		getTypeParser: [Function: getTypeParser],
		setTypeParser: [Function: setTypeParser],
		arrayParser: { create: [Function: create] },
		builtins: {
		  BOOL: 16,
		  BYTEA: 17,
		  CHAR: 18,
		  INT8: 20,
		  INT2: 21,
		  INT4: 23,
		  REGPROC: 24,
		  TEXT: 25,
		  OID: 26,
		  TID: 27,
		  XID: 28,
		  CID: 29,
		  JSON: 114,
		  XML: 142,
		  PG_NODE_TREE: 194,
		  SMGR: 210,
		  PATH: 602,
		  POLYGON: 604,
		  CIDR: 650,
		  FLOAT4: 700,
		  FLOAT8: 701,
		  ABSTIME: 702,
		  RELTIME: 703,
		  TINTERVAL: 704,
		  CIRCLE: 718,
		  MACADDR8: 774,
		  MONEY: 790,
		  MACADDR: 829,
		  INET: 869,
		  ACLITEM: 1033,
		  BPCHAR: 1042,
		  VARCHAR: 1043,
		  DATE: 1082,
		  TIME: 1083,
		  TIMESTAMP: 1114,
		  TIMESTAMPTZ: 1184,
		  INTERVAL: 1186,
		  TIMETZ: 1266,
		  BIT: 1560,
		  VARBIT: 1562,
		  NUMERIC: 1700,
		  REFCURSOR: 1790,
		  REGPROCEDURE: 2202,
		  REGOPER: 2203,
		  REGOPERATOR: 2204,
		  REGCLASS: 2205,
		  REGTYPE: 2206,
		  UUID: 2950,
		  TXID_SNAPSHOT: 2970,
		  PG_LSN: 3220,
		  PG_NDISTINCT: 3361,
		  PG_DEPENDENCIES: 3402,
		  TSVECTOR: 3614,
		  TSQUERY: 3615,
		  GTSVECTOR: 3642,
		  REGCONFIG: 3734,
		  REGDICTIONARY: 3769,
		  JSONB: 3802,
		  REGNAMESPACE: 4089,
		  REGROLE: 4096
		}
	  },
	  text: {},
	  binary: {}
	}
	Listening on port 5000 - DB time: Tue Jan 14 2025 15:56:14 GMT-0500 (Eastern Standard Time)

So the server is started... Now I refresh the page that is making the query on load:

	2025-01-14 15:56:51
	=== Route: todo
	=== req.body:
	{ a: 'get', sessionToken: '' }

	todoFunction todoGet
	msg.fields [
	  Field {
		name: 'id',
		tableID: 26366,
		columnID: 1,
		dataTypeID: 20,
		dataTypeSize: 8,
		dataTypeModifier: -1,
		format: 'text'
	  },
	  // Some more columns...
	  Field {
		name: 'owner_id',
		tableID: 26366,
		columnID: 12,
		dataTypeID: 20,
		dataTypeSize: 8,
		dataTypeModifier: -1,
		format: 'text'
	  },
	]
	this._types [ 'int' ]
	/path/to/code/node_modules/pg/lib/result.js:99
			this._parsers[i] = this._types.getTypeParser(desc.dataTypeID, desc.format || 'text')
										   ^

	TypeError: this._types.getTypeParser is not a function
		at Result.addFields (/path/to/code/node_modules/pg/lib/result.js:99:40)
		at Query.handleRowDescription (/path/to/code/node_modules/pg/lib/query.js:79:18)
		at Client._handleRowDescription (/path/to/code/node_modules/pg/lib/client.js:361:22)
		at Connection.emit (node:events:517:28)
		at /path/to/code/node_modules/pg/lib/connection.js:116:12
		at Parser.parse (/path/to/code/node_modules/pg-protocol/dist/parser.js:36:17)
		at Socket.<anonymous> (/path/to/code/node_modules/pg-protocol/dist/index.js:11:42)
		at Socket.emit (node:events:517:28)
		at addChunk (node:internal/streams/readable:368:12)
		at readableAddChunk (node:internal/streams/readable:341:9)

	Node.js v18.19.1

Notice that `this._types` got replaced by my `[ 'int' ]` array... And therefore, `[ 'int' ].getTypeParser` is not a function....

;)

**Comment by charmander** [comment]
> Solution: I simply removed them all.

This is the correct solution for now. Queries *are* supposed to have a `types` feature for parameters, and this does collide with type parsers in the current version of the library – but it takes integer OIDs, not type name strings, despite a misleading comment in serializer.ts. So `types: ['int']` is not a thing in pg, and I’m not sure it ever was.

**Comment by charmander** [comment]
The aforementioned bug is tracked in #2287, and the original issue here doesn’t have enough details to tell if it had the same cause.
