### ISSUE TITLE
listener must be a function with transactions

### ISSUE THREAD

**Issue by benoittgt** [brianc/node-postgres#1191]
Hello

First thanks for node-pg !
I'm trying to run two commands inside transactions.

```SQL
BEGIN;
ALTER TABLE ${tableName}_temp RENAME TO ${tableName}_process;
CREATE TABLE ${tableName}_temp (LIKE ${tableName}_process);
COMMIT;

BEGIN;
INSERT INTO ${tableName}
SELECT DISTINCT ${tableName}_process.*
FROM ${tableName}_process
LEFT JOIN ${tableName} USING (id)
WHERE ${tableName}.id IS NULL
ORDER BY ${tableName}_process.id;
DROP TABLE ${tableName}_process;
COMMIT;
```

The javascript with the help of https://github.com/brianc/node-postgres/wiki/Transactions
```javascript
  const client = new pg.Client(connection);

  client.connect(function(err) {
    if (err) {
      return context.fail(`Failed to connect: ${err}`);
    }
  });

  var rollback = function(client) {
    //terminating a client connection will
    //automatically rollback any uncommitted transactions
    //so while it's not technically mandatory to call
    //ROLLBACK it is cleaner and more correct
    client.query('ROLLBACK', function() {
      client.end();
    });
  };
  
  let tablesToProcess = ['my_table', 'my_other_table']
  tablesToProcess.forEach(function(tableName) {
    let tableCopyQuery = `
      ALTER TABLE ${tableName}_temp
      RENAME TO ${tableName}_process;
      CREATE TABLE ${tableName}_temp (LIKE ${tableName}_process);`
   let insertQuery = `
      INSERT INTO ${tableName}
      SELECT DISTINCT ${tableName}_process.*
        FROM ${tableName}_process
        LEFT JOIN ${tableName} USING (id)
       WHERE ${tableName}.id IS NULL
       ORDER BY ${tableName}_process.id;
      DROP TABLE ${tableName}_process;`;

    client.query('BEGIN', function(err, result) {
      if(err) return rollback(client);
      client.query(tableCopyQuery, function(err, result) {
        if(err) return rollback(client);
        client.query(insertQuery, function(err, result) {
        if(err) return rollback(client);
        client.query('COMMIT', client.end.bind(client));
      });
      });
    });
  });
```

But I get 
```
TypeError: listener must be a function
    at once (events.js:251:11)
    at Client.end (/var/task/node_modules/pg/lib/client.js:342:21)
    at Query.handleError (/var/task/node_modules/pg/lib/query.js:129:17)
    at null.<anonymous> (/var/task/node_modules/pg/lib/client.js:180:26)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/var/task/node_modules/pg/lib/connection.js:121:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
```

It's no possible to run the SQL block and let it rollback?

**Comment by benoittgt** [comment]
I switched to pg-promise and it's work well
```js
/*jshint camelcase: false */
'use strict';
const config = require('./config');
const conn = `pg://${config.user}:${config.password}@${config.host}/${config.database}`;
const pgp = require('pg-promise')();

var tableCopyQuery = function(tableName) {
  return `
      ALTER TABLE ${tableName}_temp
      RENAME TO ${tableName}_process;
      CREATE TABLE ${tableName}_temp (LIKE ${tableName}_process);`;
};
var insertQuery = function(tableName) {
  return `
      INSERT INTO ${tableName}
      SELECT DISTINCT ${tableName}_process.*
        FROM ${tableName}_process
        LEFT JOIN ${tableName} USING (id)
       WHERE ${tableName}.id IS NULL
       ORDER BY ${tableName}_process.id;
      DROP TABLE ${tableName}_process;`;
};

exports.handler = function(event, context) {
  const client = pgp(conn);

  client.tx(function (t) {
    return t.batch([
      t.none(tableCopyQuery('active_connections')),
      t.none(insertQuery('active_connections')),
      t.none(tableCopyQuery('active_downloads')),
      t.none(insertQuery('active_downloads'))
    ]);
  })
    .then(function () {
      context.succeed(`Successfully Refreshed.`);
    })
    .catch(function (error) {
      context.fail(`Failed to run queries : ${JSON.stringify(error)}`);
    });
};
```

Will clean the code a little bit, but it's working.

**Comment by charmander** [comment]
```javascript
client.query('COMMIT', client.end.bind(client));
```

This will cause the result object to be passed to `client.end`. Instead:

```javascript
client.query('COMMIT', function (error) {
    client.end(error);
});
```

or use promises, which pg supports without pg-promise.
