### ISSUE TITLE
Error SET search_path to $1::text

### ISSUE THREAD

**Issue by k--kato** [brianc/node-postgres#1194]
os: macOS 10.12.2
node: v6.9.4
node-postgres: v6.1.2
postgres: 9.6.1

Hello! Thanks for this library, it's great.

```sql
SET search_path to $1::text
```

```js
connection.query("SET search_path to $1::text", ["infomation_schema"], function (err, rows) {
}
```

```bash
"error: syntax error at or near "$1"
    at Connection.parseE (node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)"
```

**Comment by charmander** [comment]
See #539.
