### ISSUE TITLE
(node:54764) DeprecationWarning: Using Buffer without `new` will soon stop working.

### ISSUE THREAD

**Issue by agopshi** [brianc/node-postgres#1198]
```
$ node --trace-deprecation baz 
(node:54764) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
    at Buffer (buffer.js:79:13)
    at Object.<anonymous> (/Users/foo/node_modules/pg/lib/connection.js:299:19)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/foo/node_modules/pg/lib/client.js:18:18)
```

The fix is to simply change `connection.js:299` from:
```
var emptyBuffer = Buffer(0);
```
To:
```
var emptyBuffer = Buffer.alloc(0);
```

**Comment by vitaly-t** [comment]
Yet another duplicate of...

#1195, #1189, #1163 and #1158

Please check the existing issues before reporting a new one.

**Comment by agopshi** [comment]
You are correct. I will exercise more caution in the future. I think I must have had the "is:open" filter on the issue.
