### ISSUE TITLE
Deployin to heroku gives : Error: Cannot find module './pool-factory'

### ISSUE THREAD

**Issue by maykell-valdiviezo** [brianc/node-postgres#1201]
Hi I hope you can help, 

I've been using pg@4.5.1 and deploying my solution to heroku. Recently, i updated my project 
and push one .png file.  

I've notice that i  have the following error : Error: Cannot find module './pool-factory'.
Locally it works and i can see the module is present.  For now i'm trying different versions and all 
seems to create an error at the './pool **' missing when deployed to heroku. 

The error below is with pg@6.1.2.

Any idea will surely help. 

Thanks!

2017-01-23T04:10:41.149010+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2017-01-23T04:10:41.291866+00:00 heroku[web.1]: Process exited with status 143
2017-01-23T04:10:42.729472+00:00 heroku[web.1]: Starting process with command `node index.js`
2017-01-23T04:10:44.858872+00:00 app[web.1]: module.js:327
2017-01-23T04:10:44.858888+00:00 app[web.1]:     throw err;
2017-01-23T04:10:44.858889+00:00 app[web.1]:     ^
2017-01-23T04:10:44.858890+00:00 app[web.1]:
**2017-01-23T04:10:44.858891+00:00 app[web.1]: Error: Cannot find module './pool-factory'**
2017-01-23T04:10:44.858891+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:325:15)
2017-01-23T04:10:44.858892+00:00 app[web.1]:     at Function.Module._load (module.js:276:25)
2017-01-23T04:10:44.858893+00:00 app[web.1]:     at Module.require (module.js:353:17)
2017-01-23T04:10:44.858894+00:00 app[web.1]:     at require (internal/module.js:12:17)
2017-01-23T04:10:44.858895+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/pg/lib/index.js:15:19)
2017-01-23T04:10:44.858895+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2017-01-23T04:10:44.858896+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:416:10)
2017-01-23T04:10:44.858896+00:00 app[web.1]:     at Module.load (module.js:343:32)
2017-01-23T04:10:44.858897+00:00 app[web.1]:     at Function.Module._load (module.js:300:12)
2017-01-23T04:10:44.858898+00:00 app[web.1]:     at Module.require (module.js:353:17)

**Comment by maykell-valdiviezo** [comment]
This is not an issue. When deploying to Heroku make sure node_modules/ folder is register
in your .gitignore file and do not push node_modules/ folder.
