### ISSUE TITLE
Calling Buffer as function is deprecated

### ISSUE THREAD

**Issue by adrianhelvik** [brianc/node-postgres#1214]
❯ node --trace-deprecation -e 'require("pg")'
    (node:50727) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
        at Buffer (buffer.js:79:13)
        at Object.<anonymous> (/path/to/project/node_modules/pg/lib/connection.js:299:19)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/path/to/project/node_modules/pg/lib/client.js:18:18)

The problem is on line 299 of lib/connection.js

    var emptyBuffer = Buffer(0);

**Comment by charmander** [comment]
Upgrade to Node 7.2.1 or later; see #1198, #1195, #1189, #1163, and #1158.
