### ISSUE TITLE
error database "..." does not exist causes unhandled exception in node.js

### ISSUE THREAD

**Issue by Grumpy-Raymond** [brianc/node-postgres#1233]
When I attempt to connect to a non-existant database using Node.js v7.6.0 and pg 6.1.2 I get the following error and node.js exits.
<code><pre>events.js:161
      throw er; // Unhandled 'error' event
      ^

error: database "missing-database-name" does not exist
    at Connection.parseE (/var/www/html/script-processing/data-ingestion/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/var/www/html/script-processing/data-ingestion/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/var/www/html/script-processing/data-ingestion/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
</pre></code>

The client.query() call is made but the callback function is never reached and node crashes.
<pre><code>public static test_missing(callback: (err: any, result: any) => any) {
        try {
            let client = new pg.Client({
                host: "172.25.1.123",
                port: 5432,
                database: "missing",
                user: "postgres",
                password: "Password123"
            });
            client.connect();
            let query: string = "SELECT * FROM users;";
            client.query(query, function (err, result) {
                try {
                    client.end();
                    callback(err, result);
                } catch (err) {
                    callback(err, null);
                }
            });
        } catch (err) {
            callback(err, null);
        }
    }
</code></pre>

**Comment by charmander** [comment]
Please show the script you’re using.

**Comment by rpedela** [comment]
Don't you need to wait for ```connect()``` to finish via callback before performing a query?

**Comment by charmander** [comment]
Yes: `client.connect` doesn’t throw synchronously.
