### ISSUE TITLE
Issue with pgbouncer/Heroku

### ISSUE THREAD

**Issue by thomasdavis** [brianc/node-postgres#1262]
Hi there,

Trying to connect `pg` to a pgbouncer socket.

I've verified that running the psql statement below works

```
PGPASSWORD=XXXX psql -U YYYY -h /tmp -p 6000 -d db1
```
I'm able to connect and run queries but when I try write the equivalent in `pg`

```
import pg from 'pg';

const client = new pg.Client({
  host: '/tmp',
  user: 'YYYY',
  password: 'XXXX',
  port: 6000,
  database: 'db1',
  ssl: true,
});
client.connect();
client.on('error', function(error) {
  console.log(error);
});
```

I get 
```
Error: The server does not support SSL connections
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:103:33)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:563:20)
```
This is running on Heroku

**Comment by thomasdavis** [comment]
Just disabling ssl fixed it obviously, will figure out later why pgbouncer was not supporting ssl.

Sorry for the clutter!
