### ISSUE TITLE
Connection URI does not work with pg.Pool

### ISSUE THREAD

**Issue by gajus** [brianc/node-postgres#1263]
```js
const pool = new pg.Pool('postgres://postgres:test@12.240.44.14/test');

pool.query('SELECT 1');

```

Produces an error:

```
Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1029:11)
    at exports._exceptionWithHostPort (util.js:1052:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

```

**Comment by gajus** [comment]
The documentation is really not clear here.

* examples indicate that the above should work
* `pg-pool` does not support connection URI
* `pg` normalizes the config at the [`connect`](https://github.com/brianc/node-postgres/blob/71a136488bf99b4ccdb4912902c451c74314d48c/lib/index.js#L59)

Therefore, one would think that the following will work:

```js
const pool = new pg.Pool();

await pool.connect('postgres://postgres:test@12.240.44.14/test');

await pool.query('SELECT 1');

```

but this gives an error down the line:

```js
TypeError: cb is not a function
    at BoundPool.<anonymous> (/Users/gajus/Documents/dev/gajus/mightyql/node_modules/pg-pool/index.js:87:11)
    at /Users/gajus/Documents/dev/gajus/mightyql/node_modules/generic-pool/lib/generic-pool.js:339:9
    at BoundPool.<anonymous> (/Users/gajus/Documents/dev/gajus/mightyql/node_modules/pg-pool/index.js:71:7)
    at Connection.<anonymous> (/Users/gajus/Documents/dev/gajus/mightyql/node_modules/pg/lib/client.js:186:5)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/gajus/Documents/dev/gajus/mightyql/node_modules/pg/lib/connection.js:86:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)

```

**Comment by gajus** [comment]
The reason for `TypeError: cb is not a function` is because `pool.connect` passes delegates connection creation directly to `pg-pool` with the original parameters.

**Comment by gajus** [comment]
The only way I've figured to do this is to parse the config myself, e.g.

```js
import {
  parse as parseConnectionString
} from 'pg-connection-string';

// [..]

const pool = new pg.Pool(typeof configuration === 'string' ? parseConnectionString(configuration) : configuration);

```

which makes `pg.Pool` and `pg.Client` APIs inconsistent.

If I am missing something, please correct me.

**Comment by charmander** [comment]
See #1141.
