### ISSUE TITLE
Unable to re-use position value placeholders

### ISSUE THREAD

**Issue by gajus** [brianc/node-postgres#1264]
The following query:

```sql
SELECT
  event.id
FROM event
WHERE
  venue_id = $1 AND
  movie_id = $2 AND
  starts_at = $3::timestamp AT TIME ZONE (
    SELECT
      locality.timezone
    FROM venue
    INNER JOIN locality
    ON locality.id = venue.locality_id
    WHERE venue.id = $1
  )
LIMIT 2

```

When executed with 3 parameters produces the following error:

```
error: bind message supplies 4 parameters, but prepared statement "" requires 3
    at Connection.parseE (/Users/gajus/Documents/dev/applaudience/showtime-data-management-program/node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/Users/gajus/Documents/dev/applaudience/showtime-data-management-program/node_modules/pg/lib/connection.js:396:17)
    at Socket.<anonymous> (/Users/gajus/Documents/dev/applaudience/showtime-data-management-program/node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:554:20)

```

Expected behaviour:

Expect to be able to refer to a single value more than once.

**Comment by gajus** [comment]
Sorry, misread the error.
