### ISSUE TITLE
error: operator does not exist: # integer

### ISSUE THREAD

**Issue by dmr07** [brianc/node-postgres#1346]
**Current Behavior:**
Insert statement with more than 5 values causes this error. Removing any one of those values would result in a successful insertion.

Insert Statement:
```javascript
...
pool.query("INSERT INTO \
    stories (location_city, location_state, location_country, location_geohash, slug ) \
    VALUES ($1, $2, $3, $4, $5) RETURNING *", 
    [ s.location_city, s.location_state, s.location_country, s.location_geohash, slug], function (err, result) {
    if (err) { console.log(err); return next(err); };
    next(result.rows[0])
}); // end
```

Data To Be Inserted:
```javascript
{ 
  slug: 'something-dkdf-',  
  date_created: 2017-06-26T07:14:03.338Z,
  location_city: 'Culver',
  location_state: ' Oregon',
  location_country: ' United States',
  location_geohash: '9rcv39xkfh3dzzehzem2',
  ... }
```

Full Error:
```javascript
{ error: operator does not exist: # integer
    at Connection.parseE (/Users/Dan/Projects/Oria/server/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/Users/Dan/Projects/Oria/server/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/Users/Dan/Projects/Oria/server/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',
  length: 197,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No operator matches the given name and argument type(s). You might need to add explicit type casts.',
  position: '119',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_oper.c',
  line: '726',
  routine: 'op_error' }
```

**Expected Behavior:** 
Successful insertion of all values into their respective columns. 

**Version Information**
Environment: OSX 10.12.6 Beta (localhost)
Node: 7.4.0
Postgres: 9.6.2
Pg: 6.1.2

**Comment by sibedge** [comment]
>  hint: 'No operator matches the given name and argument type(s). You might need to add explicit type casts.',

The error tells you right there that your SQL type is wrong, and possibly requires casting. This is not related to the driver.

**Comment by dmr07** [comment]
@sibedge I've explicitly typecast every variable and its still happening. The db, tables and column structures are set up using Postico. Could that be a problem?

I also ran `console.log(typeof <incoming data field> )` and each returned `string`. Not sure what else I can do at this point.

```javascript
pool.query("INSERT INTO \
    stories (location_city, location_state, location_country, location_geohash, slug ) \
    VALUES ($1::text, $2::text, $3::text, $4::text, $5::text) RETURNING *", 
    [ s.location_city, s.location_state, s.location_country, s.location_geohash, slug], function (err, result) {
    if (err) { console.log(err); return next(err); };
    next(result.rows[0])
}); // end
```

**Comment by dmr07** [comment]
Syntax error. My fault, not an issue with pg. 

@sibedge thanks for your help.
