### ISSUE TITLE
Immediately getting Error: Connection terminated when creating a pool

### ISSUE THREAD

**Issue by arikalfus** [brianc/node-postgres#1355]
I am trying to run a transaction, and when I call `pool.connect(function (err, client, release) {})`, the `err` always exists and is:
```
Error: Connection terminated
    at Client.<anonymous> (<project root path>/node_modules/pg/lib/client.js:210:17)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Connection.emit (events.js:207:7)
    at Socket.<anonymous> (<project root path>/node_modules/pg/lib/connection.js:138:10)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```

Here's what I'm doing:
```
const dbConfig = {
    user: params.dbUser,
    database: params.dbName,
    host: params.dbHost,
    port: params.dbPort,
    max: params.dbPool,
    idleTimeoutMillis: params.dbConnTimeout
  };

  if (params.dbPass) {
    dbConfig.password = params.dbPass;
  }

  if (params.ssl && params.ssl.useSSL) {
    dbConfig.ssl = {
      rejectUnauthorized: true,
      ca: params.ssl.ca,
      cert: params.ssl.cert,
      key: params.ssl.key
    };
  }

  console.log('Establishing pooled connection');
  const pool = new pg.Pool(dbConfig);
  pool.connect((err, client, release) => { // testing it
    err ? console.log('FAILED', err) : console.log('WORKED');
    release();
  });
```

I'm testing with a local database so there is no SSL connection and no DB password. `params` is a variable object created in a separate config file. If I `console.log` the `dbConfig` object before I run `new pg.Pool`, I get:
```
dbConfig { user: '<my username>',
  database: '<database name>',
  host: 'localhost',
  port: '27017',
  max: 30,
  idleTimeoutMillis: 3000 }
```

Every time this runs I get the above error. Not that the actual transaction code is fuller and has actual handling of the client ending with a `client.query('COMMIT', (err) => release(err))`. However, this above test code also produces the error. What am I doing incorrectly?

**Comment by charmander** [comment]
27017 is the default MongoDB port. Are you sure you’re running a PostgreSQL server on that port?

**Comment by arikalfus** [comment]
Aaand it's always the little things. This was part of a migration from mongo to postgres. Thank you :joy:
