### ISSUE TITLE
Probably just being a ES7 n00b, but `await` doesn't seem to work as documented

### ISSUE THREAD

**Issue by d11wtq** [brianc/node-postgres#1385]
I'm trying to use the `await` style of coding with node-postgres, but I can't seem to actually handle Exceptions that are thrown from it. In particular, if I run this script with a bad hostname (resulting in connection refused), it just crashes, even though the code is wrapped with a try/catch block. I'm probably just not understanding how to do this with `await` and `async function`, as this is the first ES7 code I've ever written, however the documentation for `await` suggests it should not produce any uncaught Exceptions.

Any pointers?

``` javascript
const pg = require('pg');

const interval = parseInt(process.env['INTERVAL'] || 30) * 1000;
const exchange = process.env['EXCHANGE'];
const logTag = '[live-quotes]';

/**
 * Update live quote data once.
 */
async function updateQuotes() {
  try {
    console.log('%s starting', logTag);
    const client = new pg.Client();
    await client.connect(); // <-- THIS LINE THROWS EXCEPTION THAT IS NOT CAUGHT
    const res = await client.query(
      'SELECT symbol FROM companies WHERE exchange = $1',
      [exchange]
    );
    res.rows.forEach(row => console.log(row));
    await client.end();
    console.log('%s done', logTag);
  } catch (e) {
    console.log('%s fail [%s]', logTag, e.message);
  }
}

/**
 * Continually run the updateQuotes() procedure every env['INTERVAL'] seconds.
 */
async function run() {
  await updateQuotes();
  setTimeout(run, interval);
}

run();
```

Running on Node.js 8.2.1, without Babel and without Harmony (should work fine).

```
$ node src/bin/live-quotes-worker.js
[live-quotes] starting
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
```

**Comment by d11wtq** [comment]
Never mind, I was being a n00b and I had copied and pasted the `pg` line to package.json from an older app, so it was out of date (5.0.1).
