### ISSUE TITLE
Cannot create and drop

### ISSUE THREAD

**Issue by 8888ACC** [brianc/node-postgres#1425]
When I try to run

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

The following error occur

error: schema "public" does not exist
    at Connection.parseE (node_modules\pg\lib\connection.js:567:11)
    at Connection.parseMessage (node_modules\pg\lib\connection.js:391:17)
    at Socket.<anonymous> (node_modules\pg\lib\connection.js:129:22)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)

I can however, run these manually in console. Wondering what is wrong?

**Comment by 8888ACC** [comment]
Nothing is wrong. 
I just need to add 

DROP SCHEMA IF EXISTS public CASCADE;
