### ISSUE TITLE
Block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by jonahbron** [brianc/node-postgres#1455]
I'm working on updating pg in my application.  However, I'm running into this error now:

```
Uncaught Exception Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.cls_wrapMethod [as _load] (/home/jonah/Projects/app/node_modules/newrelic/lib/shimmer.js:235:38)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at require (/home/jonah/Projects/app/node_modules/connectors/postgres/node_modules/pg/lib/index.js:1:258)
    at Object.<anonymous> (/home/jonah/Projects/app/node_modules/connectors/postgres/node_modules/pg/lib/index.js:11:14)
```

I'm running node 4.5.0 (which the docs and package.json say is supported).  This error appears to originate from `lib/index.js:11`, but the error doesn't make sense there because that file activates strict mode at the top of the file.

```
'use strict'
/**
 * Copyright (c) 2010-2017 Brian Carlson (brian.m.carlson@gmail.com)
 * All rights reserved.
 *
 * This source code is licensed under the MIT license found in the
 * README.md file in the root directory of this source tree.
 */

var util = require('util')
var Client = require('./client')
var defaults = require('./defaults')
var Connection = require('./connection')
var Pool = require('pg-pool')
...
```

Any help would be appreciated, and I'm happy to provide more system info.

**Comment by jonahbron** [comment]
This error occurs in all 7.x versions.  6.4.2 seems to work fine.

**Comment by charmander** [comment]
Try it without the New Relic wrapper?

**Comment by jonahbron** [comment]
@charmander I just tried your recommendation, and nothing changed but the stack trace.

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at require (/home/jonah/Projects/app/node_modules/connectors/postgres/node_modules/pg/lib/index.js:1:258)
    at Object.<anonymous> (/home/jonah/Projects/app/node_modules/connectors/postgres/node_modules/pg/lib/index.js:11:14)
    at Module._compile (module.js:409:26)
```

**Comment by charmander** [comment]
Are you still able to reproduce this?

**Comment by jonahbron** [comment]
@charmander We've been able to get around it by upgrading Node versions.  Based on that, it might be necessary to update the required Node version in `node-postgres/package.json`

**Comment by charmander** [comment]
I’ve tested it again – pg 7.4.0 on Node 4.5.0 – and it works fine. If anyone else runs into this, please leave a comment.
