### ISSUE TITLE
Does pg 7.4.0 work with PostGIS 2.4.1 ?

### ISSUE THREAD

**Issue by fernandocanizo** [brianc/node-postgres#1495]
I'm getting this stack trace when trying to anything database-related:

```
error: undefined error: could not access file "$libdir/postgis-2.3": No such file or directory
    at Connection.parseE (/.../node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/.../node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/.../node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

**Comment by charmander** [comment]
That appears to be a server-side error. If you run the same query with `psql`, does it work?

**Comment by fernandocanizo** [comment]
Sorry, I forgot about this. Yes, the queries did work from `psql`. However I cannot reproduce this anymore now: I finished doing a big upgrade on my machine and now the error is gone.

**Comment by charmander** [comment]
Okay. If you run into it again, just leave a comment. =)
