### ISSUE TITLE
error: password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by zhailei31665431** [brianc/node-postgres#1511]
I'm running my app on Node v7.10.0, PostgreSQL 9.5.5, and Ubuntu 14. Which uses pg, refuses to make any connections and throws this error instead:

at Connection.parseE (/Users/zhailei/Documents/github/recordApp/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/Users/zhailei/Documents/github/recordApp/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/Users/zhailei/Documents/github/recordApp/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
  name: 'error',
  length: 104,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '307',
  routine: 'auth_failed' }

**Comment by charmander** [comment]
Was it your intent to use password authentication? With which user? The error indicates the password you’re providing for that user (postgres) is incorrect.

**Comment by brianc** [comment]
Closing as dead.
