### ISSUE TITLE
rollback is not a function

### ISSUE THREAD

**Issue by PierreGriffith** [brianc/node-postgres#1513]
TypeError: rollback is not a function
    at sendError (C:\Users\Melchior\Desktop\V2-Serveur\routes\login\reset-password.js:94:15)
    at db.transaction (C:\Users\Melchior\Desktop\V2-Serveur\routes\login\reset-password.js:24:20)
    at onError (C:\Users\Melchior\Desktop\V2-Serveur\services\database.js:71:10)
    at pool.connect (C:\Users\Melchior\Desktop\V2-Serveur\services\database.js:46:17)
    at client.connect (C:\Users\Melchior\Desktop\V2-Serveur\node_modules\pg-pool\index.js:219:9)
    at Connection.connectingErrorHandler (C:\Users\Melchior\Desktop\V2-Serveur\node_modules\pg\lib\client.js:123:14)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (C:\Users\Melchior\Desktop\V2-Serveur\node_modules\pg\lib\connection.js:118:12)
    at emitOne (events.js:96:13)

i dont understand this mistake i never had it, it just popped out from nowhere.

**Comment by sehrope** [comment]
You're calling a `rollback()` function on something that does not have that function defined. You likely never saw it before because whatever leads to the rollback situation wasn't happening (but now is).

This is something specific to your code, not the node-postgres driver itself. Without seeing more of your code or being to reproduce it, nobody is going to be able to help you.

**Comment by PierreGriffith** [comment]
sorry for the disagreement, i've just made a mistake in credentials.

at Socket. (C:\Users\Melchior\Desktop\V2-Serveur\node_modules\pg\lib\connection.js:118:12)

i put a wrong password in pg,
