### ISSUE TITLE
Blocking node event loop

### ISSUE THREAD

**Issue by DiegoRBaquero** [brianc/node-postgres#1531]
Hey guys,

I found that the following block of code is really blocking https://github.com/brianc/node-postgres/blob/master/lib/connection.js#L113-L120

I'm using `blocked-at` and it shows:

```
Blocked for 708.2884980163574ms, operation started here:  [ '    ...
  '    at Result.client.query (.../node_modules/sequelize/lib/dialects/postgres/query.js:65:113)',
  '    at Result.Query.handleReadyForQuery (.../node_modules/pg/lib/query.js:144:10)',
  '    at Connection.<anonymous> (.../node_modules/pg/lib/client.js:180:19)',
  '    at emitOne (events.js:116:13)',
  '    at Connection.emit (events.js:211:7)',
  '    at Socket.<anonymous> (/.../node_modules/pg/lib/connection.js:133:12)',
  '    at emitOne (events.js:116:13)',
  '    at Socket.emit (events.js:211:7)',
  '    at addChunk (_stream_readable.js:263:12)',
  '    at readableAddChunk (_stream_readable.js:250:11)',
  '    at Socket.Readable.push (_stream_readable.js:208:10)',
  '    at TCP.onread (net.js:594:20)' ] +995ms
```

For big queries, that while can consume a lot of time.

**Comment by charmander** [comment]
What kind of query did you run to produce those results? Could you include an `npm ls`?

**Comment by DiegoRBaquero** [comment]
The query is the following:
```
SELECT <main table fields>, <second table fields>, <third table fields> FROM "MAIN" AS "MAIN" LEFT OUTER JOIN "SECOND" AS "SECOND" ON "Main"."id" = "Second"."fk_id" LEFT OUTER JOIN "THIRD" AS "THIRD" ON "Main"."id" = "Third"."fk_id" WHERE "Main"."id" = '1';
```

Sorry I had to remove the fields. Second table has 27k rows.

Sequelize code: `Main.findById(req.params.id, {include: [Second, Third]})`

npm ls:
```
├─┬ pg@6.4.2
│ ├── buffer-writer@1.0.1
│ ├── js-string-escape@1.0.1
│ ├── packet-reader@0.3.1
│ ├── pg-connection-string@0.1.3
│ ├─┬ pg-pool@1.8.0
│ │ ├── generic-pool@2.4.3
│ │ └── object-assign@4.1.0
│ ├─┬ pg-types@1.12.1
│ │ ├── postgres-array@1.0.2
│ │ ├── postgres-bytea@1.0.0
│ │ ├── postgres-date@1.0.3
│ │ └─┬ postgres-interval@1.1.1
│ │   └── xtend@4.0.1 deduped
│ ├─┬ pgpass@1.0.2
│ │ └─┬ split@1.0.0
│ │   └── through@2.3.8 deduped
│ └── semver@4.3.2
```

This happens in latest version.

I'm using Node 8.9.1

**Comment by charmander** [comment]
How many fields are there, and what are their types? How many rows in total?

**Comment by DiegoRBaquero** [comment]
15 on main, 6 on second, 10 on third.

There are 27k row in second.

**Comment by charmander** [comment]
What are their types? How many rows does the query return in total (not just the second table)?

**Comment by DiegoRBaquero** [comment]
Tracking it down. Not pg fault. It's in sequelize. Thanks a lot!
