### ISSUE TITLE
doc example failed

### ISSUE THREAD

**Issue by le93us** [brianc/node-postgres#1564]
Latest `debian 9`, `node 9`, `pg` and `postgres` from `docker`.

```js
const { Pool, Client } = require('pg')

// pools will use environment variables
// for connection information
const pool = new Pool()

pool.query('SELECT NOW()', (err, res) => {
  console.log(err, res)
  pool.end()
})

// you can also use async/await
const res = await pool.query('SELECT NOW()')
await pool.end()

// clients will also use environment variables
// for connection information
const client = new Client()
await client.connect()

const res = await client.query('SELECT NOW()')
await client.end()
```

error:
```sh
$ PGUSER=postgres   PGHOST=localhost     PGPASSWORD=superpassword       PGDATABASE=mydb         PGPORT=5432           node index.js 

/home/le93us/Desktop/node-postgres/index.js:13
const res = await pool.query('SELECT NOW()')
            ^^^^^

SyntaxError: await is only valid in async function
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
```

Can someone help to fix it?

**Comment by alvincrespo** [comment]
How did you solve this @le93us ?
