### ISSUE TITLE
Failure when listing tables

### ISSUE THREAD

**Issue by bencmbrook** [brianc/node-postgres#1594]
`client.query('SELECT * FROM information_schema.tables WHERE table_schema = pg_catalog';)`

yields this error
```
error: column "pg_catalog" does not exist in tables
    at Connection.parseE (/Users/example/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/Users/example/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/Users/example/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

The [query itself doesn't have issues](https://stackoverflow.com/a/15644435/3724563
). There are also [no trailing spaces, or mixed case](https://stackoverflow.com/questions/10200769/postgresql-column-foo-does-not-exist).

Trying `client.query('SELECT table_schema FROM information_schema.tables;')` works. It returns many instances of `{"table_schema":"pg_catalog"}`. So it's there, but somehow it's now working with the WHERE statement. 

This leads me to believe there's something happening with node-postgres. Or something funky is happening with permissions on the Redshift instance I'm connected to. Any thoughts on whether this is a bug with node-postgres?

**Comment by charmander** [comment]
The quotes are missing – `'pg_catalog'`.

```js
client.query("SELECT * FROM information_schema.tables WHERE table_schema = 'pg_catalog'")
```
