### ISSUE TITLE
Failing to insert null into NUMERIC column

### ISSUE THREAD

**Issue by alexgoldstone** [brianc/node-postgres#1613]
I am using pg (not pg-native).

I have a database table with a combination of INTEGER and NUMERIC columns.

I am using the `Parameterized query` method to pass parameters inline with the node-postgres documentation.

Inserting in general is fine. Inserting integer values into INTEGER or NUMERIC columns works fine.

Inserting null values into INTEGER columns works fine.

Inserting null values into NUMERIC columns fails with the following:

```
error: invalid input syntax for integer: "NaN"
    at Connection.parseE (.../node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (.../node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (.../node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

My NUMERIC columns are specified as NUMERIC without any precision or scale.

**Comment by alexgoldstone** [comment]
For anyone finding this in the archive, my issue was that the values were starting as strings and I was casting to parseFloat before passing to node-postgres.

parseFloat returns NaN for strings that cannot be cast to numbers however my logger serialises to JSON (converting NaN to null in the process) so it was not immediately obvious that this was the issue.
