### ISSUE TITLE
Calling SQL-Function with Parameter of type anyelement will fail

### ISSUE THREAD

**Issue by planetarydev** [brianc/node-postgres#1623]
I've got a function in my database with a parameter of type "anyelement".
By calling the function like 
`SELECT myfunction($1, $2) AS result`
with node-postgres it fails with the following error:

```
Result from query { error: konnte polymorphischen Typ nicht bestimmen, weil Eingabe Typ unknown hat
    at Connection.parseE (/home/rene/galaxy/server/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/home/rene/galaxy/server/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/home/rene/galaxy/server/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'error',
  length: 157,
  severity: 'FEHLER',
  code: '42804',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_coerce.c',
  line: '1795',
  routine: 'enforce_generic_type_consistency' }
```

Thats my sample function:

```
CREATE FUNCTION myfunction (
    IN settingsName TEXT,
    IN settingsValue anyelement
)
RETURNS TEXT
AS $FNBODY$
BEGIN
    /* do something
    .... */
END;
$FNBODY$ LANGUAGE PLPGSQL;
```

By calling the function with explicit converting param 2 to text it will run.
`SELECT myfunction($1, $2::text) AS result`

Is there any way to run the query without converting param 2 to type text?

**Comment by charmander** [comment]
It’s not so much converting as specifying in this case. There is the option of specifying parameter types by OID:

```js
const OID_TEXT = 25;

db.query({
    text: "SELECT myfunction($1, $2) AS result",
    types: [OID_TEXT],
    values: […],
})
```

but that’s not really better.
