### ISSUE TITLE
Could not serialize access due to concurrent update even when using advisory lock

### ISSUE THREAD

**Issue by cressie176** [brianc/node-postgres#1625]
Firstly apologies if this ends up being down to my own ignorance or inability to RTFM rather than a problem with node-pg.

I'm getting 40001 / "Could not serialize access due to concurrent update" errors when updating a row in the database concurrently. The isolation level is REPEATABLE READ, but am also using `pg_advisory_xact_lock` which I thought would serialise my access. The following script demonstrates the problem...

```
const { Pool } = require('pg')
const pool = new Pool({ max: 10 });

(async () => {
  const client = await pool.connect();
  await client.query("CREATE TABLE IF NOT EXISTS books (id INTEGER PRIMARY KEY, NAME TEXT NOT NULL)");
  await client.query("INSERT INTO books VALUES (1, 'Kes') ON CONFLICT DO NOTHING");
  await client.release();

  const work = [];
  for (let i = 0; i < 10; i++) {
    work.push((async () => {
      const client = await pool.connect();
      let res = await client .query('SELECT pg_backend_pid()');
      const pg_backend_pid = res.rows[0].pg_backend_pid;
      try {
        await client.query('BEGIN');
        await client.query('SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ');
        await client.query('SELECT pg_advisory_xact_lock(1)');
        let res = await client.query(`SELECT * FROM pg_locks WHERE locktype='advisory' AND mode='ExclusiveLock' AND granted = true AND objid = 1 AND pid = '${pg_backend_pid}'`);
        res.rows.length === 1 ? console.log(`Aquired advisory lock for update ${i} with connection ${pg_backend_pid}`)
                              : console.log(`Failed to aquire advisory lock for update ${i} with connection {pg_backend_pid}`);
        console.log(`About to perform update ${i} with connection ${pg_backend_pid}`);
        await client.query("UPDATE books SET name = 'Kim' WHERE id = 1");
        console.log(`Finished performing update ${i} with connection ${pg_backend_pid}`);
        await client.query('END');
        await client.release();
      } catch (err) {
        console.error(`Failed to perform update ${i} with connection ${pg_backend_pid}`);
        throw err;
      };
    })());
  }
  await Promise.all(work).catch((err) => {
    console.error(err);
  });

  process.exit();
})();


setInterval(() => {}, 10000);
```
The script consistently fails with output similar to the following
```
Aquired advisory lock for update 0 with connection 1677
About to perform update 0 with connection 1677
Finished performing update 0 with connection 1677
Aquired advisory lock for update 1 with connection 1679
About to perform update 1 with connection 1679
Failed to perform update 1 with connection 1679
{ error: could not serialize access due to concurrent update
    at Connection.parseE (/Users/steve/Development/tes/pg-xact-lock-bug/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/Users/steve/Development/tes/pg-xact-lock-bug/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/Users/steve/Development/tes/pg-xact-lock-bug/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'error',
  length: 115,
  severity: 'ERROR',
  code: '40001',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'nodeModifyTable.c',
  line: '985',
  routine: 'ExecUpdate' }
```
I'm at a loss to explain why the serialization fails. I've tried to reproduce using psql and raw SQL without success. Any help you can offer is greatly appreciated.

**Comment by sehrope** [comment]
If you interleave the statements between the two sessions you can reproduce this from psql as well:

Session 1: 

```
app=> BEGIN;
BEGIN
Time: 1.329 ms
app=> SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET
Time: 1.304 ms
app=> SELECT pg_advisory_xact_lock(1);
 pg_advisory_xact_lock 
-----------------------
 
(1 row)

Time: 3.757 ms
app=> \d foo
                Table "public.foo"
 Column |  Type   | Collation | Nullable | Default 
--------+---------+-----------+----------+---------
 id     | integer |           | not null | 
Indexes:
    "foo_pkey" PRIMARY KEY, btree (id)

app=> UPDATE foo SET id = 1 WHERE id = 1;
UPDATE 1
Time: 6.555 ms
app=> COMMIT;
COMMIT
Time: 3.006 ms
```

Session 2:
```
app=> BEGIN;
BEGIN
Time: 0.993 ms
app=> SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET
Time: 1.195 ms
app=> SELECT pg_advisory_xact_lock(1);
 pg_advisory_xact_lock 
-----------------------
 
(1 row)

Time: 20931.287 ms (00:20.931)
app=> UPDATE foo SET id = 1 WHERE id = 1;
ERROR:  40001: could not serialize access due to concurrent update
LOCATION:  ExecUpdate, nodeModifyTable.c:722
Time: 2.136 ms
```

The problem is that changing the transaction isolation level needs to be the first command executed after the BEGIN. That means you don't acquire the advisory lock until after that point and the snapshot is from *before* the lock acquisition.

For this type of explicit serialization you can instead use a regular (non-xact) lock: `SELECT pg_advisory_lock(1)` and explicitly unlock it when the transaction completes. So something like:

1. `SELECT pg_advisory_lock(1)`
2. BEGIN
3. Change to repeatable read
4. Do stuff
5. COMMIT or ROLLBACK
6. `SELECT pg_advisory_unlock(1)` (or unlock all)

Watch out to make sure you actually release the locks as they're carried across transaction boundaries. Also, make sure you release the connection back to the pool for discarding on error (i.e. `client.release(err)`).
