### ISSUE TITLE
Prepared Statement doesn't require any parameters

### ISSUE THREAD

**Issue by EmrysMyrddin** [brianc/node-postgres#1630]
I'm trying to make an update for multiple rows at once.
For this, I'm making the folowing prepared statement :

```sql
WITH new_values (id, data, email) AS (
  VALUES ($1, $2, $3), ($4, $5, $6), ($7, $8, $9), ($10, $11, $12)
)
UPDATE prospects
  SET 
    data = new_values.data,
    email = new_values.email
  FROM new_values
  WHERE
    prospects.id = new_values.id
  RETURNING *
```

But I'm getting the following error :

```
error: bind message supplies 12 parameters, but prepared statement "prospects-multi-update" requires 0
api-prospects_1       |     at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:546:11)
api-prospects_1       |     at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:371:19)
api-prospects_1       |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:114:22)
api-prospects_1       |     at Socket.emit (events.js:180:13)
api-prospects_1       |     at addChunk (_stream_readable.js:274:12)
api-prospects_1       |     at readableAddChunk (_stream_readable.js:261:11)
api-prospects_1       |     at Socket.Readable.push (_stream_readable.js:218:10)
api-prospects_1       |     at TCP.onread (net.js:581:20)
```

I have tried different queries (with `INSERT ... ON CONFLICT DO UPDATE`) but it does the same.

It's working only on straight `INSERT INTO` queries.

**Comment by sehrope** [comment]
What's the code that is creating the prepared statement? Would help figure out the cause.

Separately, you may want to check out using arrays or JSON types instead of a dynamic list of values. You can use it to pass in an arbitrary number of parameters:

```sql
SELECT
  (data->>'id')::int AS id,
  data->>'name' AS name
FROM json_array_elements(
        '[{"id": 1, "name": "foo"}, {"id": 2, "name": "bar"}]'::json
     ) AS data
```

You could replace the `new_values` in your UPDATE with something similar to that in a nested sub-SELECT with the literal JSON as $1 and execute with a single parameter matching that JSON shape being specified.

**Comment by EmrysMyrddin** [comment]
Here is the full code. I have removed some unrelated codes but have kept all code that will actually run when this query is executed.

```es6
const omit = require('lodash/omit')
const partition = require('lodash/partition')
const flatten = require('lodash/flatten')
const { query } = require('../../pg')

const makeColumnVariableGetter = columns => row => (colName, colIndex) =>
  `$${row * columns.length + colIndex + 1}`

module.exports = (resourceName, specificColumns = []) => {
  const columns = ['data', ...specificColumns]

  const insertValues = async (entities) => // [...]

  const upsertValues = async (entities) => {
    if (entities.length === 0) return []
    const getColumnVariable = makeColumnVariableGetter(['id', ...columns])

    const values = entities.map(entity => [
      entity.id,
      omit(entity, ['id', ...specificColumns]),
      ...specificColumns.map(column => entity[column]),
    ])

    const variables = entities
      .map((entity, row) => `(${['id', ...columns].map(getColumnVariable(row)).join(', ')})`)
      .join(', ')

    const setStatements = columns
      .map(column => `${column} = new_values.${column}`)
      .join(', ')

    const res = await query({
      name: `${resourceName}-multi-update`,
      test: `
        WITH new_values (id, ${columns.join(', ')}) AS (
          VALUES ${variables}
        )
        UPDATE prospects
          SET ${setStatements}
          FROM new_values
          WHERE
            prospects.id = new_values.id
          RETURNING *
      `,
      values: flatten(values),
    })

    return res.row || []
  }

  return async (data) => {
    const [existingEntities, newEntities] = partition(data, 'id')

    const results = Promise.all([
      insertValues(newEntities),
      upsertValues(existingEntities),
    ])

    return flatten(results).map((row) => {
      const entity = { ...row.data, id: row.id }

      specificColumns.forEach((column) => {
        entity[column] = row[column]
      })

      return entity
    })
  }
}

```

**Comment by charmander** [comment]
> ```javascript
>       test: `
> ```

This should be “te**x**t”. If you didn’t already execute a query with the same name, though, it should fail, so it might be correct in the actual code. Anyway, the main problem is the named query, which you definitely don’t want here; the same query will be reused every time, even when the number of parameters or the specific columns to update differ.

**Comment by EmrysMyrddin** [comment]
Yes I have just found out this `test` typo... It was the problem.
I wasn't aware of this "limitation" of named query. I haven't any problem with other queries built like this one from now. 
You suggest to remove the `name` property ?

**Comment by charmander** [comment]
Yes. It’s not a limitation; it’s what it’s intended to do.

**Comment by EmrysMyrddin** [comment]
Yes I understand, it's just not want I was expecting !
Thank you for your help.
