### ISSUE TITLE
array_remove() does not exist

### ISSUE THREAD

**Issue by Rc85** [brianc/node-postgres#1662]
Not sure if this is the pg library or Postgres itself. I have Postgres 10.1 installed on my desktop and using the array_remove() function in my node application gives me an error in console. However, using the function in pg CLI, it works.

    { error: function array_remove(integer[], integer[]) does not exist
        at Connection.parseE (D:\Projects\healme\node_modules\pg\lib\connection.js:553:11)
        at Connection.parseMessage (D:\Projects\healme\node_modules\pg\lib\connection.js:378:19)
        at Socket.<anonymous> (D:\Projects\healme\node_modules\pg\lib\connection.js:119:22)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at addChunk (_stream_readable.js:263:12)
        at readableAddChunk (_stream_readable.js:250:11)
        at Socket.Readable.push (_stream_readable.js:208:10)
        at TCP.onread (net.js:594:20)
      name: 'error',
      length: 227,
      severity: 'ERROR',
      code: '42883',
      detail: undefined,
      hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
       position: '88',
       internalPosition: undefined,
       internalQuery: undefined,
       where: undefined,
       schema: undefined,
       table: undefined,
       column: undefined,
       dataType: undefined,
       constraint: undefined,
       file: 'parse_func.c',
       line: '528',
       routine: 'ParseFuncOrColumn' }

**Comment by charmander** [comment]
`array_remove` accepts an array and an element to remove, so the issue is with the query.
