### ISSUE TITLE
Operator does not exist: text ~ integer

### ISSUE THREAD

**Issue by vegas23** [brianc/node-postgres#1686]
I've run into an issue where a query I'm using uses the regular expression operator ~* and ~ but I receive a parsing error doing it. 

> events.js:167
      throw er; // Unhandled 'error' event
      ^
>
> error: operator does not exist: text ~ integer
    at Connection.parseE (/Users/martin/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/Users/martin/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/Users/martin/node_modules/pg/lib/connection.js:117:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:262:11)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onread (net.js:638:20)
Emitted 'error' event at:
    at Query.handleError (/Users/martin/node_modules/pg/lib/query.js:131:8)
    at Connection.<anonymous> (/Users/martin/node_modules/pg/lib/client.js:180:26)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/martin/node_modules/pg/lib/connection.js:121:12)
    at Socket.emit (events.js:182:13)
    [... lines matching original stack trace ...]
    at TCP.onread (net.js:638:20)

I'm working on finding an alternative but it would be very useful to have this library recognize this operator!

My code looks like this:

```javascript
getSQL(`select item_number, sum(round(noNeg(coitem_qtyord - coitem_qtyshipped + coitem_qtyreturned - qtyatshipping(coitem_id)))) as balance
                from cohead
                left outer join coitem on(coitem_cohead_id = cohead_id)
                left outer join itemsite on(itemsite_id = coitem_itemsite_id)
                left outer join item on(item_id = itemsite_item_id)
                left outer join rahead on(rahead_new_cohead_id = cohead_id)
                where rahead ISNULL 
                    and coitem_status NOT IN(\'C\', \'X\') 
                    and cohead_number ~ `+ordQuery+`
                    and(extract(week from coitem_scheddate) = extract(week from current_date))
                group by item_number
                order by item_number`,targetCol, 'ROWS');
```

**Comment by sehrope** [comment]
This isn't a driver issue. Your SQL is being generated by concatenating the value of `ordQuery` into the middle of the string and `ordQuery` is a number rather than a quoted literal. The same error shows up in psql if you try something like: 

```sql
=> SELECT 'test'::text ~ 123

ERROR:  42883: operator does not exist: text ~ integer
LINE 1: SELECT 'test'::text ~ 123;
```

You should either escape/quote it (so `1` becomes `'1'`) or even better specify it as a parameter and ensure that it's converted to a string beforehand:

```js
const ordQueryText = '' + ordQuery;
const sql = 'SELECT * FROM foo WHERE cohead_number ~ $1';
const result = await pool.query(sql, [ordQueryText]);
```

Also, checkout the markdown guide for formatting code blocks. It makes it easier for others to read your code and understand the issue: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code
