### ISSUE TITLE
Password authentication failed for user "Matt" even though PGUSER is set to "postgres"

### ISSUE THREAD

**Issue by heath3n** [brianc/node-postgres#1719]
Maybe I'm just misunderstanding how the connection works but I set `PGUSER`, `PGPASSWORD`, etc. in a `.env` file. When I run the app with `node server.js` it works fine; I can connect to the database with no problem. When I have `"scripts": { "start": "node src/server.js" }` in my `package.json` and use `npm start` however, I get the following:

```
{ error: password authentication failed for user "Matt"
    at Connection.parseE (C:\Users\Matt\Documents\Cloud\Projects\2018-2019\NodeTest\test-server\node_modules\pg\lib\connection.js:553:11)
    at Connection.parseMessage (C:\Users\Matt\Documents\Cloud\Projects\2018-2019\NodeTest\test-server\node_modules\pg\lib\connection.js:378:19)
    at Socket.<anonymous> (C:\Users\Matt\Documents\Cloud\Projects\2018-2019\NodeTest\test-server\node_modules\pg\lib\connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  name: 'error',
  length: 100,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '328',
  routine: 'auth_failed' }
```

1) Where is the user "Matt" coming from? I only ever used the `postgres` user.
1) Why do I get an error when using `npm start` when it just runs the same script that works fine?

**Comment by charmander** [comment]
What reads .env? `node server.js` and `node src/server.js` aren’t the same, and the different working directory could be responsible for the difference.

**Comment by heath3n** [comment]
Huh. So it looks like when I run `node src/server.js` I get the same error as above, but if I go into the `src` directory, running `node server.js` gives me no issue. Running `npm start` from anywhere still gives me the issue.

`server.js` reads `.env` using `require('dotenv').config();` as the first line. Technically it's another file `db.js` that uses the variables to connect to PostgreSQL but like I said, it connects fine when I run normally. I tried adding the dotenv require to the top of every file and nothing changed.

**Comment by charmander** [comment]
[Specify a path][1] based on `__dirname` so you can run it from any directory. (npm scripts always move to where package.json is.)

[1]: https://www.npmjs.com/package/dotenv#path
