### ISSUE TITLE
bug: "syntax error at or near" when queries nest too much IN/ANY

### ISSUE THREAD

**Issue by flockonus** [brianc/node-postgres#1731]
I just opened this issue in `knex`, but now I realized the error seems to be in pg. Do you have a workaround in mind for it?

[Full description, including a reproduction scenario](https://github.com/tgriesser/knex/issues/2812)

**Comment by charmander** [comment]
Can you confirm that the Knex script still produces an error (`node some-script.js`), then paste the unmodified output of `xxd some-script.js` in a comment?

**Comment by flockonus** [comment]
ok, i think i figured out what it was... most likely: invisible characters copied from Postico! After re-formatting everything errors went away.

Here is a sample of the seemingly random error messages i was getting, which for some reason wasn't a problem in Postico itself, maybe they replace those before submitting?

Anyways, feel free to close by my account. Thank you @charmander 

```
{ error: syntax error at or near "  AND"
    at Connection.parseE (/Users/fps/workspace/axiomzen/cryptokitties-api/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/Users/fps/workspace/axiomzen/cryptokitties-api/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/Users/fps/workspace/axiomzen/cryptokitties-api/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'error',
  length: 97,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '896',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1086',
  routine: 'scanner_yyerror' }


{ error: syntax error at or near "  "
    at Connection.parseE (/Users/fps/workspace/axiomzen/cryptokitties-api/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/Users/fps/workspace/axiomzen/cryptokitties-api/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/Users/fps/workspace/axiomzen/cryptokitties-api/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'error',
  length: 95,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '2194',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1086',
  routine: 'scanner_yyerror' }

{ error: missing FROM-clause entry for table "  kc"
    at Connection.parseE (/Users/fps/workspace/axiomzen/cryptokitties-api/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/Users/fps/workspace/axiomzen/cryptokitties-api/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/Users/fps/workspace/axiomzen/cryptokitties-api/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'error',
  length: 119,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '2079',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3140',
  routine: 'errorMissingRTE' }
```
