### ISSUE TITLE
pg-query-stream fails with 7.5.0

### ISSUE THREAD

**Issue by toddself** [brianc/node-postgres#1742]
Using pg 7.4.3, works great.

Upgraded to 7.5.0 this morning and getting this stack trace:

```
/usr/lib/node_modules/@scriptollc/search-crawler/node_modules/pg/lib/client.js:277
    if (self.activeQuery.name) {
                         ^

TypeError: Cannot read property 'name' of null
    at Connection.<anonymous> (/usr/lib/node_modules/@scriptollc/search-crawler/node_modules/pg/lib/client.js:277:26)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/usr/lib/node_modules/@scriptollc/search-crawler/node_modules/pg/lib/connection.js:124:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

The query being run is a very simple 

```
format(`SELECT * FROM %I`, tableName)
```

Doesn't matter which table in our database we use.

Happy to assist with anything you might need!

**Comment by brianc** [comment]
Thanks for reporting this. I apologize for the break.  Do you have a snippet of code I could check out to reproduce the issue?

**Comment by toddself** [comment]
Thanks for the quick reply!

```js
function indexTable (table, client, channel) {
  return new Promise((resolve, reject) => {
    let date = ''
    if (argv.date) {
      date = format(`WHERE
        (data ? 'modiifed' AND (data->>'modified'::timestamp > '%s'::timestamp)
        OR
        (NOT data ? 'modified' AND (data->>'created'::timestamp > '%s'::timestamp)
      `, argv.date, argv.date)
    }
    const sql = format(`SELECT * FROM %I${date}`, table)
    const query = new QueryStream(sql)
    const stream = client.query(query)

    stream.on('error', reject)

    stream.on('data', (data) => {
      const timestamp = (new Date()).getTime()
      const columns = Object.keys(data)
      const placeholders = columns.map((c, i) => ('$' + (i + 1)))
      const query = format(`INSERT INTO %I (${columns.join(',')}) VALUES (${placeholders.join(',')})`, table)
      log.trace(`Indexing ${query}`)
      const args = Buffer.from(JSON.stringify(columns.map((column) => data[column])), 'utf8')
      const msg = IndexMessage.encode({
        query,
        timestamp,
        args
      })
      channel.sendToQueue(rabbitQueue, msg)
    })

    stream.on('end', () => {
      log.debug('Stream ended')
      resolve()
    })
  })
}
```

This is called with `indexTable('script', client, channel)`

The schema for `script` is:

`CREATE TABLE script (key uuid, data jsonb)`

**Comment by toddself** [comment]
LOL also noticed I said I upgraded to 7.4.0 in my original message; I fixed that to say 7.5.0 :)

**Comment by andrewspinks** [comment]
I have the same error:

```const pg = require('pg')
const QueryStream = require('pg-query-stream')

exports.queryStream = async (text, params, batchSize) => {
  const pool = new pg.Pool()
  const client = await pool.connect()
  const query = new QueryStream(text, params, {batchSize})
  const stream = client.query(query)

  stream
    .on('error', (err) => {
      console.error('Error running query stream', err)
      client.end()
      throw err
    })
    .on('end', () => {
      client.end()
    })

  return stream
}

exports.queryStream(
  `SELECT * from information_schema.tables`, [], 100).then(console.log)
```

Reverting  to 7.4.3 works.

**Comment by whatl3y** [comment]
Same issue here, I'll be using 7.4.3 for now until this is fixed in 7.5.x

**Comment by brianc** [comment]
please feel free to reopen if the fix in pg-query-stream doesn't fix your issue.

**Comment by toddself** [comment]
super late to say thank you but thank you!

**Comment by brianc** [comment]
happy to help!
