### ISSUE TITLE
Incorrect number of parameters for prepared statement - Error 26000

### ISSUE THREAD

**Issue by Gargarensis** [brianc/node-postgres#1747]
Good afternoon, today I was working with node-postgres when, by using a parameterized query, which is very similar to various examples, we got this error: 

```
{ error: Incorrect number of parameters for prepared statement 
    at Connection.parseE (/home/ssh_user_clr/bitbucket/server/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/home/ssh_user_clr/bitbucket/server/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/home/ssh_user_clr/bitbucket/server/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  name: 'error',
  length: 172,
  severity: 'ERROR',
  code: '26000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: '/scratch_a/release/svrtar2886/vbuild/vertica/Session/ClientSession.cpp',
  line: '2830',
  routine: 'exec_bind_message' }
```

This is the code used:
```
const { Pool, Client } = require('pg')
const connectionString = '******'

const client = new Client({
  connectionString: connectionString,
})
client.connect()

client.query('SELECT * FROM CRM.USER WHERE EMAIL = $1;', ["email@xxx.com"], (err, res) => {
  console.log(err)
  console.log(res)
  client.end()
})
```

we also tried to write the same code in other formats, but nothing happens.
Using the same query without parameters do not throw any error and it works fine.

As a dbms we are using Vertica. Our machine runs on GNU/Linux, x86_64 with Node 8.12

**Comment by sehrope** [comment]
I wasn't able to reproduce this with a PostgreSQL backend. It may be something Vertica specific.

The only thing that stands out in the sample code is the extra semicolon at the end of the SQL command. It doesn't make a difference in PostgreSQL (it's still just one command so it doesn't complain about using parameters) but perhaps Vertica is more picky. Try removing it to see if that fixes things. Otherwise see if you can recreate the problem with a PostgreSQL backend.

**Comment by Gargarensis** [comment]
Using PostgresSQL works fine.
If supporting Vertica or a workaround for this is not a planned feature, I guess you can close the issue.
