### ISSUE TITLE
Cannot works well in version 9.6.6

### ISSUE THREAD

**Issue by kekeqy** [brianc/node-postgres#1754]
version of Node:8.11.2
version of Postgres:9.6.6
It can make connections and can execute non-table query,but cannot query tables,it prompt table does not exit.
sample1:'SELECT NOW() AS "theTime"',works well
sample2:'select * from t_device',error

  error: 关系 "t_device" 不存在
      at Connection.parseE (C:\Users\yh\Desktop\tsweb\node_modules\pg\lib\connection.js:554:11)
      at Connection.parseMessage (C:\Users\yh\Desktop\tsweb\node_modules\pg\lib\connection.js:379:19)
      at Socket.<anonymous> (C:\Users\yh\Desktop\tsweb\node_modules\pg\lib\connection.js:119:22)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:597:20)

**Comment by kekeqy** [comment]
I found that table names with the prefix "T_" are not ok.No prefixes are ok!!!What is this operation???

**Comment by kekeqy** [comment]
It turns out that it's not a prefix problem, but table names can't have uppercase letters.

扎心了，老铁！！！

**Comment by kekeqy** [comment]
You should fix this bug, I found that mysql and sqlite do not have this problem.

**Comment by kekeqy** [comment]
The table name in the database cannot be capitalized, and the table name in the code can be capitalized.
Interesting!!!

**Comment by kibertoad** [comment]
@kekeqy PostgreSQL has case-sensitive table names. MySQL has case-insensitive table names. This is by design and is not driver-specific.
