### ISSUE TITLE
Error: Connection terminated unexpectedly

### ISSUE THREAD

**Issue by lucca65** [brianc/node-postgres#1783]
Hi, I'm trying to use node-postgres in my productions servers and its giving me this error:

```
Error: Connection terminated unexpectedly
    at Connection.con.once (/home/backend/event-source/node_modules/pg/lib/client.js:200:9)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/home/backend/event-source/node_modules/pg/lib/connection.js:129:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

I'm trying to use this config:

```
const { Pool, Client } = require('pg')

const pool = new Pool({
  user: 'postgres',
  host: 'localhost',
  database: 'bespiral',
  password: '...', // omitted on this issue
  port: 5432,
})

pool.query('SELECT NOW()', (err, res) => {
  console.log(err, res)
  pool.end()
})

const client = new Client({
  user: 'postgres',
  host: 'localhost',
  database: 'bespiral',
  password: 'p0stgr3s',
  port: 5432,
})
client.connect()

client.query('SELECT NOW()', (err, res) => {
  console.log(err, res)
  client.end()
})
```

I've tried to use the native extension but I get another error:

```
$ npm i -g pg-native
$ node script.js

[Error: received invalid response to SSL negotiation: H
] undefined
(node:25841) UnhandledPromiseRejectionWarning: Error: received invalid response to SSL negotiation: H
```

I've also written a python equivalent, which works fine:

```python
#!/usr/bin/python
import psycopg2
import sys

def main():
	#Define our connection string
	conn_string = "host='localhost' dbname='bespiral' user='postgres' password='omitted'"

	# print the connection string we will use to connect
	print "Connecting to database\n	->%s" % (conn_string)

	# get a connection, if a connect cannot be made an exception will be raised here
	conn = psycopg2.connect(conn_string)

	# conn.cursor will return a cursor object, you can use this cursor to perform queries
	cursor = conn.cursor()
	print "Connected!\n"

if __name__ == "__main__":
	main()
```

I'm running `psql (PostgreSQL) 10.6 (Ubuntu 10.6-0ubuntu0.18.04.1)` on a Linode's ubuntu.

```
$ uname -a
Linux bespiraldev 4.18.16-x86_64-linode118 #1 SMP PREEMPT Mon Oct 29 15:38:25 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lucca65** [comment]
got a ghost process holding port 5432, damn. Nevermind
