### ISSUE TITLE
client.end() or pool.end() will produce UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by pkit** [brianc/node-postgres#1833]
```
(node:32461) UnhandledPromiseRejectionWarning: Error: Connection terminated
    at Connection.con.once (..../node_modules/pg/lib/client.js:199:9)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:187:15)
    at Socket.<anonymous> (..../node_modules/pg/lib/connection.js:76:10)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12)
```
The code:
```
            let client;
            try {
                client = await pool.connect();
                await client.query('begin');
                await client.query(`.............`);
                client.query('commit');
            } catch (e) {
                client.query('rollback');
                logger.err(e.stack);
            } finally {
                if (client)
                    client.release();
                pool.end();
            }
```
Removing the `finally` block solves the problem.
Same thing happens if `Client` is used directly: `client.end()` will fail in the exact same place.
Obviously I can see on empty test postgres instance that runs in docker that `begin; ....; commit;` is actually executed and no errors.

**Comment by charmander** [comment]
You forgot to `await` the commit and rollback queries.
