### ISSUE TITLE
Query parameters handling causes syntax error

### ISSUE THREAD

**Issue by radio-miskovice** [brianc/node-postgres#1874]
When I do the following query, everything completes fine in psql:
```
-- psql
INSERT INTO public.contest (contest_id, period_id, start_ts, end_ts, contest_name, default_format, status ) 
VALUES ('VKVPA', '2019/01', timestamp '2019-01-20 08:00', 
timestamp '2019-01-20 11:00', 'description', 'EDI', 'NEW' ) RETURNING contest_key;

-- console output:
contest_key |
------------+
         17 |

```
(```start_ts``` and ```end_ts``` have type ```TIMESTAMP WITHOUT TIME ZONE```)
When I do the same in a program using **pg** module, it ends with syntax error:
```
// contest-debug.ts
import { Pool } from 'pg' ;
let pool = new Pool( {user: 'contest_owner', database: 'contest'} );
pool.query(
    "INSERT INTO public.contest (contest_id, period_id, start_ts, end_ts, contest_name, default_format, status ) "
    + "VALUES ($1, $2, timestamp $3, timestamp $4, $5, $6, 'NEW' ) RETURNING contest_key", 
    ['VKVPA', '2019/02',  '2019-02-17 08:00', '2019-02-17 11:00', 'VKV Provozni aktiv 2019/02', 'EDI']
  )
  .then( result => { 
      console.log(`New contest has number ${result.rows[0].contest_key}`);
    })
  .catch( reason => { console.log( 'Contest creation failed:', reason )});

```
Console output:
```
Contest creation failed: { error: syntax error at or near "$3"
    at Connection.parseE (D:\dev\cav\log2any\node_modules\pg\lib\connection.js:601:11)
    at Connection.parseMessage (D:\dev\cav\log2any\node_modules\pg\lib\connection.js:398:19)
    at Socket.<anonymous> (D:\dev\cav\log2any\node_modules\pg\lib\connection.js:120:22)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:150:17)
  name: 'error',
  length: 92,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '135',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1134',
  routine: 'scanner_yyerror' }
```
The following code works. I did not pass the timestamp strings as parameters
and instead included them directly in the text of the query. Apparently, this is a bug either in libpq or in the javascript module. For some strange reason a string parameter is not handled as string if it is preceded by `timestamp` keyword in the query,

```
pool.query(
    "INSERT INTO public.contest (contest_id, period_id, start_ts, end_ts, contest_name, default_format, status ) "
    + "VALUES ($1, $2, timestamp '2019-02-17 08:00', timestamp '2019-02-17 11:00', $3, $4, 'NEW' ) RETURNING contest_key", 
    ['VKVPA', '2019/02',  'VKV Provozni aktiv 2019/02', 'EDI']
  )
...
```

**Comment by radio-miskovice** [comment]
Thanks, I will try. BTW, there is a specific reason why I use TIMESTAMP and not TIMESTAMPTZ. The data arrive in text file and they always mean UTC. If I used javascript Date object (which otherwise works with **pg** without any problems), I would get wrong date and time depending on current locale in the system.

**Comment by charmander** [comment]
`$3::timestamp AT TIME ZONE 'UTC'`, then?
