### ISSUE TITLE
Unexpected Null Reference error in Connection. 

### ISSUE THREAD

**Issue by rclayton-the-terrible** [brianc/node-postgres#1881]
Hello, I'm getting a really strange error when I run a Node.js service that uses Knex with `pg`:

```
TypeError: Cannot read property 'name' of undefined
  at Socket.<anonymous> (<project>/node_modules/pg/lib/connection.js:122:27)
  at emitOne (events.js:116:13)
  at Socket.emit (events.js:211:7)
  at addChunk (_stream_readable.js:263:12)
  at readableAddChunk (_stream_readable.js:250:11)
  at Socket.Readable.push (_stream_readable.js:208:10)
  at TCP.onread (net.js:601:20)
```

I modified the code to see what the offending packet was.  I'm receiving a header value of `74` and `Connection.prototype.parseMessage` function's switch statement is falling through and not returning a message.

What's really strange about this problem is that I'm only seeing it when I run my Node.js process within PM2.  If I run it externally from the process manager, I don't receive this error.

**Comment by rclayton-the-terrible** [comment]
Sorry, I'm an idiot.  The issue was that my PM2 environment had an erroneous variable pointing to the wrong port.  I was, unfortunately, trying to use the PG protocol to communicate to MySQL.
