### ISSUE TITLE
Still getting same error Connection terminated

### ISSUE THREAD

**Issue by oksanakyslenko** [brianc/node-postgres#1902]
I getting this error.

Error: Connection terminated
    at Connection.con.once (G:\2.Semester\ProjectVersionen\29.05.19\books\\node_modules\pg\lib\client.js:234:9)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Connection.emit (events.js:208:7)
    at Socket.<anonymous> (G:\2.Semester\ProjectVersionen\29.05.19\books\\node_modules\pg\lib\connection.js:77:10)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:557:12)
G:\2.Semester\ProjectVersionen\29.05.19\books\\app.js:84
        var resultLength = dbResponse.rows.length;
                                      ^

TypeError: Cannot read property 'rows' of undefined
    at Query.callback (G:\2.Semester\ProjectVersionen\29.05.19\books\\app.js:84:39)
    at Query.handleError (G:\2.Semester\ProjectVersionen\29.05.19\books\\node_modules\pg\lib\query.js:142:17)
    at process.nextTick (G:\2.Semester\ProjectVersionen\29.05.19\books\\node_modules\pg\lib\client.js:63:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

app.get("/books2", function(req,res) {
    res.render("books2");
});
app.post("/books2", urlencodedParser, function(req,res) {
    var search = req.body.search;
    //console.log(search)
    dbClient.query("SELECT * FROM books WHERE name LIKE '%$1%'",  [search], function(dbError, dbResponse) {
       console.log(dbError);
        var resultLength = dbResponse.rows.length;
        for(var i=0; i<resultLength; i++) {
            console.log(dbResponse);
        }   
            res.render("books2");
    });
    dbClient.end();
});

**Comment by charmander** [comment]
If you want to keep using the same client for every request, don’t close it after the first one (`dbClient.end()`).
