### ISSUE TITLE
Serializable transactions affecting separate rows throw unhandled promise rejection

### ISSUE THREAD

**Issue by schuma7** [brianc/node-postgres#1934]
I’m trying to run two transactions with serializable isolation level concurrently using the following code snippet:

```
const { Pool } = require('pg')
const pool = new Pool()

const sleep = (timeoutMs: number): Promise<void> =>
  new Promise((resolve) => setTimeout(resolve, timeoutMs));

const tx = async (callback) => {
  const client = await pool.connect()
  try {
    await client.query('BEGIN')
    try {
      await callback(client)
      client.query('COMMIT')
      console.log('SUCCESS');
    } catch(e) {
      client.query('ROLLBACK')
      console.error('ERROR', e);
    }
  } finally {
    client.release()
  }
}

async function run() {
  const tx1 = tx(async (client) => {
    await client.query("set transaction isolation level serializable;");
    await client.query("update test set value = 'change 1' where id = 2;");
    await sleep(3000);
  });

  const tx2 = tx(async (client) => {
    await client.query("set transaction isolation level serializable;");
    await client.query("update test set value = 'change 2' where id = 3;");
    await sleep(3000);
  });

  await Promise.all([tx1, tx2]);
}

run();
```

As you can see I’m trying to update two separate rows on the same table. In my test scenario this table just has 3 rows. Executing this snippet on the “postgres:11.2” docker image yields the following output:

```
SUCCESS
SUCCESS
(node:42220) UnhandledPromiseRejectionWarning: error: could not serialize access due to read/write dependencies among transactions
    at Connection.parseE (/Users/user/pg-test/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/Users/user/pg-test/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/Users/user/pg-test/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
(node:42220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

As you can see it logs two SUCCESS messages instead of one SUCCESS for the first one and one ERROR for the second failed transaction. Instead it throws an unhandled promise rejection.

Please note that when trying to update the same row by using the same id in both update queries, the library correctly throws an error:

```
SUCCESS
ERROR { error: could not serialize access due to concurrent update
    at Connection.parseE (/Users/user/pg-test/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/Users/user/pg-test/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/Users/user/pg-test/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
```

I’m using the following versions:
node: 10.5.0
node-postgres: 7.11.0
Postgres: 11.2

**Comment by sehrope** [comment]
You need to `await` the COMMIT and ROLLBACK. The COMMIT in particular could fail at commit time due to serialization issues. 

Also, you should consider using `client.release(err)` for the error situation as if the connection is broken (ex: backend terminated), you don't want to return it from the pool. Generally if the ROLLBACK succeeds, the connection is fine to reuse. If it fails, then discard it.
