### ISSUE TITLE
How would you identify trigger errors?

### ISSUE THREAD

**Issue by SulaimanAlabbar** [brianc/node-postgres#1961]
This is my trigger:

```sql
CREATE OR REPLACE FUNCTION abc_trigger()
RETURNS TRIGGER AS $BODY$
BEGIN
  IF (NEW.first_name = 'abc')
    THEN RAISE EXCEPTION 'bad' using hint = 'make it good';
  END IF;
RETURN NEW;
END;
$BODY$ LANGUAGE plpgsql;
​
CREATE TRIGGER abc
BEFORE INSERT ON users
FOR EACH ROW EXECUTE PROCEDURE abc_trigger();
```
This is an error:
```js
error: bad
    at Connection.parseE (/home/sulaiman/Desktop/api test/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/home/sulaiman/Desktop/api test/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/home/sulaiman/Desktop/api test/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
  name: 'error',
  length: 140,
  severity: 'ERROR',
  code: 'P0001',
  detail: undefined,
  hint: 'make it good',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'PL/pgSQL function abc_trigger() line 4 at RAISE',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'pl_exec.c',
  line: '3337',
  routine: 'exec_stmt_raise'
}
```
As far as I can tell, if an error was due to this trigger, I could only figure that out by checking against error.message or error.hint, which I could set to be what I want them to be. 
I'm not comfortable identifying errors by their messages. If it had been a constraint violation, I could have named my constraints and checked error.constraint. What can I do here if I want to handle this error?

**Comment by vitaly-t** [comment]
> How would you identify trigger errors

By the code - `code: 'P0001'`, i.e. `P0001` is your code for the custom-raised exceptions.
