### ISSUE TITLE
UnhandledPromiseRejectionWarning: error: value "-1001473594688" is out of range for type integer

### ISSUE THREAD

**Issue by straps** [brianc/node-postgres#1963]
I see the following error on my node app

```
(node:28950) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:28950) UnhandledPromiseRejectionWarning: error: value "-1001473594688" is out of range for type integer
    at Connection.parseE (/home/strx/www/personal/telegram-bot/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/home/strx/www/personal/telegram-bot/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/home/strx/www/personal/telegram-bot/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

I don't think it is something related to my code, backtrace doesn't show it at least...

Can you help me solve? Thanks

**Comment by straps** [comment]
It was my fault, sorry
