### ISSUE TITLE
Error using numeric bind variables "function testbind(text) does not exist"

### ISSUE THREAD

**Issue by mrTrunk** [brianc/node-postgres#1965]
I'm trying to execute simple query with bind vvariables, and got error:
error: function testbind(text) does not exist
    at Connection.parseE (backend\node_modules\pg\lib\connection.js:602:11)
    at Connection.parseMessage (backend\node_modules\pg\lib\connection.js:399:19)
    at Socket.<anonymous> (backend\node_modules\pg\lib\connection.js:121:22)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:154:17)

looks like all bind variables sended as strings....

Query:
import { Client } from "pg";

const client = new Client({
    user: 'postgres',
    host: '10.10.10.110',
    database: 'dkptest',
    password: 'dkppg',
    port: 5472,
  })
  client.connect()

const query = {
    // give the query a unique name
    text: `select testBind(t.n)
    from (select $1 n from dual) t`,
    values: [1]
  }
  // callback
  client.query(query, (err, res) => {
    if (err) {
      console.log(err.stack)
    } else {
      console.log(res.rows[0])
    }
  })
  

SQL Function:
CREATE OR REPLACE FUNCTION public.testbind(num in numeric)
	RETURNS varchar
	LANGUAGE plpgsql
AS $$
	BEGIN
 	  return to_char(num);
	END;
$$
;

**Comment by mrTrunk** [comment]
i can provide types for the query like:
```
const query = {
    text: `select testBind(t.n)
    from (select $1 n from dual) t`,
    values: [4],
    types: [PG_TYPE_NUMERIC]
  }
```
and select work fine.... but.....
in this case, library failed on 
TypeError: (this._types || types).getTypeParser is not a function
    at Result.addFields (c:\Work\web-backend\node_modules\pg\lib\result.js:98:41)

```var parser = (this._types || types).getTypeParser(desc.dataTypeID, desc.format || 'text')```
cause _types is array.....
