### ISSUE TITLE
How to establish a connection to a database that exists?

### ISSUE THREAD

**Issue by krfong916** [brianc/node-postgres#1999]
**Summary**
I am trying to connect to my postgresql server using the Client API, but I am unable to establish a client connection. I receive the following error:
```
error: database "mydb" does not exist
    at Connection.parseE (/Users/kyle/Desktop/DreamsVisualized/CSProjects/__/server/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/Users/kyle/Desktop/DreamsVisualized/CSProjects/__/server/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/Users/kyle/Desktop/DreamsVisualized/CSProjects/__/server/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
```
I run a simple script to test the establishment of a TCP/IP connection to the desired database:
`node postgresDBReportsImplementation.js `
```javascript
// file: reportsPostgresImpl.js
const postgres = require('../../postgresDB').postgres;

let postgresReportsImplementation = {
  findById: function(reportId) {
    const query = {
      text: 'SELECT * FROM report WHERE id = $1',
      values: [reportId],
    };
    Promise.resolve(postgres.getPostgresClientConnection())
      .then(connect => console.log(connect))
      .catch(error => console.error(error.stack));
  }
}

// USAGE HERE
// USAGE HERE
postgresReportsImplementation.findById(1);
// USAGE HERE
// USAGE HERE

// file: postgresDB.js
// imports...
let postgresDB = {
 getPostgresClientConnection: function() {
    let serverConnection = new sshClient();
    let {port, host, username, privateKeyPath, passphrase} = env.local.ssh;
    let {dbHost, user, database, password} = env.local.db;
    let {
      srcAddress,
      srcPort,
      destinationAddress,
      destinationPort,
    } = env.local.postgresPortForwarding;

    const sshConfig = {
      port: port,
      host: host,
      username: username,
      privateKey: fs.readFileSync(privateKeyPath),
      passphrase: passphrase,
    };

    const portForwardSettings = {
      srcAddress: srcAddress,
      srcPort: srcPort,
      destinationAddress: destinationAddress,
      destinationPort: destinationPort,
    };

    return new Promise(function(resolve, reject) {
      serverConnection
        // listen for when we've made a successful authentication
        .on('ready', function() {
          // forwardOut() establishes a TCP connection
          // between a port that we'll make requests from and
          // the port that postgres is serving from
          serverConnection.forwardOut(
            portForwardSettings.srcAddress,
            portForwardSettings.srcPort,
            portForwardSettings.destinationAddress,
            portForwardSettings.destinationPort,
            function(error, duplexStream) {
              // establish a user connection to postgres server
              let connection = new Client({
                host: dbHost, // '127.0.0.1'
                user: username, // 'kyle'
                database: database, // 'testdb'
                password: password, // can't tell you
                port: 5432
              });
              connection.connect(function(err, connection) {
                if (err) return reject(err);
                else return resolve(connection);
              });
            },
          );
        })
        .connect(sshConfig); // ssh tunnel to remote server
    });
  },
};
```
**Background**
I create an ssh tunnel between my local computer and a remote server that hosts my postgresql db -> no problems there.
My issue is when I'd like to establish localhost connection to the database 'testdb' via port 5432.

SSHing into my remote server and accessing my database via command line I have no problem: `psql -U kyle testdb`

What gives?

**Comment by krfong916** [comment]
**additional info**
This is my pg_hba.conf file
```
# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
```

and my hosts file
```
# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data
#
127.0.1.1 project-db-server project-db-server
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

**Comment by charmander** [comment]
> ```
>                 host: dbHost, // '127.0.0.1'
> ```
>
> ```
>                 port: 5432
> ```

Is this right? What’s in `env.local.postgresPortForwarding`?

**Comment by krfong916** [comment]
Hi @charmander here's the contents of the file containing the env variable
```
const env = {
	local: {
		ssh: {
			port: 22,
			host: 'host_ip_address',
			username: 'kyle',
			privateKeyPath: '/Users/kyle/.ssh/prvt-key',
			passphrase: 'some_passphrase',
		},
		postgresPortForwarding: {
			srcAddress: '127.0.0.1',
			srcPort: 3307,
			destinationAddress: '127.0.0.1',
			destinationPort: 5432,
		},
		db: {
			dbHost: '127.0.0.1',
			user: 'kyle',
			database: 'mydb',
			password: 'some_password',
		},
	},
};

exports.env = env;
```

**Comment by charmander** [comment]
Is there another layer of forwarding involved? The destination, `127.0.0.1:5432`, is PostgreSQL on localhost… and you’re connecting directly to that anyway with pg, instead of using the equivalent but indirect `127.0.0.1:3307` (confusingly, the MySQL port).

Did you mean something like:

```
postgresPortForwarding: {
	srcAddress: '127.0.0.1',
	srcPort: 5433,
	destinationAddress: '127.0.1.1',
	destinationPort: 5432,
},
```

with

```js
let connection = new Client({
  host: dbHost, // '127.0.0.1'
  user: username, // 'kyle'
  database: database, // 'mydb'
  password: password, // can't tell you
  port: srcPort,
});
```

?

**Comment by krfong916** [comment]
No, there's no other forwarding. Sorry for throwing the port `3307`, it is confusing.
I'm able to connect using the `Client` API with the following `Client` configs
```javascript
let connection = new Client({
  host: 'localhost'
  user: 'kyle'
});

let connection = new Client({
  host: 'localhost',
  user: 'testuser',
  database: 'testuser'
});

let connectionString = "postgres://kyle:[password_here]@localhost:5432/postgres"
let connectionString = "postgres://kyle:[password_here]@localhost:5432/kyle"
let connection = new Client(connectionString);
```

Even though I'm able to connect to my db with those configs, I am unable to make queries to the database using the `Query` API
I receive an `Error: relation 'test' does not exist`

**Comment by charmander** [comment]
Your errors have stopped matching their descriptions and each other. Please show either:

- a psql command that does work and
- an equivalent pg script that doesn’t work, run from the same place as psql

or:

- a pg script that does work and
- an equivalent pg script that doesn’t work, using an SSH tunnel

**Comment by krfong916** [comment]
I have a question, where you ask for an equivalent pg script that doesn't work, what do you mean by 'run from the same place as psql'?

I've listed below what I think you mean, but please correct me if I've misunderstood you.
- psql commands that do work
1. `psql -U kyle microreports`
2. `psql -h 127.0.0.1 -d microreports`
3. `psql postgres://kyle:[password_here]@localhost:5432/microreports`

- an equivalent pg script that doesn't work, run from the same place as psql
2. 
```javascript
const env = require('./env/env').env;
const fs = require('fs');
const stringify = require('csv-stringify');
const {Client} = require('pg');
const sshClient = require('ssh2').Client;

let postgresDB = {
  query: function(connection, sql) {
    console.log(connection);
    return new Promise(function(resolve, reject) {
      connection.query(sql, function(error, data) {
        if (error) return reject(error);
        else return resolve(data);
      });
    });
  },
  getPostgresClientConnection: function() {
    let serverConnection = new sshClient();
    let {port, host, username, privateKeyPath, passphrase} = env.local.ssh;
    let {dbHost, user, database, password} = env.local.db;
    let {
      srcAddress,
      srcPort,
      destinationAddress,
      destinationPort,
    } = env.local.postgresPortForwarding;

    const sshConfig = {
      port: port,
      host: host,
      username: username,
      privateKey: fs.readFileSync(privateKeyPath),
      passphrase: passphrase,
    };

    const portForwardSettings = {
      srcAddress: srcAddress,
      srcPort: srcPort,
      destinationAddress: destinationAddress,
      destinationPort: destinationPort,
    };

    serverConnection
      // listen for when we've made a successful authentication
      .on('ready', function() {
        // forwardOut() establishes a TCP connection
        // between a port that we'll make requests from and
        // the port that postgres is serving from
        serverConnection.forwardOut(
          portForwardSettings.srcAddress,
          portForwardSettings.srcPort,
          portForwardSettings.destinationAddress,
          portForwardSettings.destinationPort,
          function(error, duplexStream) {
            // establish a user connection to server
            let connection = new Client({
              username: "kyle",
              host: "localhost",
              database: "microreports"
            });

            connection.connect(err => {
               if (err) console.error(err.stack);
             });
          },
        );
      })
      .connect(sshConfig); // ssh tunnel to remote server
  },
};
```
3. 
```javascript
const env = require('./env/env').env;
const fs = require('fs');
const stringify = require('csv-stringify');
const {Client} = require('pg');
const sshClient = require('ssh2').Client;

let postgresDB = {
  query: function(connection, sql) {
    console.log(connection);
    return new Promise(function(resolve, reject) {
      connection.query(sql, function(error, data) {
        if (error) return reject(error);
        else return resolve(data);
      });
    });
  },
  getPostgresClientConnection: function() {
    let serverConnection = new sshClient();
    let {port, host, username, privateKeyPath, passphrase} = env.local.ssh;
    let {dbHost, user, database, password} = env.local.db;
    let {
      srcAddress,
      srcPort,
      destinationAddress,
      destinationPort,
    } = env.local.postgresPortForwarding;

    const sshConfig = {
      port: port,
      host: host,
      username: username,
      privateKey: fs.readFileSync(privateKeyPath),
      passphrase: passphrase,
    };

    const portForwardSettings = {
      srcAddress: srcAddress,
      srcPort: srcPort,
      destinationAddress: destinationAddress,
      destinationPort: destinationPort,
    };

    serverConnection
      // listen for when we've made a successful authentication
      .on('ready', function() {
        // forwardOut() establishes a TCP connection
        // between a port that we'll make requests from and
        // the port that postgres is serving from
        serverConnection.forwardOut(
          portForwardSettings.srcAddress,
          portForwardSettings.srcPort,
          portForwardSettings.destinationAddress,
          portForwardSettings.destinationPort,
          function(error, duplexStream) {
            // establish a user connection to server
            let connectionString = "postgres://kyle:[password_here]@localhost:5432/microreports"
            let connection = new Client(connectionString);

            connection.connect(err => {
               if (err) console.error(err.stack);
             });
          },
        );
      })
      .connect(sshConfig); // ssh tunnel to remote server
  },
};
```

**Comment by charmander** [comment]
“run from the same place as psql” = on the same host, as the same user, in the same environment. Where you run `psql -U kyle testdb`, you should run `node minimal-script.js`, where minimal-script.js is exactly this:

```js
let {Client} = require('pg');

let connection = new Client({
  user: "kyle",
  database: "testdb",
});

connection.connect(console.log); 
```

No `// setup`. Notice that the option is `user`, not `username`.

If you can’t do that, adjust your `psql` command so it uses the same port forwarding. If a query is involved, show the `psql -c '(query)'`.

**Comment by krfong916** [comment]
Ah, I understand what you're saying now. I'll post the results tomorrow morning
Regardless of whether or not I get this bug sorted out, I want to say thank you for taking the time to help me @charmander

**Comment by krfong916** [comment]
Ok, I'm able to run a small script that allows me to connect to my postgres db on the same host. I think script allows us to safely assume my issue isn't with node-postgres itself, and instead, is with my postgresql configuration.

I do have a question, what would you surmise the problem may be then? This question is out of scope of the focus of this project, so I understand if it's not in your interests to answer.

**Comment by charmander** [comment]
I think the database “testdb” doesn’t exist on localhost:5432, and you have multiple PostgreSQL servers running that you’re getting mixed up because of (backwards?) port forwarding.

**Comment by krfong916** [comment]
Thank you for your advice and your help. I'm going to close this issue while I continue to debug. I'll open it back up if I find the root of my problem.

**Comment by krfong916** [comment]
Thank you for your advice and your help. I'm going to close this issue while I continue to debug. I'll open it back up if I find the root of my problem.
