### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE] when parsing result fields

### ISSUE THREAD

**Issue by ubnt-michals** [brianc/node-postgres#2053]
I am getting following error:

https://sentry.io/share/issue/dc40781d83fd437184bca7ee5cde56be/

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 1074. Received 2377
  File "internal/buffer.js", line 49, col 9, in boundsError
  File "internal/buffer.js", line 361, col 5, in Buffer.readInt32BE
  File "/home/app/unms/node_modules/pg/lib/connection.js", line 630, col 22, in Connection.parseInt32
    var value = buffer.readInt32BE(this.offset)
  File "/home/app/unms/node_modules/pg/lib/connection.js", line 535, col 21, in Connection._readValue
    var length = this.parseInt32(buffer)
  File "/home/app/unms/node_modules/pg/lib/connection.js", line 528, col 26, in Connection.parseD
    msg.fields.push(this._readValue(buffer))
  File "/home/app/unms/node_modules/pg/lib/connection.js", line 377, col 19, in Connection.parseMessage
    return this.parseD(buffer, length)
  File "/home/app/unms/node_modules/pg/lib/connection.js", line 120, col 22, in Socket.<anonymous>
    var msg = self.parseMessage(packet)
  File "events.js", line 189, col 13, in Socket.emit
  File "domain.js", line 441, col 20, in Socket.EventEmitter.emit
  File "_stream_readable.js", line 284, col 12, in addChunk
  File "_stream_readable.js", line 265, col 11, in readableAddChunk
  File "_stream_readable.js", line 220, col 10, in Socket.Readable.push
  File "internal/stream_base_commons.js", line 94, col 17, in TCP.onStreamRead [as onread]
```

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 542. Received -19
  File "internal/buffer.js", line 49, col 9, in boundsError
  File "internal/buffer.js", line 361, col 5, in Buffer.readInt32BE
  File "/home/app/unms/node_modules/pg/lib/connection.js", line 630, col 22, in Connection.parseInt32
    var value = buffer.readInt32BE(this.offset)
  File "/home/app/unms/node_modules/pg/lib/connection.js", line 535, col 21, in Connection._readValue
    var length = this.parseInt32(buffer)
  File "/home/app/unms/node_modules/pg/lib/connection.js", line 528, col 26, in Connection.parseD
    msg.fields.push(this._readValue(buffer))
  File "/home/app/unms/node_modules/pg/lib/connection.js", line 377, col 19, in Connection.parseMessage
    return this.parseD(buffer, length)
  File "/home/app/unms/node_modules/pg/lib/connection.js", line 120, col 22, in Socket.<anonymous>
    var msg = self.parseMessage(packet)
  File "events.js", line 189, col 13, in Socket.emit
  File "domain.js", line 441, col 20, in Socket.EventEmitter.emit
  File "_stream_readable.js", line 284, col 12, in addChunk
  File "_stream_readable.js", line 265, col 11, in readableAddChunk
  File "_stream_readable.js", line 220, col 10, in Socket.Readable.push
  File "internal/stream_base_commons.js", line 94, col 17, in TCP.onStreamRead [as onread]
```

- `pg` - 7.8.0
- `postgesql` - 9.6.12

I don't have failing server response yet, I am still trying to reproduce the issue.

**Comment by brianc** [comment]
that looks weird/bad - lemme know if you can get steps to reproduce!

**Comment by seantcanavan** [comment]
I'm getting this issue as well unfortunately with my data set trying to query multiple rows. If anyone has any idea what causes it that would be amazing.

**Comment by christhegrand** [comment]
We saw several crashes caused by this today:

```
ERROR 2025-04-11T20:01:38.854413215Z RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 5888. Received 5892
ERROR 2025-04-11T20:01:38.854418835Z at boundsError (node:internal/buffer:88:9)
ERROR 2025-04-11T20:01:38.854425665Z at Buffer.readInt32BE (node:internal/buffer:484:5)
ERROR 2025-04-11T20:01:38.854432025Z at BufferReader.int32 (/home/node/app/Backend/node_modules/pg-protocol/dist/buffer-reader.js:27:36)
ERROR 2025-04-11T20:01:38.854440505Z at Parser.parseField (/home/node/app/Backend/node_modules/pg-protocol/dist/parser.js:189:40)
ERROR 2025-04-11T20:01:38.854445825Z at Parser.parseRowDescriptionMessage (/home/node/app/Backend/node_modules/pg-protocol/dist/parser.js:181:38)
ERROR 2025-04-11T20:01:38.854451285Z at Parser.handlePacket (/home/node/app/Backend/node_modules/pg-protocol/dist/parser.js:126:29)
ERROR 2025-04-11T20:01:38.854456625Z at Parser.parse (/home/node/app/Backend/node_modules/pg-protocol/dist/parser.js:35:38)
ERROR 2025-04-11T20:01:38.854487275Z at Socket.<anonymous> (/home/node/app/Backend/node_modules/pg-protocol/dist/index.js:11:42)
ERROR 2025-04-11T20:01:38.854491105Z at Socket.emit (node:events:524:28)
ERROR 2025-04-11T20:01:38.854494515Z at addChunk (node:internal/streams/readable:561:12) {
ERROR 2025-04-11T20:01:38.854499035Z code: 'ERR_OUT_OF_RANGE'
ERROR 2025-04-11T20:01:38.854502065Z }
```

As far as I can tell the query itself wasn't logged anywhere.

**Comment by christhegrand** [comment]
This happened to us again today:

```
ERROR 2026-02-06T20:35:51.046119309Z RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 49148. Received -16637394
ERROR 2026-02-06T20:35:51.046123235Z at boundsError (node:internal/buffer:88:9)
ERROR 2026-02-06T20:35:51.046127337Z at Buffer.readInt32BE (node:internal/buffer:484:5)
ERROR 2026-02-06T20:35:51.046139808Z at BufferReader.int32 (/home/node/app/Backend/node_modules/pg/node_modules/pg-protocol/dist/buffer-reader.js:27:36)
ERROR 2026-02-06T20:35:51.046149329Z at parseDataRowMessage (/home/node/app/Backend/node_modules/pg/node_modules/pg-protocol/dist/parser.js:231:28)
ERROR 2026-02-06T20:35:51.046153429Z at Parser.handlePacket (/home/node/app/Backend/node_modules/pg/node_modules/pg-protocol/dist/parser.js:122:27)
ERROR 2026-02-06T20:35:51.046157461Z at Parser.parse (/home/node/app/Backend/node_modules/pg/node_modules/pg-protocol/dist/parser.js:37:38)
ERROR 2026-02-06T20:35:51.046161097Z at Socket.<anonymous> (/home/node/app/Backend/node_modules/pg/node_modules/pg-protocol/dist/index.js:11:42)
ERROR 2026-02-06T20:35:51.046164756Z at Socket.emit (node:events:524:28)
ERROR 2026-02-06T20:35:51.046168925Z at addChunk (node:internal/streams/readable:561:12)
ERROR 2026-02-06T20:35:51.046174812Z at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {
ERROR 2026-02-06T20:35:51.046179766Z code: 'ERR_OUT_OF_RANGE'
ERROR 2026-02-06T20:35:51.046183424Z }
```

**Comment by brianc** [comment]
> lemme know if you can get steps to reproduce!

I'm really sorry this is happening! I need steps to reproduce this or i can't fix it

**Comment by David-Owen-Walker** [comment]
We are seeing a similar issue:

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 110588. Received -45116
  at boundsError (node:internal/buffer:88:9)
  at Buffer.readInt32BE (node:internal/buffer:484:5)
  at BufferReader.int32 (/usr/src/app/node_modules/pg-protocol/dist/buffer-reader.js:27:36)
  at Parser.parseDataRowMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:213:37)
  at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:112:29)
  at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
  at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
  at Socket.emit (node:events:524:28)
  at Socket.emit (node:domain:489:12)
  at addChunk (node:internal/streams/readable:561:12)
```

`pg: 8.11.2`
`pg-protocol: 1.6.0`
`Postgres version 14.20`
Potentially relevant: this is running on k8s and the pods where the crash occurs are using [linkerd2](https://github.com/linkerd/linkerd2).

No specific query appears to consistently trigger the crash. **As soon as I have a means of reproducing the error, I will share it.** What I can currently share is that the bounds & offset are not totally random. We saw the following values repeated across 341 errors:
| LB | UB | Offset |
|---|---|---|
| 0 | 55292 | 1659730758 |
| 0 | 110588 | 1701095183 |
| 0 | 131068 | 892714509 |
| 0 | 442364 | -45116 |
| 0 | 221180 | -45116 |
| 0 | 110588 | -45116 |
| 0 | 131068 | 1865412113 |
| 0 | 262140 | 713311195 |
| 0 | 131068 | 713311195 |
| 0 | 65532 | 713311195 |
| 0 | 8388604 | 879158575 |
| 0 | 4194300 | 879158575 |
| 0 | 2097148 | 879158575 |
| 0 | 1048572 | 879158575 |
| 0 | 524284 | 879158575 |
| 0 | 262140 | 879158575 |
| 0 | 131068 | 879158575 |
| 0 | 16777212 | 875679983 |
| 0 | 8388604 | 875679983 |
| 0 | 4194300 | 875679983 |
| 0 | 2097148 | 875679983 |
| 0 | 1048572 | 875679983 |
| 0 | 524284 | 875679983 |
| 0 | 262140 | 875679983 |
| 0 | 131068 | 875679983 |
| 0 | 2097148 | 8424163 |
| 0 | 1048572 | 8424163 |
| 0 | 524284 | 8424163 |
| 0 | 262140 | 8424163 |
| 0 | 131068 | 8424163 |
| 0 | 131068 | 962947807 |
| 0 | 131068 | -11901508 |
| 0 | 524284 | 1667340819 |
| 0 | 262140 | 1667340819 |
| 0 | 131068 | 1667340819 |
| 0 | 131068 | 1107335958 |
| 0 | 524284 | -196114096 |
| 0 | 262140 | -196114096 |
| 0 | 131068 | -196114096 |
| 0 | 65532 | -196114096 |

**Comment by christhegrand** [comment]
We are also using Kubernetes, but not linkerd.

-- 
Thanks,
Chris

**Comment by David-Owen-Walker** [comment]
@christhegrand Thanks! We've also observed that the issue only happens on pods which are running on a particular node. At this point we haven't identified anything unique about the node. Does that match what you see?

**Comment by christhegrand** [comment]
I'm not sure, but I can check through our logs later today to find the last time this occurred and see if all the errors came from the same node.
