### ISSUE TITLE
Received protocol request 'E' for portal while in PortalSuspended state for portal

### ISSUE THREAD

**Issue by RoAsHrOaSh** [brianc/node-postgres#2055]
I'm trying to run a query from node.js and I'm getting the following error:
Received protocol request 'E' for portal '' while in PortalSuspended state for portal '<unnamed portal 14>'.

call stack:
error: Received protocol request 'E' for portal '' while in PortalSuspended state for portal '<unnamed portal 14>'.
at Connection.parseE (C:\ws\IGServer\node_modules\pg\lib\connection.js:604:13)
at Connection.parseMessage (C:\ws\IGServer\node_modules\pg\lib\connection.js:403:19)
at Socket. (C:\ws\IGServer\node_modules\pg\lib\connection.js:123:22)
at Socket.emit (events.js:189:13)
at Socket.EventEmitter.emit (domain.js:441:20)
at addChunk (_stream_readable.js:284:12)
at readableAddChunk (_stream_readable.js:265:11)
at Socket.Readable.push (_stream_readable.js:220:10)
at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

important to say that I don't use the pg lib directly, only through pg-promise.
also, when I run the query on Workbench I get results and everything seems to be fine.
I tried to revert my Redshift version on AWS, but it didn't seem to solve this issue.

Will appreciate any help with it.

**Comment by vitaly-t** [comment]
If the author actually tested it against pg-promise versions `7.5.2` and `10.4.0-beta.1`, it translates into pg versions `~7.4.1` and `7.17.0` accordingly.

**Comment by brianc** [comment]
Can you submit steps to reproduce?

**Comment by RoAsHrOaSh** [comment]
Hi @brianc ,

I couldn't create a simple example to reproduce the problem, but after a long investigation it seems to happen when we use both pg-query-stream together with pg-promise.
it seems that this error happens when we try to insert records using pg-promise and reading data from the table using pg-query-stream in parallel.

I hope that helps.

**Comment by charmander** [comment]
> it seems that this error happens when we try to insert records using pg-promise and reading data from the table using pg-query-stream in parallel.

Not using the same client, right?

**Comment by RoAsHrOaSh** [comment]
@charmander right, different clients. any idea for a temporary workaround?

**Comment by brianc** [comment]
@RoAsHrOaSh without a self-contained script to reproduce its gonna be pretty hard to track down.  If you can't reproduce this issue w/ using nothing but the modules in this repo then it's not likely something I'll have the time to look at....meaning if it's related to pg-promise you should narrow that down & open an issue on that repo.  Thanks!

**Comment by bi-kro** [comment]
I have the same issue, created a ticket to AWS but they said they don't support PG node.js driver.

**Comment by brianc** [comment]
> they said they don't support PG node.js driver.

Yeah... I support the PG node.js driver.  But without any steps to reproduce I'm not going to be able to support this issue.  Please let me know when you have a self-contained script to reproduce this, without using `pg-promise`...just the `pg` libraries directly.  Once you have that, it shouldn't be a problem for me to fix it.

**Comment by pietersv** [comment]
I also occasionally get this error `error: Received protocol request 'E' for portal '' while in PortalSuspended state for portal '<unnamed portal 14>'` when using node-postgres.  

I think the error is generated from within Postgres, not the fault of the driver.   The error message refers to `code: '0801', file: `'../src/pg/src/backend/libpq/pqcomm.c'`, line: '2796'`.    The C language file [pqcomm.c ](https://github.com/postgres/postgres/blob/master/src/backend/libpq/pqcomm.c)and the [error code](https://github.com/postgres/postgres/blob/47b7051bc82f11f19df43544045c93549783e962/src/backend/utils/errcodes.txt#L111) definition are part of the Postgres database, not this repo.  

```
Trace
    at onError (/Users/pieter/Exp/globalstrategy/convert.js:25:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

error: Received protocol request 'E' for portal '' while in PortalSuspended state for portal '<unnamed portal 14>'.
    at Parser.parseErrorMessage (/Users/pieter/Exp/globalstrategy/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/pieter/Exp/globalstrategy/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/pieter/Exp/globalstrategy/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/Users/pieter/Exp/globalstrategy/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
    at SocksConnection.ondata (node:internal/js_stream_socket:77:22) {
  length: 215,
  severity: 'ERROR',
  code: '08P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: '../src/pg/src/backend/libpq/pqcomm.c',
  line: '2796',
  routine: 'errorPortalSuspendedInvalidRequestPortal'
}

Node.js v18.12.1

```
