### ISSUE TITLE
Cursor closed twice when used in async iterable

### ISSUE THREAD

**Issue by matthieusieben** [brianc/node-postgres#2119]
Running the following code produces a race condition causing the pg-cursor to be closed twice:

```js
const { Pool } = require('pg')
const PgQueryStream = require('pg-query-stream')

const connectionString = "XXX"
const pool = new Pool({ connectionString })

async function* stream(query, values, { highWaterMark = 1 } = {}){
    const stream = new PgQueryStream(query, values, { highWaterMark })
    this.query(stream)
    return yield* stream
}

const main = async () => {
  const connection = await pool.connect()
  try {
    for await(const item of stream.call(connection, 'SELECT TRUE')) break
    for await(const item of stream.call(connection, 'SELECT TRUE')) break
    for await(const item of stream.call(connection, 'SELECT TRUE')) break
    for await(const item of stream.call(connection, 'SELECT TRUE')) break
    for await(const item of stream.call(connection, 'SELECT TRUE')) break
    for await(const item of stream.call(connection, 'SELECT TRUE')) break
    for await(const item of stream.call(connection, 'SELECT TRUE')) break
  } finally {
    await connection.release()
  }
}

main()

```

Running this code (multiple times) with a fast connection (local pg server) results in the following error:

```
~/node_modules/pg/lib/client.js:337
    if (self.activeQuery.name) {
                         ^

TypeError: Cannot read property 'name' of null
    at Connection.<anonymous> (~/node_modules/pg/lib/client.js:337:26)
    at Connection.emit (events.js:321:20)
    at Socket.<anonymous> (~/node_modules/pg/lib/connection.js:134:12)
    at Socket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

This error is caused by the fact that the `_closePortal()` will get called twice.
1) first because NodeJs will try and `destroy()` the steam when the loop is `break`en. This will cause `close()` to be called.
2) because `handleCommandComplete()` will be triggered by the pg connection listener

**Comment by matthieusieben** [comment]
I am still having this issue with:
`node 13.13.0`
and
```
 npm list
/Users/msi/Desktop
├─┬ pg@8.0.3
│ ├── buffer-writer@2.0.0
│ ├── packet-reader@1.0.0
│ ├── pg-connection-string@0.1.3
│ ├── pg-pool@3.1.1
│ ├── pg-protocol@1.2.2
│ ├─┬ pg-types@2.2.0
│ │ ├── pg-int8@1.0.1
│ │ ├── postgres-array@2.0.0
│ │ ├── postgres-bytea@1.0.0
│ │ ├── postgres-date@1.0.5
│ │ └─┬ postgres-interval@1.2.0
│ │   └── xtend@4.0.2
│ ├─┬ pgpass@1.0.2
│ │ └─┬ split@1.0.1
│ │   └── through@2.3.8
│ └── semver@4.3.2
└─┬ pg-query-stream@3.0.7
  └── pg-cursor@2.1.10
```

**Comment by matthieusieben** [comment]
Note, my exact setup is as follows:
MacOS host (10.15.4)
- Running a postgres:11 database through docker (dinghy + xhyve VM)
- Running the JS above from the MacOS host

**Comment by matthieusieben** [comment]
This error is still an issue for me. I am using Postgres `13.3`, NodeJS `v16.6.1` and the latest `pg-*` (as of today).

<img width="842" alt="Capture d’écran 2021-09-07 à 22 14 01" src="https://user-images.githubusercontent.com/813661/132405169-d09c7c6a-d74b-4bec-9bf4-66f25d64be82.png">

**Comment by matthieusieben** [comment]
Using the following code, the error occurs every time on my machine:
```js
const Pool = require('pg-pool')
const PgQueryStream = require('pg-query-stream')

const main = async () => {
  const pool = new Pool({ connectionString: "postgres://localhost/postgres" })
  const connection = await pool.connect()
  try {
    for await(const item of connection.query(new PgQueryStream('SELECT TRUE', [], { highWaterMark: 1 }))) break
    for await(const item of connection.query(new PgQueryStream('SELECT TRUE', [], { highWaterMark: 1 }))) break
  } finally {
    await connection.release()
    await pool.end()
  }
}

main()
```

```
/Users/msi/Desktop/test/node_modules/pg/lib/client.js:367
    if (this.activeQuery.name) {
                         ^

TypeError: Cannot read property 'name' of null
    at Client._handleParseComplete (/Users/msi/Desktop/test/node_modules/pg/lib/client.js:367:26)
    at Connection.emit (node:events:394:28)
    at /Users/msi/Desktop/test/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/Users/msi/Desktop/test/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/Users/msi/Desktop/test/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by matthieusieben** [comment]
Note: I currently use the following monkey patch as workaround:
```js
const Cursor = require('pg-cursor')

// @hack: https://github.com/brianc/node-postgres/issues/2119
const orig = Cursor.prototype._closePortal
Cursor.prototype._closePortal = function (...args: any[]) {
  if (this.state !== 'done') orig.apply(this, ...args)
}
```
