### ISSUE TITLE
Problems creating a bot for discord

### ISSUE THREAD

**Issue by FalloutDiscord** [brianc/node-postgres#2152]
I make my bot for discord, I use Visual Studio Code, I made him start commands. I launch the bot using node bot.js and throws an error.

(node:1104) UnhandledPromiseRejectionWarning: ReferenceError: client is not defined
    at Client.<anonymous> (C:\Users\user\Documents\Bot\bot.js:23:22)  
    at Client.emit (events.js:311:20)
    at WebSocketManager.triggerClientReady (C:\Users\user\Documents\Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:433:17)
    at WebSocketManager.checkShardsReady (C:\Users\user\Documents\Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:417:10)
    at WebSocketShard.<anonymous> (C:\Users\user\Documents\Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:199:14)
    at WebSocketShard.emit (events.js:311:20)
    at WebSocketShard.checkReady (C:\Users\user\Documents\Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:466:12)
    at WebSocketShard.onPacket (C:\Users\user\Documents\Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:438:16)
    at WebSocketShard.onMessage (C:\Users\user\Documents\Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\user\Documents\Bot\node_modules\ws\lib\event-target.js:120:16)
(node:1104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

After issuing this error, the terminal simply freezes, nothing happens, I can’t write, I just open the terminal on a new one.
I made no mistakes anywhere, everything is clean and tidy.

**Comment by charmander** [comment]
That doesn’t look related to PostgreSQL.
