### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by ugate** [brianc/node-postgres#2168]
It looks like there are occasions where connection packet messages are unable to be extracted which results in convoluted error messages.

One example is when an _invalid/used_ `port` is set on a connection pool configuration that points to the wrong database vendor. For example, we had inadvertently used the MySQL server port on a server which resulted int the following error. It doesn't seem likely that this particular issue would arise much, but it does pose the question if there should be some additional validation in place for `pg` connections?

```js
const { Pool } = require('pg');
const pool = new Pool({
  host: 'localhost',
  user: 'postgres-user',
  port: 3306
});
...
```

![image](https://user-images.githubusercontent.com/944948/79614500-89597a80-80b5-11ea-8ac4-5f179be1319c.png)

```
./node_modules/pg/lib/connection.js:116 Uncaught TypeError: Cannot read property 'name' of undefined
    at Socket.<anonymous> (.\node_modules\pg\lib\connection.js:116:27)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by vitaly-t** [comment]
And [this issue](https://stackoverflow.com/questions/61323787/pg-promise-cancel-a-query-initiated-with-pg-query-stream) appears to be related.

Apparently, the following call is possible when `self.activeQuery` is null, so it throws an error:

https://github.com/brianc/node-postgres/blob/2ef55503738eb2cbb6326744381a92c0bc0439ab/packages/pg/lib/client.js#L357
