### ISSUE TITLE
pg-query-stream error event not emitted in 3.x when postgres server killed. Works in 2.x

### ISSUE THREAD

**Issue by markddrake** [brianc/node-postgres#2187]
Apologies in advance if this is an expected change of behavior or a total misunderstanding of how things are meant to work...

Given the following code
```
const {Client,Pool} = require('pg')
const  QueryStream = require('pg-query-stream')
const Transform = require('stream').Transform;

class MyTransform extends Transform {

  constructor() {
    super({objectMode: true });  
	this.counter = 0;
  }
  
  async _transform (data,encodoing,done) {
	this.counter++
	if ((this.counter % 10000) === 0 ){
      this.push('.')
	}
    done();
  }
}
  
async function main() {

 const pool = new Pool({
   user: 'postgres',
   host: 'yadamu-db2',
   database: 'yadamu',
    password: 'oracle',
    port: 5432
  })
  
 const connection  = await pool.connect()
 connection.on('error',
	  function(err, p) {
        // yadamuLogger.info([`${databaseVendor}`,`Connection.onError()`],err.message);
   	    // Do not throw errors here.. Node will terminate immediately
   	    // const pgErr = new PostgresError(err,self.postgresStack,self.postgressOperation)  
        // throw pgErr
      }
	)

 console.log('Connected')
 const queytStream = new QueryStream(`select jsonb_build_array("PROD_ID","CUST_ID","TIME_ID"::timestamptz,"CHANNEL_ID","PROMO_ID","QUANTITY_SOLD","AMOUNT_SOLD") "json" from "SH"."SALES"`)
 const resultStream = await connection.query(queytStream)
 const t = new MyTransform()

 console.log('Creating Promise')
 const copy = new Promise(async function foo(resolve,reject) {   
   resultStream.on('error',function(e) {console.log(`Error emitted after ${t.counter} rows.`),reject(e)})
   resultStream.on('end',function() { resolve('DONE')})
   try {
     resultStream.pipe(t).pipe(process.stdout);
   } catch(e) {
	 reject(e);
   }
 })
 
 console.log('Waiting for Pipe')
 await copy
 console.log('Pipe Complete');
 
}
main().then(function(r) { console.log(r)}).catch(function(e) {console.log(e)});
```
If I run the code with  Node 14.1 and 

+-- pg@8.0.3
+-- pg-copy-streams@2.2.2
+-- pg-query-stream@2.1.2
 
and kill the backend postgres process while the query is running  I get the following output
```
C:\Development\YADAMU-2020-04-15\app>node t1.js
Connected
Creating Promise
Waiting for Pipe
..............................................................Error emitted after 623500 rows.
Error: Connection terminated unexpectedly
    at Connection.<anonymous> (C:\Development\YADAMU-2020-04-15\app\node_modules\pg\lib\client.js:275:71)
    at Object.onceWrapper (events.js:421:28)
    at Connection.emit (events.js:315:20)
    at Socket.<anonymous> (C:\Development\YADAMU-2020-04-15\app\node_modules\pg\lib\connection.js:126:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

C:\Development\YADAMU-2020-04-15\app>
```
As can be seen the error event is emitted and my error handler is invoked.
However if I upgrade to pg_query_stream 3.x and run the same code I get the following 

```
C:\Development\YADAMU-2020-04-15\app>npm install pg-query-stream@3.0.7
+ pg-query-stream@3.0.7
updated 1 package and audited 830 packages in 2.294s

8 packages are looking for funding
  run `npm fund` for details

found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Development\YADAMU-2020-04-15\app>node t1.js
Connected
Creating Promise
Waiting for Pipe
..................................................
C:\Development\YADAMU-2020-04-15\app>
```

As can seen the 'error' event does not appear to be emitted when I kill the backend process. 

Was the 2.x behavior incorrect ?. If so, how should I be setting up the onError handler in 3.x

**Comment by markddrake** [comment]
It appears that with 2.x two connection errors are emitted, the first before the streams error event is emitted, and the second after the stream error event. With 3.x only the second of the connection errors is emitted.

**Comment by brianc** [comment]
Hey @markddrake sorry you're running into that issue.  Thanks for the report w/ the code example.  Do you happen to have a piece of code that can reproduce the entire thing w/o having to manually kill a backend process?  Its not really possible to turn these things into unit tests (and subsequently fix them) if the only way to get the issue to trigger is a manual step in the middle.

**Comment by markddrake** [comment]
Brian

I don't, wish that I did, since I have a similar issue with testing YADAMU (except x8 since I support 8 different databases). I am more of an Oracle and to a lesser extend MsSQL guy. 

I've been thinking along the lines of having a second pool and connection and trying to kill the process from that connection. Note sure if that approach could work with Postgres, in general issuing a graceful shutdown on a second connection results in a cleaner disconnection than killing a process. I tried with a docker stop but that seems to get translated into a graceful shutdown. The other thought is to have some kind of kill server running that you could send the kill process request too. I

**Comment by markddrake** [comment]
Ok, try this.. it's crude but I think it shows the problem

```
"use strict" 
const fs = require('fs');
const Readable = require('stream').Readable;
const { performance } = require('perf_hooks');

/* 
**
** Require Database Vendors API 
**
** ### pg_query-stream 3.x is not supported as it does not emit error events when the connection is lost: https://github.com/brianc/node-postgres/issues/2187
**
*/
const {Client,Pool} = require('pg')
const CopyFrom = require('pg-copy-streams').from;
const QueryStream = require('pg-query-stream')

const YadamuDBI = require('../../common/yadamuDBI.js');
const YadamuLibrary = require('../../../YADAMU/common/yadamuLibrary.js');
const {ConnectionError, PostgresError} = require('../../common/yadamuError.js')
const DBParser = require('./dbParser.js');
const TableWriter = require('./tableWriter.js');
const StatementGenerator = require('./statementGenerator.js');

const sqlGenerateQueries = `select EXPORT_JSON($1,$2)`;

const sqlSystemInformation = `select current_database() database_name,current_user,session_user,current_setting('server_version_num') database_version`;					   

const sqlCreateSavePoint = `SAVEPOINT YadamuInsert`;

const sqlRestoreSavePoint = `ROLLBACK TO SAVEPOINT YadamuInsert`;

const sqlReleaseSavePoint = `RELEASE SAVEPOINT YadamuInsert`;


class PostgresDBI extends YadamuDBI {
    
  /*
  **
  ** Local methods 
  **
  */
  
  async testConnection(connectionProperties) {   
    super.setConnectionProperties(connectionProperties);
	try {
      const pgClient = new Client(this.connectionProperties);
      await pgClient.connect();
      await pgClient.end();     
	} catch (e) {
      throw e;
	}
	
  }
  
  async createConnectionPool() {
	
	const yadamuLogger = this.yadamuLogger
    const databaseVendor = this.DATABASE_VENDORR

    this.logConnectionProperties();
	let sqlStartTime = performance.now();
	this.pool = new Pool(this.connectionProperties);
    this.traceTiming(sqlStartTime,performance.now())
	
	const self = this
    this.pool.on('error',(err, p) => {
	  // Do not throw errors here.. Node will terminate immediately
	  // const pgErr = new PostgresError(err,self.postgresStack,self.postgressOperation)
      // yadamuLogger.logException([`${databaseVendor}`,`Client.onError()`],pgErr);
      // throw pgErr
    })

  }
  
  async getConnectionFromPool() {

    if (this.status.sqlTrace) {
      this.status.sqlTrace.write(this.traceComment(`Gettting Connection From Pool.`));
    }
	
	let stack
	try {
      const sqlStartTime = performance.now();
	  stack = new Error().stack;
	  const connection = await this.pool.connect();
      this.traceTiming(sqlStartTime,performance.now())
      return connection
	} catch (e) {
	  throw new PostgresError(e,stack,'pg.Pool.connect()')
	}
  }

  async getConnection() {
	this.logConnectionProperties();
    const sqlStartTime = performance.now();
	
	let stack 
	let operation
	
	try {
	  operation = 'pg.Client()'
	  stack = new Error().stack;
      const pgClient = new Client(this.connectionProperties);
	
	  operation = 'Client.connect()'
	  stack = new Error().stack;
      this.connection = await pgClient.connect();
    
	  this.traceTiming(sqlStartTime,performance.now())
	} catch (e) {
      throw new PostgresException(e,stack,operation);
	}
    await configureConnection();
  }
  
  async closeConnection() {

  	// this.yadamuLogger.trace([this.DATABASE_VENDOR,this.slaveNumber === undefined ? 'Master' : this.slaveNumber],`closeConnection()`)
	  
    if (this.connection !== undefined && this.connection.release) {
	  let stack
      try {
     	stack = new Error().stack;
        await this.connection.release();
        this.connection = undefined;
      } catch (e) {
        this.connection = undefined;
		const err = new PostgresError(e,stack,'Client.release()');
		throw err
      }
	}
  };
  
  async closePool() {

	// this.yadamuLogger.trace([this.DATABASE_VENDOR],`closePool()`)

    if (this.pool !== undefined && this.pool.end) {
      let stack
	  try {
	    stack = new Error().stack
	    await this.pool.end();
        this.pool = undefined
  	  } catch (e) {
        this.pool = undefined
	    throw new PostgresError(e,stack,'pg.Pool.close()')
	  }
	}
  }
  
  async reconnectImpl() {
      
    // this.yadamuLogger.trace([`${this.constructor.name}.reconnectImpl()`],`Attemping reconnection.`);
       
    /*
    **
    ** Attempt to close the connection. Log but do not throw any errors...
    **
    */	
	
    if (this.connection) {
	  try { 
		await this.connection.release();
      } catch (e) {
        this.yadamuLogger.logException([`${this.constructor.name}.reconnectImpl()`,`{this.constructor.name}.release()`],e);
      }
    }

    let retryCount = 0;
	let connectionFailure 
    this.connectionOpen = false;
    
    while (retryCount < 10) {
	  let stack
      try {
        this.connection = await this.getConnectionFromPool()
        // this.yadamuLogger.trace([`${this.constructor.name}.reconnectImpl()`],`New connection availabe.`);
        return;
      } catch (e) {
        if (true) {
		  connectionFailure = e;
          this.yadamuLogger.warning([`${this.constructor.name}.reconnectImpl()`],`Waiting for ${this.DATABASE_VENDOR} restart.`)
          await this.waitForRestart(500);
          retryCount++;
        }
        else {
          this.yadamuLogger.logException([`${this.constructor.name}.reconnectImpl()`,`${this.constructor.name}.getConnectionFromPool()`],e);
          throw e;
        }
      }
    }
    // this.yadamuLogger.trace([`${this.constructor.name}.reconnectImpl()`],`Unable to re-establish connection.`)
	throw connectionFailure
  }

  async configureConnection() {
    
	const yadamuLogger = this.yadamuLogger
    const databaseVendor = this.DATABASE_VENDOR
   
    const self = this
    this.connection.on('error',
	  function(err, p) {
        // yadamuLogger.info([`${databaseVendor}`,`Connection.onError()`],err.message);
   	    // Do not throw errors here.. Node will terminate immediately
   	    // const pgErr = new PostgresError(err,self.postgresStack,self.postgressOperation)  
        // throw pgErr
      }
	)

    this.connection.on('notice',
	  function(n){ 
	    const notice = JSON.parse(JSON.stringify(n));
        switch (notice.code) {
          case '42P07': // Table exists on Create Table if not exists
            break;
          case '00000': // Table not found on Drop Table if exists
		    break;
          default:
            yadamuLogger.info([`${this.constructor.name}.onNotice()`],`${JSON.stringify(n)}`);
        }
      }
	)  
  
    const setTimezone = `set timezone to 'UTC'`
	this.executeSQL(setTimezone);
  
    const setFloatPrecision = `set extra_float_digits to 3`
	this.executeSQL(setFloatPrecision);

    const setIntervalFormat =  `SET intervalstyle = 'iso_8601';`;
	this.executeSQL(setIntervalFormat);
  }
  
  /*
  **
  ** Overridden Methods
  **
  */
  
  get DATABASE_VENDOR()    { return 'Postgres' };
  get SOFTWARE_VENDOR()    { return 'The PostgreSQL Global Development Group' };
  get SPATIAL_FORMAT()      { return this.spatialFormat };
  get DEFAULT_PARAMETERS() { return this.yadamu.getYadamuDefaults().postgres }

  constructor(yadamu) {
    super(yadamu,yadamu.getYadamuDefaults().postgres);
       
    this.pgClient = undefined;
    this.useBinaryJSON = false
    this.transactionInProgress = false;
  }

  getConnectionProperties() {
    return {
      user      : this.parameters.USERNAME
     ,host      : this.parameters.HOSTNAME
     ,database  : this.parameters.DATABASE
     ,password  : this.parameters.PASSWORD
     ,port      : this.parameters.PORT
    }
  }

  /*  
  **
  **  Connect to the database. Set global setttings
  **
  */
  
  async executeSQL(sqlStatement,args) {
	
    let attemptReconnect = this.attemptReconnection;

	if ((this.status.sqlTrace) && (typeof sqlStatemeent === 'string')) {
      this.status.sqlTrace.write(this.traceSQL(sqlStatement));
    }

    let stack
    while (true) {
      // Exit with result or exception.  
      try {
        const sqlStartTime = performance.now();
		stack = new Error().stack
        const results = await this.connection.query(sqlStatement,args)
        this.traceTiming(sqlStartTime,performance.now())
		return results;
      } catch (e) {
		const cause = new PostgresError(e,stack,sqlStatement);
		if (attemptReconnect && cause.lostConnection()) {
          attemptReconnect = false;
		  // reconnect() throws cause if it cannot reconnect...
          await this.reconnect(cause)
          continue;
        }
        throw cause
      }      
    } 
	
  }
  
  async initialize() {
    await super.initialize(true);   
    this.spatialFormat = this.parameters.SPATIAL_FORMAT ? this.parameters.SPATIAL_FORMAT : super.SPATIAL_FORMAT
  }
    
  /*
  **
  **  Gracefully close down the database connection and pool.
  **
  */
  
  async finalize() {
	await super.finalize()
  } 

  /*
  **
  **  Abort the database connection and pool.
  **
  */

  async abort() {
    super.abort();
  }

  /*
  **
  ** Begin a transaction
  **
  */
  
  async beginTransaction() {

     const sqlStatement =  `begin transaction`
     await this.executeSQL(sqlStatement);
	 super.beginTransaction();

  }

  /*
  **
  ** Commit the current transaction
  **
  */
  
  async commitTransaction() {
	  
     const sqlStatement =  `commit transaction`
	 await this.executeSQL(sqlStatement);
	 super.commitTransaction()
  }

  /*
  **
  ** Abort the current transaction
  **
  */
  
  async rollbackTransaction(cause) {

	if (cause && (typeof cause.lostConnection === 'function') && cause.lostConnection()) {
	  throw cause;
	}

    const sqlStatement =  `rollback transaction`
	 
	try {
      await this.executeSQL(sqlStatement);
      super.rollbackTransaction()
	} catch (e) {
	  if (cause instanceof Error) {
		this.yadamuLogger.logException([`${this.constructor.name}.rollbackTransaction()`],e)
	    e = cause
	  }
	  throw e;
	}
  }

  async createSavePoint() {

    await this.executeSQL(sqlCreateSavePoint);
    super.createSavePoint();
  }
  
  async restoreSavePoint(cause) {

	if (cause && (typeof cause.lostConnection === 'function') && cause.lostConnection()) {
	  throw cause;
	}
	
    let stack
    try {
      await this.executeSQL(sqlRestoreSavePoint);
      super.restoreSavePoint();
	} catch (e) {
      if (cause instanceof Error) {
        this.yadamuLogger.logException([`${this.constructor.name}.rollbackTransaction()`],e)
	    e = cause
	  }
	  throw e;
	}
  }  

  async releaseSavePoint(cause) {

    await this.executeSQL(sqlReleaseSavePoint);    
    super.releaseSavePoint();

  } 
  
  /*
  **
  ** The following methods are used by JSON_TABLE() style import operations  
  **
  */

  /*
  **
  **  Upload a JSON File to the server. Optionally return a handle that can be used to process the file
  **
  */

  async createStagingTable() {
  	let sqlStatement = `drop table if exists "YADAMU_STAGING"`;		
  	await this.executeSQL(sqlStatement);
  	sqlStatement = `create temporary table if not exists "YADAMU_STAGING" (data ${this.useBinaryJSON === true ? 'jsonb' : 'json'}) on commit preserve rows`;					   
  	await this.executeSQL(sqlStatement);
  }
  
  async loadStagingTable(importFilePath) {

    const copyStatement = `copy "YADAMU_STAGING" from STDIN csv quote e'\x01' delimiter e'\x02'`;
    if (this.status.sqlTrace) {
      this.status.sqlTrace.write(this.traceSQL(copyStatement))
    }    

    let inputStream = fs.createReadStream(importFilePath);
    const stream = await this.executeSQL(CopyFrom(copyStatement));
    const importProcess = new Promise(async function(resolve,reject) {  
      stream.on('end',function() {resolve()})
  	  stream.on('error',function(err){reject(err)});  	  
      inputStream.pipe(stream);
    })  
    
    const startTime = performance.now();
    await importProcess;
    const elapsedTime = performance.now() - startTime
    inputStream.close()
    return elapsedTime;
  }
  
  async uploadFile(importFilePath) {
    let elapsedTime;
    try {
      await this.createStagingTable();    
      elapsedTime = await this.loadStagingTable(importFilePath)
    }
    catch (e) {
      if (e.code && (e.code === '54000')) {
        this.yadamuLogger.info([`${this.constructor.name}.uploadFile()`],`Cannot process file using Binary JSON. Switching to textual JSON.`)
        this.useBinaryJSON = false;
        await this.createStagingTable();
        elapsedTime = await this.loadStagingTable(importFilePath);	
      }      
      else {
        throw e
      }
    }
  }
  
  /*
  **
  **  Process a JSON File that has been uploaded to the server. 
  **
  */

  processLog(log) {
    super.processLog(log, this.status, this.yadamuLogger)
    return log
  }

  async processStagingTable(schema) {  	
  	const sqlStatement = `select ${this.useBinaryJSON ? 'import_jsonb' : 'import_json'}(data,$1) from "YADAMU_STAGING"`;
  	var results = await this.executeSQL(sqlStatement,[schema]);
    if (results.rows.length > 0) {
      if (this.useBinaryJSON  === true) {
	    return this.processLog(results.rows[0].import_jsonb);  
      }
      else {
	    return this.processLog(results.rows[0].import_json);  
      }
    }
    else {
      this.yadamuLogger.error([`${this.constructor.name}.processStagingTable()`],`Unexpected Error. No response from ${ this.useBinaryJSON === true ? 'CALL IMPORT_JSONB()' : 'CALL_IMPORT_JSON()'}. Please ensure file is valid JSON and NOT pretty printed.`);
      // Return value will be parsed....
      return [];
    }
  }

  async processFile(hndl) {
     return await this.processStagingTable(this.parameters.TO_USER)
  }
  
  /*
  **
  ** The following methods are used by the YADAMU DBReader class
  **
  */
  
  /*
  **
  **  Generate the SystemInformation object for an Export operation
  **
  */
  
  async getPostgisInfo() {

    const sqlStatement  =  `SELECT PostGIS_full_version() "POSTGIS"`;
    
    let postgis = undefined
    
    try {
      const results = await this.executeSQL(sqlStatement)
      return results.rows[0].POSTGIS;
	} catch (e) {
      if (e.code && (e.code === '42883')) {
        // ### What to do about SystemInfo.SPATIAL_FORMAT There can be no Geography or Geometry columns without POSTGIS
        return "Not Installed"
      }
      else {
        throw e;
      }
    }
  }

  async getSystemInformation() {     
  
    const postgisInfo = await this.getPostgisInfo();
   
    const results = await this.executeSQL(sqlSystemInformation)
    const sysInfo = results.rows[0];
	
    return {
      date               : new Date().toISOString()
     ,timeZoneOffset     : new Date().getTimezoneOffset()                      
     ,sessionTimeZone    : sysInfo.SESSION_TIME_ZONE
     ,vendor             : this.DATABASE_VENDOR
     ,postgisInfo        : postgisInfo
     ,spatialFormat      : this.SPATIAL_FORMAT
     ,schema             : this.parameters.FROM_USER
     ,exportVersion      : this.EXPORT_VERSION
	 ,sessionUser        : sysInfo.session_user
     ,dbName             : sysInfo.database_name
     ,databaseVersion    : sysInfo.database_version
     ,softwareVendor     : this.SOFTWARE_VENDOR
     ,nodeClient         : {
        version          : process.version
       ,architecture     : process.arch
       ,platform         : process.platform
      }      
    }
  }

  /*
  **
  **  Generate a set of DDL operations from the metadata generated by an Export operation
  **
  */

  async getDDLOperations() {
    return undefined
  }
  
  async fetchMetadata(schema) {
    const results = await this.executeSQL(sqlGenerateQueries,[schema,this.spatialFormat]);
    this.metadata = results.rows[0].export_json;
  }
  
  generateTableInfo() {
      
    const tableInfo = Object.keys(this.metadata).map(function(value) {
      return {TABLE_NAME : value, SQL_STATEMENT : this.metadata[value].sqlStatemeent}
    },this)
    return tableInfo;    
    
  }
  
  async getSchemaInfo(schema) {
    await this.fetchMetadata(this.parameters[schema]);
    return this.generateTableInfo();
  }

  generateMetadata(tableInfo,server) {     
    return this.metadata;
  }
   
  generateSelectStatement(tableMetadata) {
     return tableMetadata;
  }   

  createParser(tableInfo,objectMode) {
    return new DBParser(tableInfo,objectMode,this.yadamuLogger);
  }  
  
  forceEndOnInputStreamError(error) {
	return true;
  }
  
  streamingError(e,stack,tableInfo) {
    return new PostgresError(e,stack,tableInfo.SQL_STATEMENT)
  }
  
  async getInputStream(tableInfo,parser) {        
    const queryStream = new QueryStream(tableInfo.SQL_STATEMENT)
    return await this.executeSQL(queryStream)   
  }      

  /*
  **
  ** The following methods are used by the YADAMU DBwriter class
  **
  */
  
  async createSchema(schema) {
    const createSchema = `create schema if not exists "${schema}"`;
    await this.executeSQL(createSchema);   
  }
  
  async executeDDLImpl(ddl) {
    await this.createSchema(this.parameters.TO_USER);
    await Promise.all(ddl.map(async function(ddlStatement) {
      try {
        ddlStatement = ddlStatement.replace(/%%SCHEMA%%/g,this.parameters.TO_USER);
        return await this.executeSQL(ddlStatement);
      } catch (e) {
        this.yadamuLogger.logException([`${this.constructor.name}.executeDDL()`],e)
        this.yadamuLogger.writeDirect(`${ddlStatement}\n`)
      }
    },this))
  }
  
  async generateStatementCache(schema,executeDDL) {
    await super.generateStatementCache(StatementGenerator, schema, executeDDL)
  }

  getTableWriter(table) {
    const tableName = this.metadata[table].tableName
    return new TableWriter(this,tableName,this.statementCache[tableName],this.status,this.yadamuLogger);      
  }
  
  async insertBatch(sqlStatement,batch) {
    const result = await this.executeSQL(sqlStatement,batch)
    return result;
  }

  async slaveDBI(slaveNumber) {
	const dbi = new PostgresDBI(this.yadamu)
	const connection = await this.getConnectionFromPool()
	return await super.slaveDBI(slaveNumber,dbi,connection)
  }
  
  tableWriterFactory(tableName) {
    return new TableWriter(this,tableName,this.statementCache[tableName],this.status,this.yadamuLogger)
  }
  
}

module.exports = PostgresDBI
```

**Comment by markddrake** [comment]
OK Try this..

```
const {Client,Pool} = require('pg')
const  QueryStream = require('pg-query-stream')
const Transform = require('stream').Transform;

class MyTransform extends Transform {

  constructor() {
    super({objectMode: true });  
	this.counter = 0;
  }
  
  async _transform (data,encodoing,done) {
	this.counter++
	if ((this.counter % 10000) === 0 ){
      this.push('.')
	}
    done();
  }
}
  
async function main() {

 const pool = new Pool({
   user: 'postgres',
   host: 'yadamu-db2',
   database: 'yadamu',
    password: 'oracle',
    port: 5432
  })
  
 const connection  = await pool.connect()
 connection.on('error',
	  function(err, p) {
        // yadamuLogger.info([`${databaseVendor}`,`Connection.onError()`],err.message);
   	    // Do not throw errors here.. Node will terminate immediately
   	    // const pgErr = new PostgresError(err,self.postgresStack,self.postgressOperation)  
        // throw pgErr
      }
	)

 const res = await connection.query(`select pg_backend_pid()`)
 const pid = res.rows[0].pg_backend_pid;
 console.log(pid)
 console.log('Connected')
 
 const conn2 = await pool.connect();
 setTimeout(
    async function() {
	 const res = await conn2.query(`select pg_terminate_backend(${pid})`);
	 await conn2.release()
	},2000);
               
 const queytStream = new QueryStream(`select jsonb_build_array("PROD_ID","CUST_ID","TIME_ID"::timestamptz,"CHANNEL_ID","PROMO_ID","QUANTITY_SOLD","AMOUNT_SOLD") "json" from "SH"."SALES"`)
 const resultStream = await connection.query(queytStream)
 const t = new MyTransform()

 console.log('Creating Promise')
 const copy = new Promise(async function foo(resolve,reject) {   
   resultStream.on('error',function(e) {console.log(`Error emitted after ${t.counter} rows.`),reject(e)})
   resultStream.on('end',function() { resolve('DONE')})
   try {
     resultStream.pipe(t).pipe(process.stdout);
   } catch(e) {
	 reject(e);
   }
 })
 
 console.log('Waiting for Pipe')
 await copy
 console.log('Pipe Complete');
 await connection.release()
 await pool.end()
 
}
main().then(function(r) { console.log(r)}).catch(function(e) {console.log(e)});
```

**Comment by markddrake** [comment]
Running with 3.0.7
```
C:\Development\YADAMU>node scratch\postgres\killBackend.js
11666
Connected
Creating Promise
Waiting for Pipe
..............
C:\Development\YADAMU>
```

Running with 2.1.2
```
C:\Development\YADAMU>node scratch\postgres\killBackend.js
11674
Connected
Creating Promise
Waiting for Pipe
.............Error emitted after 133100 rows.
error: terminating connection due to administrator command
    at Connection.parseE (C:\Development\YADAMU\node_modules\pg\lib\connection.js:581:48)
    at Connection.parseMessage (C:\Development\YADAMU\node_modules\pg\lib\connection.js:380:19)
    at Socket.<anonymous> (C:\Development\YADAMU\node_modules\pg\lib\connection.js:116:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 116,
  severity: 'FATAL',
  code: '57P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '3011',
  routine: 'ProcessInterrupts'
}
```

So I guess I'm now spending the rest of my automating my kill tests.. :)

**Comment by Envek** [comment]
Faced very similar issue today while testing ”what if something breaks while streaming results” (and terminating postgres backend is the simplest way to emulate such a failure).

With code like this (somewhere in Express.js route handlers):
```js
const { Client } = require('pg');
const QueryStream = require('pg-query-stream');

// Using demo database from https://postgrespro.com/education/demodb
const client = new Client({ connectionString: 'postgresql:///demo' });
await client.connect();
const qs = new QueryStream('SELECT * FROM bookings;');
const stream = client.query(qs);
stream.on('data', console.log);
```

And terminating postgres backend somewhere in-between:
```sql
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE query = 'SELECT * FROM bookings;';
```

My node process terminates with following error:
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/home/envek/…/node_modules/pg/lib/client.js:272:71)
```

**Workaround**: manually forward error to stream
```js
client.once('error', (...args) => stream.emit('error', ...args));
```

Now it doesn't crash and I can subscribe to `error` message on stream.

Not sure whether this is expected behavior or not.

**Versions**:
node: 12.18.3
pg: 8.3.0
pg-query-stream: 3.2.0:

**Comment by brianc** [comment]
Hey nice - are you able to build a test case for this in the code? I think the stream _should_ throw an error if the client has an error...this is a bug.

**Comment by brianc** [comment]
actually I think I can fix this right now...gimme a min

**Comment by brianc** [comment]
okay i ran out of time for the day 😦 Its' tricky because the client _is_ dead, so you want to handle the death of the client on the client, but the query stream should reject as well.

**Comment by Envek** [comment]
> client is dead, so you want to handle the death of the client on the client

:exploding_head:

**Comment by markddrake** [comment]
Uh, yes. couldn't agree more. However the point is the code I have that "handles the death of the client on the client" that works with 2.1.2 does not work with 3.1.7 because the stream does not get the error...

**Comment by lastmjs** [comment]
I'm having trouble catching errors in streams as well

**Comment by markddrake** [comment]
Just retried with 4.x and the issue still exists..

**Comment by markddrake** [comment]
I just had to upgrade to avoid other issues that had started to surface with @2.1.2. I am now using the following code to work around the fact the pg-query-stream@4.0.0 does not raise an error when the connection is lost.

```
const handleConnectionError = (err) => {inputStream.destroy(err); inputStream.emit('error',err)}
this.connection.on('error',handleConnectionError)
inputStream.on('end',() => { this.connection.removeListener('end',handleConnectionError)}).on('error',() => { this.connection.removeListener('error',handleConnectionError)})    		
```
Two issues, first, I still don't think I should need to do this. 

Second, I don't think I should have to force the input stream to emit the error, calling destroy with the error should cause the error to be emitted.
