### ISSUE TITLE
Error - column "typarray" does not exist

### ISSUE THREAD

**Issue by eboats** [brianc/node-postgres#2248]
We have an older application that is trying to use the below sequelize and pg versions to connect to a Postgres 8.2 db and am getting the error   "column "typarray" does not exist"

I've tried various combinations of sequelize and pg versions and no luck.  Is there a version of pg that is compatible with this version of sequelize?

Postgres db 8.2
Node 8
sequelize 3.35.1
pg  (tried versions 4 through 8 )

Error is below :

Unhandled rejection error: column "typarray" does not exist
    at Connection.parseE    /node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage  /node_modules/pg/lib/connection.js:366:17)
    at TLSSocket.<anonymous> /node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20)

**Comment by sehrope** [comment]
That's not an issue with the driver. That error is being returned back from the server and is caused by querying for a field that does not exist. Assuming sequelize is trying to query pg_type, it's because that column did not appear in the catalog table until PG version 8.3: https://www.postgresql.org/docs/8.2/catalog-pg-type.html

I'd suggest opening this up as a sequelize bug or somehow overriding the SQL it's executing to be compatible with your PG version.

**Comment by boromisp** [comment]
Looks like you have to upgrade either sequelize or the database: https://github.com/sequelize/sequelize/issues/5254

**Comment by eboats** [comment]
Thanks sehrope for the response - that was exactly the issue.  The issue is with the Sequelize connection-manager.js trying to run a query ( SELECT typname, typtype, oid, typarray FROM pg_type ) that isn't supported in Postgres 8.3 and above.  It looks like all versions of sequelize after 3.13.0 have this query so consequently don't work with Postgres 8.2 and below.
