### ISSUE TITLE
Native binding not loading

### ISSUE THREAD

**Issue by mudcube** [brianc/node-postgres#231]
When switching from require('pg') to require('pg').native Node creates this error:

mud:sketch-src mud$ node server.js 

Error: Cannot find module '/Library/WebServer/Documents/sketchpad.io/sketch-src/node_modules/pg/lib/native/../../build/default/binding'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Library/WebServer/Documents/sketchpad.io/sketch-src/node_modules/pg/lib/native/index.js:12:12)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

Looking in the node_modules directly, I'm not seeing the /build/default/binding/—is that something that can be build using a script?

**Comment by Luchooo** [comment]
Hi, you use postgres 9.3?, this solution is first unistall pg with `npm uninstall pg`, after if use postgres 9.3 install the next dependency `sudo apt-get install libpq-dev` and now install pg with `npm install pg`, This solved my problem.
