### ISSUE TITLE
Some uses of the WITH statement work, others don't?

### ISSUE THREAD

**Issue by awsjeffg** [brianc/node-postgres#2339]
I'm trying to do some queries that use `WITH`, and getting different results. A query like this works:

```sql
WITH dates(input_date, curr_week_start, curr_week_end, curr_ww) AS ( 
  SELECT CURRENT_DATE as input_date,
        -- last week 
    TO_DATE((DATE_TRUNC('week',input_date + 1 -7) - '1 day'::INTERVAL),'YYYY-MM-DD') AS curr_week_start, 
    TO_DATE (curr_week_start + '7 days'::INTERVAL,'YYYY-MM-DD') AS curr_week_end, datepart (w,input_date+1) as current_ww
)
SELECT * FROM dates;
```

This works correctly, I assume because I am just using the database engine to get datetime info. When I select data from the database inside a with statement and then try to use is in the rest of the query, for example:

```sql
WITH items(id, count) AS (
  SELECT DISTINCT id, COUNT(*) as count
  FROM tablename
  WHERE tablename.date <= DATE('2020-09-06')
  AND tablename.date >= DATE('2020-08-30')
  GROUP BY id
  ORDER BY count DESC
)
SELECT * FROM items LIMIT 10;
```

A query like this works fine with a GUI client like Aginity but fails using node-postgres with an error:

```
error: relation "deployments" does not exist
    at Parser.parseErrorMessage (/Users/jefgri/code/scripts/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/jefgri/code/scripts/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/jefgri/code/scripts/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/Users/jefgri/code/scripts/node_modules/pg-protocol/dist/index.js:8:42)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at TLSSocket.Readable.push (_stream_readable.js:218:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 146,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: '/path/to/catalog/namespace.c',
  line: '269',
  routine: 'LocalRangeVarGetRelid'
}
```

The node-postgres code running this query looks like this:

```javascript
const { Client, Pool } = require('pg');

const pool = new Pool({
  user: 'user',
  host: 'hostname',
  database: 'somedb',
  password: 'sompass',
  port: '9000',
  ssl: {
    rejectUnauthorized: false
  }
});

pool.connect();

let with_query = `WITH items(id, count) AS (
  SELECT DISTINCT id, COUNT(*) as count
  FROM tablename
  WHERE tablename.date <= DATE('2020-09-06')
  AND tablename.date >= DATE('2020-08-30')
  GROUP BY id
  ORDER BY count DESC
)
SELECT * FROM items LIMIT 10;
`;

pool.query(with_query, (err, res) => {
  console.log(err ? err.stack : res.rows);
  pool.end();
});
```

**Comment by awsjeffg** [comment]
If you ever run into this issue again, the answer is this: some fancy clients like Aginity will take bare table names in a query like this however node-postgres really wants you to quote the table name like so:

```
WITH items(id, count) AS (
  SELECT DISTINCT id, COUNT(*) as count
  FROM tablename
  WHERE tablename.date <= DATE('2020-09-06')
  AND tablename.date >= DATE('2020-08-30')
  GROUP BY id
  ORDER BY count DESC
)
SELECT * FROM "items" LIMIT 10; -- quote that virtual table name!
```

It turns out googling for help for this error relating to 'WITH' statements was hard but I did find something finally in SO:

https://stackoverflow.com/a/52812437/562145
