### ISSUE TITLE
App crashes on conection lost to Postgres

### ISSUE THREAD

**Issue by snajdov** [brianc/node-postgres#2386]
I've looked over previous issues, and in the docs:
- https://node-postgres.com/api/pool#events
- https://node-postgres.com/api/client#events

and I can't seem to figure it out.

The use case is this:
(1) I have an ExpressJS app that creates a `new Pool()`
(2) I use the `pool.query` to issue queries to the DB
(3) I use the `pool.on('error', callback)` to catch client errors

However, when I test a restart on the DB, it issues this:
```javascript
events.js:291
      throw er; // Unhandled 'error' event
      ^

error: terminating connection due to administrator command
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on Client instance at:
    at Client._handleErrorEvent (/usr/src/app/node_modules/pg/lib/client.js:310:10)
    at Client._handleErrorMessage (/usr/src/app/node_modules/pg/lib/client.js:321:12)
    at Connection.emit (events.js:314:20)
    at /usr/src/app/node_modules/pg/lib/connection.js:109:12
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:10:42)
    [... lines matching original stack trace ...]
    at Socket.Readable.push (_stream_readable.js:214:10) {
  length: 116,
  severity: 'FATAL',
  code: '57P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '3078',
  routine: 'ProcessInterrupts'
}
```
and the app crashes.

Having a `client.on('error', callback)` seems to work, but I don't want to access `client`s directly, but through the `pool`, so I don't use a single connection.
Shouldn't `pool.on('error', callback)` catch any errors thrown from the `client`s?

Below a code example:

```javascript
var pool = new Pool({
	host: 'db',
	user: 'postgres',
	password: 'example',
	database: 'example',
	max: 10,
	idleTimeoutMillis: 30000,
	connectionTimeoutMillis: 2000
});

var reconnecting = 0;
pool.on('error', reconnect); // try reconnecting on error
pool.connect().then(_ => { console.log('connected'); }).catch(reconnect); // catch connect errors as well


async function reconnect(_) {
	if (!reconnecting) { // if not reconnecting (checking because multiple clients may issue reconnects)
		reconnecting = 1;
		setTimeout(_ => { // try reconnect after 2 seconds
			pool.connect()
				.then(_ => { reconnecting = 0; })
				.catch(_ => {
					reconnecting = 0;
					reconnect();
				});
		}, 2000);
	}
}

```

Connecting is successful, but when I restart the DB to test reconnecting, it issues the `Unhandled 'error' event` above, and the whole app crashes with `exit status 1`:
```
      Name                    Command               State     Ports  
---------------------------------------------------------------------
app_1              docker-entrypoint.sh node  ...   Exit 1
```
The `reconnect()` function is not called at all.

Any reconnect strategy for a `pool`?

**Comment by snajdov** [comment]
Using the `connect` event solved the problem for me:

```javascript
var reconnecting = 0;
pool.on('error', reconnect); // try reconnecting on error
pool.on('connect', (c) => { c.on('error', reconnect); }); // attach reconnect() as callback to each new acquired client
pool.connect().then((c) => { console.log('connected'); }).catch(reconnect);

async function reconnect(_) {
	if (!reconnecting) { // if not reconnecting (checking because multiple clients may issue reconnects)
		console.log('reconnecting...');
		reconnecting = 1;
		setTimeout(_ => { // try reconnect after 2 seconds
			pool.connect()
				.then(_ => { reconnecting = 0; console.log('connected'); })
				.catch(_ => {
					reconnecting = 0;
					reconnect();
				});
		}, 2000);
	}
}
```

Closing this. Feel free to open if I missed something.
