### ISSUE TITLE
Connection issue azure database

### ISSUE THREAD

**Issue by mdpgeobe** [brianc/node-postgres#2401]
Hi !

I have some difficulties to use the module with Azure PostgreSQL Database. The problem is the `@` in the username given by Microsoft. I have read to use `%40` instead with a connection string (https://github.com/brianc/node-postgres/issues/2288#issuecomment-660571245), but I have the same problem. For example, with this connection string: `postgresql://john%40mdpgeobe:[mypassword]@mdpgeobe.postgres.database.azure.com:5432/exercices?ssl=true` (the password is the good one, of course), I have this error: 
```
2020-11-05T16:51:37.606994959Z: [ERROR]  error: no pg_hba.conf entry for host "40.89.161.203", user "john", database "exercices", SSL on
2020-11-05T16:51:37.607046259Z: [ERROR]      at Parser.parseErrorMessage (/node_modules/pg-protocol/dist/parser.js:278:15)
2020-11-05T16:51:37.607052059Z: [ERROR]      at Parser.handlePacket (/node_modules/pg-protocol/dist/parser.js:126:29)
2020-11-05T16:51:37.607056459Z: [ERROR]      at Parser.parse (/node_modules/pg-protocol/dist/parser.js:39:38)
2020-11-05T16:51:37.607060759Z: [ERROR]      at TLSSocket.<anonymous> (/node_modules/pg-protocol/dist/index.js:8:42)
2020-11-05T16:51:37.607065859Z: [ERROR]      at TLSSocket.emit (events.js:314:20)
2020-11-05T16:51:37.607070060Z: [ERROR]      at addChunk (_stream_readable.js:303:12)
2020-11-05T16:51:37.607074260Z: [ERROR]      at readableAddChunk (_stream_readable.js:279:9)
2020-11-05T16:51:37.607078460Z: [ERROR]      at TLSSocket.Readable.push (_stream_readable.js:218:10)
2020-11-05T16:51:37.607082660Z: [ERROR]      at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```

In case if you want the script used to configure pg:
```js
require("dotenv").config();
const process = require("process");
const pg = require("pg");
const Pool = pg.Pool;
const username = process.env.DB_USER;
const dbPassword = process.env.DB_PASSWORD;
const dbHost = process.env.DB_HOST;
const dbDatabase = process.env.DB_DATABASE
const dbPort = process.env.DB_PORT;

const connectionString = `postgresql://${username}:${dbPassword}@${dbHost}:${dbPort}/${dbDatabase}?ssl=true`
console.log(connectionString);


const pool = new Pool({
    connectionString
});

module.exports = pool;
```

The console.log is just used to be sure that the connection string is well constructed and I received the good parameters. I have no idea what to do now :/
I use the version 8.3.3

**Comment by mdpgeobe** [comment]
After investigation, the bug only happens on Linux & MaxOS. On Windows, it works fine.

**Comment by brianc** [comment]
you might need to `encodeURIComponent` on your password variable.  Can you
create a self-contained script that reproduces the issue I can run over
here?  It's almost certainly the way you're encoding the password.

**Comment by martindavid** [comment]
I have similar error connecting to Managed database in DigitalOcean. Up until now, I have no idea what went wrong. I have similar setup like @mdpgeobe

**Comment by mdpgeobe** [comment]
Hi Brianc!

Sorry for the delay in responding, the last few days have been quite difficult for me 😅 Your idea was correct! There was a special character that had to be URI encoded. It should have been obvious to me 😳

Thanks for your help, brianc 👍
