### ISSUE TITLE
Can't select `schema` whose name includes `-`

### ISSUE THREAD

**Issue by zhaoyi0113** [brianc/node-postgres#2429]
I use this api to select different schema: 

```
await client.query(`SET search_path TO test-38`);
await client.query(...)
```

I always got `error: relation "Customers" does not exist` error if I use a schema with `-`  in its name. It works fine if I remove the `-`. It works fine via command line. 
Is it a bug in this library? Is there any other method for me to change the `search_path` to select different schema?

**Comment by vitaly-t** [comment]
> Is it a bug in this library?

Definitely not. The error is on the server level, this library does not control schema resolution for table names. There is something amiss in your example.

**Comment by zhaoyi0113** [comment]
sorry, I mean it doesn't support putting `-` in the schema not about the number. Is the `-` not supported?

**Comment by vitaly-t** [comment]
You need to use `SET search_path TO "test-38"` in this case. That's just invalid escaping on your part.

**Comment by zhaoyi0113** [comment]
it doesn't work for "test-38" and I get an exception for that:

```
error: syntax error at or near "-"
          at Parser.parseErrorMessage (/Users/joey/dev/zeller/component-ams-engine/apps/system-testing/node_modules/pg-protocol/src/parser.ts:357:11)
          at Parser.handlePacket (/Users/joey/dev/zeller/component-ams-engine/apps/system-testing/node_modules/pg-protocol/src/parser.ts:186:21)
          at Parser.parse (/Users/joey/dev/zeller/component-ams-engine/apps/system-testing/node_modules/pg-protocol/src/parser.ts:101:30)
          at TLSSocket.<anonymous> (/Users/joey/dev/zeller/component-ams-engine/apps/system-testing/node_modules/pg-protocol/src/index.ts:7:48)
          at TLSSocket.emit (events.js:310:20)
          at TLSSocket.EventEmitter.emit (domain.js:482:12)
          at addChunk (_stream_readable.js:286:12)
          at readableAddChunk (_stream_readable.js:268:9)
          at TLSSocket.Readable.push (_stream_readable.js:209:10)
          at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
```

**Comment by charmander** [comment]
@zhaoyi0113 Can you show your updated query code?

**Comment by zhaoyi0113** [comment]
The exception is from this code: `await client.query(`SET search_path TO test-38`);`

**Comment by charmander** [comment]
@zhaoyi0113 That looks the same as the original, still missing quotes around `test-38`. `SET search_path TO "test-38"`

**Comment by zhaoyi0113** [comment]
it is the same issue. I tried both single quote and double quote but get the same exception.

```
await client.query(SET search_path TO 'test-38');
await client.query(SET search_path TO "test-38");
```

**Comment by vitaly-t** [comment]
@zhaoyi0113 Are you making a query on the same client or are you releasing the client and make query on another client from the pool? The latter might explain the issue, of setting the schema on a different connection session.

**Comment by zhaoyi0113** [comment]
Yes I am using the same client and the query code is not even run. Exception happens on set the serach_path.

**Comment by vitaly-t** [comment]
Try this:

```sql
SET search_path TO '"test-38"'
```

**Comment by zhaoyi0113** [comment]
This one works, thanks a lot.

**Comment by vitaly-t** [comment]
@zhaoyi0113 As a follow-up on this, I think this got something to do with you using a very old version of PostgreSQL server, because I have tried the same here with versions 11 and 13 of PostgreSQL, and got both `"test-38"` and `'test-38'` working just fine.

**Comment by zhaoyi0113** [comment]
Thanks for your confirm. I will check my server version.
