### ISSUE TITLE
Error [ERR_STREAM_WRITE_AFTER_END]: write after end

### ISSUE THREAD

**Issue by raymond-rogers** [brianc/node-postgres#2432]
I am occasionally seeing this error.  In only one of our services, and I have not been able to determine the root cause.  Is there any known condition that can cause these errors?

uncaughtException: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at Socket.Writable.write (_stream_writable.js:291:5)
    at Connection.end (/var/www/html/services/node_modules/pg/lib/connection.js:319:22)
    at Client.end (/var/www/html/services/node_modules/pg/lib/client.js:489:21)
    at Pool._remove (/var/www/html/services/node_modules/pg-pool/index.js:161:12)
    at Timeout.setTimeout (/var/www/html/services/node_modules/pg-pool/index.js:44:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by vitaly-t** [comment]
From the error stack, it looks like it is an old version of the library.

You should include version details of the library + NodeJS + OS that you are using.

**Comment by raymond-rogers** [comment]
Sorry for the delay, I was on vacation :)

This is running Ubuntu 18.04 server, Node 10, and pg 8.2.1
