### ISSUE TITLE
Error: A query must have either text or a name. Supplying neither is unsupported.

### ISSUE THREAD

**Issue by Bautista-Baiocchi-lora** [brianc/node-postgres#2435]
Hello,

I am running the latest version of node-postgres. 

I have the following code:

```
 async register(registerDTO: UserRegistrationDTO): Promise<boolean> {
    const client = await this.pool.connect();

    return await create_user(client, registerDTO);
  }


export const create_user = async (
  client,
  dto: UserRegistrationDTO,
): Promise<boolean> => {
  try {
    await client.query('BEGIN');

    const acc_id = await create_account(client, dto.email, dto.password);

    const doc_id = await create_person_document(client, dto.doc_id); //ERROR HERE!!!
    await create_person(client, acc_id, doc_id, dto);
    await client.query('COMMIT');
    return true;
  } catch (e) {
    await client.query('ROLLBACK');
    throw e;
  } finally {
    client.release();
  }
};


export const create_account = async (
  pg,
  email: string,
  password: string,
): Promise<string> => {
  return pg
    .query(create_account_query(email, password))
    .then((res) => res.rows[0].id);
};


const create_account_query = (email: string, password: string) => {
  return {
    text: 'INSERT INTO account(email, password) values ($1, $2) returning id',
    values: [email, password],
  };
};


export const create_person_document = async (pg, doc_id) => {
  return pg
    .query(create_person_document_query(doc_id))
    .then((res) => res.rows[0].doc_id);
};

const create_person_document_query = async (doc_id: string) => {
  return {
    text: 'INSERT INTO person_document(doc_id) values ($1) returning doc_id',
    values: [doc_id],
  };
};
```

Calling `create_person_document`(Marked in above code snippet) gives me the following error... 

> Error: A query must have either text or a name. Supplying neither is unsupported.\n    at Query.submit (/Users/bautista/Desktop/InviteApp/server/node_modules/pg/lib/query.js:145:14)\n    at Client._pulseQueryQueue (/Users/bautista/Desktop/InviteApp/server/node_modules/pg/lib/client.js:481:45)\n    at Client.query (/Users/bautista/Desktop/InviteApp/server/node_modules/pg/lib/client.js:576:10)\n    at /Users/bautista/Desktop/InviteApp/server/dist/user/person.repo.js:20:10\n    at Generator.next (<anonymous>)\n    at /Users/bautista/Desktop/InviteApp/server/dist/user/person.repo.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/bautista/Desktop/InviteApp/server/dist/user/person.repo.js:4:12)\n    at Object.exports.create_person_document (/Users/bautista/Desktop/InviteApp/server/dist/user/person.repo.js:18:50)\n    at /Users/bautista/Desktop/InviteApp/server/dist/user/user.repo.js:19:44 {stack: 'Error: A query must have either text or …App/server/dist/user/user.repo.js:19:44', …}

The query works just fine when I run it in the pg terminal.

**Comment by Bautista-Baiocchi-lora** [comment]
The error was caused by the "async" in the create_person_document_query method declaration.
