### ISSUE TITLE
Heroku node-gyp issues

### ISSUE THREAD

**Issue by jbrooksuk** [brianc/node-postgres#245]
I'm trying to push my code using this module to Heroku on a Cedar stack however I'm facing issues. Here is my output from the failed push.

```
Jamess-MacBook-Pro:hooligan jbrooksuk$ git push heroku master
Counting objects: 481, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (370/370), done.
Writing objects: 100% (398/398), 619.55 KiB | 31 KiB/s, done.
Total 398 (delta 156), reused 0 (delta 0)
-----> Removing .DS_Store files
-----> Node.js app detected
-----> Resolving engine versions

       WARNING: No version of Node.js specified in package.json, see:
       https://devcenter.heroku.com/articles/nodejs-versions

       WARNING: The default version of Node.js and npm on Heroku will begin
       tracking the latest stable release starting September 1, 2012.

       Using Node.js version: 0.4.7
       Using npm version: 1.0.106
-----> Fetching Node.js binaries
-----> Vendoring node into slug
-----> Installing dependencies with npm


       > pg@0.7.2 install /tmp/build_56r70aug7mbt/node_modules/pg
       > node-gyp rebuild || (exit 0)

       sh: node-gyp: not found

       > ws@0.4.25 install /tmp/build_56r70aug7mbt/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
       > (node-gyp rebuild 2> builderror.log) || (exit 0)


       > hiredis@0.1.14 preinstall /tmp/build_56r70aug7mbt/node_modules/socket.io/node_modules/redis/node_modules/hiredis
       > make || gmake

       cd deps/hiredis && make static
       make[1]: Entering directory `/tmp/build_56r70aug7mbt/node_modules/socket.io/node_modules/redis/node_modules/hiredis/deps/hiredis'
       make[1]: Nothing to be done for `static'.
       make[1]: Leaving directory `/tmp/build_56r70aug7mbt/node_modules/socket.io/node_modules/redis/node_modules/hiredis/deps/hiredis'
       node-waf configure build
       Setting srcdir to                        : /tmp/build_56r70aug7mbt/node_modules/socket.io/node_modules/redis/node_modules/hiredis 
       Setting blddir to                        : /tmp/build_56r70aug7mbt/node_modules/socket.io/node_modules/redis/node_modules/hiredis/build 
       Checking for program g++ or c++          : /usr/bin/g++ 
       Checking for program cpp                 : /usr/bin/cpp 
       Checking for program ar                  : /usr/bin/ar 
       Checking for program ranlib              : /usr/bin/ranlib 
       Checking for g++                         : ok  
       Checking for node path                   : not found 
       Checking for node prefix                 : ok /tmp/node-node-z32A 
       'configure' finished successfully (0.126s)
       Waf: Entering directory `/Users/jbrooksuk/Code/vagrant-heroku/hooligan/node_modules/socket.io/node_modules/redis/node_modules/hiredis/build'
       Waf: Leaving directory `/Users/jbrooksuk/Code/vagrant-heroku/hooligan/node_modules/socket.io/node_modules/redis/node_modules/hiredis/build'
       Traceback (most recent call last):
         File "/tmp/node-node-z32A/bin/node-waf", line 16, in <module>
           Scripting.prepare(t, os.getcwd(), VERSION, wafdir)
         File "/tmp/node-node-z32A/bin/../lib/node/wafadmin/Scripting.py", line 145, in prepare
           prepare_impl(t, cwd, ver, wafdir)
         File "/tmp/node-node-z32A/bin/../lib/node/wafadmin/Scripting.py", line 135, in prepare_impl
           main()
         File "/tmp/node-node-z32A/bin/../lib/node/wafadmin/Scripting.py", line 188, in main
           fun(ctx)
         File "/tmp/node-node-z32A/bin/../lib/node/wafadmin/Scripting.py", line 386, in build
           return build_impl(bld)
         File "/tmp/node-node-z32A/bin/../lib/node/wafadmin/Scripting.py", line 405, in build_impl
           bld.compile()
         File "/tmp/node-node-z32A/bin/../lib/node/wafadmin/Build.py", line 268, in compile
           os.chdir(self.bldnode.abspath())
       OSError: [Errno 2] No such file or directory: '/Users/jbrooksuk/Code/vagrant-heroku/hooligan/node_modules/socket.io/node_modules/redis/node_modules/hiredis/build'
       make: *** [all] Error 1
       sh: gmake: not found
       npm ERR! hiredis@0.1.14 preinstall: `make || gmake`
       npm ERR! `sh "-c" "make || gmake"` failed with 127
       npm ERR! 
       npm ERR! Failed at the hiredis@0.1.14 preinstall script.
       npm ERR! This is most likely a problem with the hiredis package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     make || gmake
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls hiredis
       npm ERR! There is likely additional logging output above.
       npm ERR! 
       npm ERR! System Linux 2.6.32-348-ec2
       npm ERR! command "/tmp/node-node-z32A/bin/node" "/tmp/node-npm-gYMn/cli.js" "rebuild"
       npm ERR! cwd /tmp/build_56r70aug7mbt
       npm ERR! node -v v0.4.7
       npm ERR! npm -v 1.0.106
       npm ERR! code ELIFECYCLE
       npm ERR! 
       npm ERR! Additional logging details can be found in:
       npm ERR!     /tmp/build_56r70aug7mbt/npm-debug.log
       npm not ok
 !     Failed to rebuild dependencies with npm
 !     Heroku push rejected, failed to compile Node.js app
```

I saw there was previously (7 months ago) a problem with node-gyp however I believe that should've been fixed by now.

**Comment by reklis** [comment]
for others googling, if you find this and you are working on an old project, you might need to `heroku stack:set cedar-14` to move an old project forward
