### ISSUE TITLE
Error: column "f2xuxt" does not exist

### ISSUE THREAD

**Issue by chsnt** [brianc/node-postgres#2460]
When i execute 
```
const pool = new Pool(credentials);
pool.query(SQL_FIND);
``` 
i get this:
```
error: column "f2xuxt" does not exist
    at Parser.parseErrorMessage (D:\Projects\apxub\parser\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (D:\Projects\apxub\parser\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (D:\Projects\apxub\parser\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (D:\Projects\apxub\parser\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:280:11)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 99,
  name: 'error',
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '37',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3194',
  routine: 'errorMissingColumn'
}
```

**Comment by charmander** [comment]
This is probably a problem with the query in `SQL_FIND` or the database it’s being run against instead of pg. If you can get the same query to work with a different driver/tool (like psql), please add details accordingly.
