### ISSUE TITLE
I want to insert an array of type array into postgress 

### ISSUE THREAD

**Issue by muhammedminhal** [brianc/node-postgres#2461]
```
 query.callfunction('fn_create_mp_product', parameters, (err, result) => {
        if (err) {
            console.log(err)
            callback(err);
        } else {
            if (result.status == 'success') {
                callback(null, result);
            } else {
                callback(result.message);
            }
        }
    });
```
I want to pass the parameters to fn_create_mp_product function in that parameter one on the perameter is an array of type array i want to insert it from node

```
  var products='array['+data.productId+']';
```
so i tried like this but it is hitting an error
```
{ error: function fn_create_mp_product(unknown, unknown, unknown, unknown) does not exist
    at Connection.parseE (/home/alignminds/Desktop/insidersBackendgit/insiderbackend/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/home/alignminds/Desktop/insidersBackendgit/insiderbackend/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/home/alignminds/Desktop/insidersBackendgit/insiderbackend/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 249,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint:
   'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '15',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',

```

I just want  array[23,23] in this format parameter to pass on to my fuction what can I do

**Comment by charmander** [comment]
Can you give an example of a successful call to the function, e.g. with a static query either using pg or another tool?
