### ISSUE TITLE
Having issues while using an 'INSERT' inside of a 'WITH'

### ISSUE THREAD

**Issue by grid0-dev** [brianc/node-postgres#2467]
### Problem 
I am inserting and then returning data based on the id generated from the insert. I am wanting to do this in one call vs multiples. When using the `insert` inside of the `with` if the table throws a Postgres error, like a unique constraint, the library eats the error and it never surfaces. I am going to do more investigating to get more data. 

The query I have is: 

```sql
WITH "insert" AS (
	INSERT INTO "table" ( "column1")
	VALUES
		( :column1 ) RETURNING "column1",
		"kit_uuid" 
... cut the rest out
```

Is this allowed with Postgres? When I run the query outside of node, it runs fine and errors surface. However when I use this query with knex I get: 

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

  at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:278:15)
at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:10:42)
```
here is how it is called. 
```js
const query = await self.client.raw(file.toString(), {column1: "my value"})
```

My original call was this 

```js
 let query = self.client
      .with('crate_record', (qb) => {
        qb.from('table1')
          .insert({
            column1, 
          })
          .returning(['column1']);
      })
      .from('create_record')
      .innerJoin('table2', 'table2.uuid', 'insert.column')
... 
  
```

I did a simple test to ensure this was the proper library. I tried both raw sql and using knex's `toString` method. Both of which throw this error. 

Any help would be appreciated.

**Comment by grid0-dev** [comment]
Issue not with library. a async / await function didn't have a return in my code making it appear it was the library. sorry for random post.
