### ISSUE TITLE
node + pg + docker: password authentication failed for user "postgres" although POSTGRES_HOST_AUTH_METHOD=trust

### ISSUE THREAD

**Issue by pretzelhammer** [brianc/node-postgres#2524]
Git repository with bug reproduction steps: https://github.com/pretzelhammer/node-pg-docker-issue

Quick summary:

I create and run a postgres instance inside of a docker container using the following command:

```
docker run --rm --name node-pg-postgres -e POSTGRES_HOST_AUTH_METHOD=trust -p 5432:5432 -d postgres
```

The `POSTGRES_HOST_AUTH_METHOD=trust` setting tells the postgres instance to accept all incoming connections without a password. I have verified I can connect without a password without issue using a GUI client (Postico). However, when I attempt to connect to the postgres instance using node-postgres and the following connection string `postgres://postgres@localhost:5432/postgres` I get the following error:

```
error: password authentication failed for user "postgres"
    at Parser.parseErrorMessage (/Users/kirill/github/node-pg-docker-issue/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/kirill/github/node-pg-docker-issue/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/kirill/github/node-pg-docker-issue/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/kirill/github/node-pg-docker-issue/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 104,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '337',
  routine: 'auth_failed'
} undefined
```

I only get this error with the node-postgres library. I have run this identical setup (with the same exact docker run command and the same exact connection string) in a couple Rust projects using the [r2d2](https://github.com/sfackler/r2d2) and [sqlx](https://github.com/launchbadge/sqlx) libraries and they connected without issue.

**Comment by pretzelhammer** [comment]
nevermind, I had a VM running on my machine which was somehow also was binding to localhost:5432 and that's what was messing with node-postgres, after shutting the VM down the errors I could finally connect without a password, closing this as it's probably fixed
