### ISSUE TITLE
pg-cursor (pg-query-stream) doesn't work with CockroachDB

### ISSUE THREAD

**Issue by janproch** [brianc/node-postgres#2546]
I am using node-postgres for connecting to CockroachDB, which works great. Only problem is with pg-cursor, which throws following error:
```
error: unknown portal "C_1"
    at Parser.parseErrorMessage (/home/jena/test/cockroach-test/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/jena/test/cockroach-test/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/jena/test/cockroach-test/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/jena/test/cockroach-test/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 72,
  severity: 'ERROR',
  code: '34000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'conn_executor.go',
  line: '1496',
  routine: 'func2'
}
```

The error occurs, when loading second batch from pg-cursor or when loading more than 100 rows from pg-query-stream.

Reproducing is simple, using this script against empty CockroachDB server running on localhost:
```js
const pg = require("pg");
const Cursor = require("pg-cursor");

async function run() {
  const client = new pg.Client({
    host: "localhost",
    port: 26257,
    user: "root",
    database: "postgres",
  });
  await client.connect();

  const cursor = client.query(
    new Cursor("select * from information_schema.tables", undefined, {
      rowMode: "array",
    })
  );

  const res = [];
  cursor.read(10, (err, rows) => {
    if (err) {
      throw err;
    }
    res.push(...rows);
    cursor.read(10, (err, rows) => {
      if (err) {
        throw err;
      }
      res.push(...rows);
    });
  });

  console.log("LENGTH", res.length);
}

run();
```

I am using package version listed in following package.json:
```json
{
  "dependencies": {
    "pg": "^8.6.0",
    "pg-cursor": "^2.6.0"
  }
}
```

I came across this error when using package pg-query-stream, which leads me to underlying package pg-cursor

**Comment by charmander** [comment]
CockroachDB doesn’t seem to support cursors yet: https://www.cockroachlabs.com/docs/v20.2/sql-feature-support.html

**Comment by janproch** [comment]
Thanks for info

After small research of node-postgres source code, I have found way to do this without cursor, so it work also on CockroachDB. It uses undocument query streaming (which from my point of view is much better way than using cursors)

```js

const pg = require("pg");

async function run() {
  const client = new pg.Client({
    host: "localhost",
    port: 26257,
    user: "root",
    database: "postgres",
  });
  await client.connect();

  const query = new pg.Query("select * from information_schema.tables");

  const res = [];
  query.on("row", (row) => res.push(row));
  query.on("error", (error) => console.log("ERROR", error));
  query.on("end", (row) => console.log("RESULT", res.length, "rows"));

  client.query(query);
}

run();

```
