### ISSUE TITLE
Supplies 8 parameters, but prepared statement "" requires 0

### ISSUE THREAD

**Issue by bjhobson12** [brianc/node-postgres#2555]
I'm not sure what's causing this or if I've done something wrong. Any help would be great. Node v14.1.0. "pg": "^8.6.0"

```
db.query(`DO
    $do$
    BEGIN
       IF NOT EXISTS (
          SELECT FROM user_profile  -- SELECT list can be empty for this
          WHERE (username = $1 OR email = $2)) THEN
          INSERT INTO user_profile(username,
            email,      
            password,      
            first_name,    
            last_name,         
            phone,         
            date_of_birth, 
            sex) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
       END IF
    END
    $do$;
    `, [
        req.body.username || null,
        req.body.email || null,
        req.body.password || null,
        req.body.first_name || null,
        req.body.last_name || null,
        req.body.phone || null,
        req.body.date_of_birth || null,
        req.body.sex || null
    ], (err, res) => {
        if (err) {

            console.log(err)
            return res.status(500).json({
                errorcode: 'could-not-query-error',
                message: `There was an error registering.`
            })
        }
        return res.status(200).json({
            success: 'The user exists'
        })
    })
```

Error message:

error: bind message supplies 8 parameters, but prepared statement "" requires 0
[0]     at Parser.parseErrorMessage (/Users/bhob12/Desktop/Quegeo/quegeo-web/node_modules/pg-protocol/dist/parser.js:287:98)
[0]     at Parser.handlePacket (/Users/bhob12/Desktop/Quegeo/quegeo-web/node_modules/pg-protocol/dist/parser.js:126:29)
[0]     at Parser.parse (/Users/bhob12/Desktop/Quegeo/quegeo-web/node_modules/pg-protocol/dist/parser.js:39:38)
[0]     at Socket.<anonymous> (/Users/bhob12/Desktop/Quegeo/quegeo-web/node_modules/pg-protocol/dist/index.js:11:42)
[0]     at Socket.emit (events.js:315:20)
[0]     at addChunk (_stream_readable.js:300:12)
[0]     at readableAddChunk (_stream_readable.js:276:9)
[0]     at Socket.Readable.push (_stream_readable.js:217:10)
[0]     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
[0]   length: 137,
[0]   severity: 'ERROR',
[0]   code: '08P01',
[0]   detail: undefined,
[0]   hint: undefined,
[0]   position: undefined,
[0]   internalPosition: undefined,
[0]   internalQuery: undefined,
[0]   where: undefined,
[0]   schema: undefined,
[0]   table: undefined,
[0]   column: undefined,
[0]   dataType: undefined,
[0]   constraint: undefined,
[0]   file: 'postgres.c',
[0]   line: '1700',
[0]   routine: 'exec_bind_message'
[0] }
[0] file:///Users/bhob12/Desktop/Quegeo/quegeo-web/routes/users.js:122
[0]             return res.status(500).json({
[0]                        ^

**Comment by bjhobson12** [comment]
Closing because ```DO``` is not considered valid SQL by Node-postgres

https://stackoverflow.com/questions/52488762/pg-wont-concatenate-large-sql-string

**Comment by charmander** [comment]
It is valid, just not as a prepared statement. But you shouldn’t do an insert based on an existence check to avoid duplicates; instead, the columns that shouldn’t be duplicated should be [unique keys](https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS). Then the query is just the `INSERT` part and you check for the error code and constraint name if it produces an error.

**Comment by sehrope** [comment]
If you have a UNIQUE constraint or index, you can also use `INSERT ... ON CONFLICT ..." to either ignore the duplicate or perform a different UPDATE action: https://www.postgresql.org/docs/current/sql-insert.html

All of that functionality is provided by the server. This driver never parses the SQL text itself. It's always sent as-is to the server and the server decides if it's a valid command.
