### ISSUE TITLE
half process meet Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by laorunsen** [brianc/node-postgres#2600]
we use a postgresql HA  cluster with vip,  once vip switchover ,   we found follow  service log:

testserver:/var/log/service # tail -f testservice.log
{"name":"testservice.query","hostname":"testserver","pid":27329,"level":50,"tid":"1001","msg":"query exception: Error: connect ETIMEDOUT 192.168.5.90:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)\n    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:126:14) {\n  errno: 'ETIMEDOUT',\n  code: 'ETIMEDOUT',\n  syscall: 'connect',\n  address: '192.168.5.90',\n  port: 5432\n}","time":"2021-08-23T09:11:39.798Z","v":0}
{"name":"testservice.common","hostname":"testserver","pid":27329,"level":50,"tid":"1001","msg":"errorInfo:  {\n  \"statusCode\": 500,\n  \"errorCode\": \"ZZ-11-112\",\n  \"errorDescription\": \"Database error.\"\n} \n actualErr:  undefined","time":"2021-08-23T09:11:39.798Z","v":0}
{"name":"testservice.query","hostname":"testserver","pid":27375,"level":50,"tid":"1002","msg":"query exception: Error: connect ETIMEDOUT 192.168.5.90:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)\n    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:126:14) {\n  errno: 'ETIMEDOUT',\n  code: 'ETIMEDOUT',\n  syscall: 'connect',\n  address: '192.168.5.90',\n  port: 5432\n}","time":"2021-08-23T09:11:39.834Z","v":0}

we use multi process, then we found that some process can connect to postgresql, but some keep meet ETIMEDOUT 

testserver:/var/log/service # netstat -nap|grep 8896|grep testservice
tcp        0      0 192.168.5.82:56933      192.168.5.90:5432       ESTABLISHED 27338/node testservice
tcp        0      0 192.168.5.82:56285      192.168.5.90:5432       ESTABLISHED 27350/node testservice
tcp        0      0 192.168.5.82:57057      192.168.5.90:5432       ESTABLISHED 27338/node testservice
testserver:/var/log/service # ps -ef|grep testservice
testusr  27061     1  2 17:09 ?        00:00:02 node testservice -n testservice
testusr  27329 27061  5 17:09 ?        00:00:05 node testservice -n testservice
testusr  27338 27061 13 17:09 ?        00:00:13 node testservice -n testservice
testusr  27350 27061 10 17:09 ?        00:00:10 node testservice -n testservice

**Comment by laorunsen** [comment]
version like this:
/test/node_modules/pg # cat package.json
{
  "name": "pg",
  "version": "7.18.2",
  "description": "PostgreSQL client - pure javascript & libpq with the same API",
  "keywords": [
    "database",
    "libpq",
    "pg",
    "postgre",
    "postgres",
    "postgresql",
    "rdbms"
  ],
  "homepage": "https://github.com/brianc/node-postgres",
  "repository": {
    "type": "git",
    "url": "git://github.com/brianc/node-postgres.git"
  },
  "author": "Brian Carlson <brian.m.carlson@gmail.com>",
  "main": "./lib",
  "dependencies": {
    "buffer-writer": "2.0.0",
    "packet-reader": "1.0.0",
    "pg-connection-string": "0.1.3",
    "pg-packet-stream": "^1.1.0",
    "pg-pool": "^2.0.10",
    "pg-types": "^2.1.0",
    "pgpass": "1.x",
    "semver": "4.3.2"
  },
  "devDependencies": {
    "async": "0.9.0",
    "bluebird": "3.5.2",
    "co": "4.6.0",
    "eslint": "^6.0.1",
    "eslint-config-standard": "^13.0.1",
    "eslint-plugin-import": "^2.18.1",
    "eslint-plugin-node": "^9.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.0",
    "pg-copy-streams": "0.3.0"
  },
  "minNativeVersion": "2.0.0",
  "scripts": {
    "test": "make test-all",
    "lint": "make lint"
  },
  "files": [
    "lib",
    "SPONSORS.md"
  ],
  "license": "MIT",
  "engines": {
    "node": ">= 4.5.0"
  },
  "gitHead": "29877530c6f7b5ebc0bf814e3a711b4b66e4d51a"
}
