### ISSUE TITLE
Need help for install ERROR

### ISSUE THREAD

**Issue by SaltFish001** [brianc/node-postgres#2610]
I'm work with WSL2 (Ubuntu 20.04), when  I want run 
```
 npm install pg pg-hstore
```
I got an Error:
```
error code 1
186 error path /root/projects/GLSD/InformationEntry/node_modules/libpq
187 error command failed
188 error command sh -c node-gyp rebuild
189 error gyp info it worked if it ends with ok
189 error gyp info using node-gyp@7.1.2
189 error gyp info using node@14.17.6 | linux | x64
189 error gyp info find Python using Python version 3.9.2 found at "/usr/local/bin/python3"
189 error gyp info spawn /usr/local/bin/python3
189 error gyp info spawn args [
189 error gyp info spawn args   '/root/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
189 error gyp info spawn args   'binding.gyp',
189 error gyp info spawn args   '-f',
189 error gyp info spawn args   'make',
189 error gyp info spawn args   '-I',
189 error gyp info spawn args   '/root/projects/GLSD/InformationEntry/node_modules/libpq/build/config.gypi',
189 error gyp info spawn args   '-I',
189 error gyp info spawn args   '/root/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
189 error gyp info spawn args   '-I',
189 error gyp info spawn args   '/root/.cache/node-gyp/14.17.6/include/node/common.gypi',
189 error gyp info spawn args   '-Dlibrary=shared_library',
189 error gyp info spawn args   '-Dvisibility=default',
189 error gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.17.6',
189 error gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp',
189 error gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.17.6/<(target_arch)/node.lib',
189 error gyp info spawn args   '-Dmodule_root_dir=/root/projects/GLSD/InformationEntry/node_modules/libpq',
189 error gyp info spawn args   '-Dnode_engine=v8',
189 error gyp info spawn args   '--depth=.',
189 error gyp info spawn args   '--no-parallel',
189 error gyp info spawn args   '--generator-output',
189 error gyp info spawn args   'build',
189 error gyp info spawn args   '-Goutput_dir=.'
189 error gyp info spawn args ]
189 error find: ‘/usr/pg*’: No such file or directory
189 error gyp: Call to 'which pg_config || find /usr/bin /usr/local/bin /usr/pg* /opt -executable -name pg_config -print -quit' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
189 error gyp ERR! configure error
189 error gyp ERR! stack Error: `gyp` failed with exit code: 1
189 error gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
189 error gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
189 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
189 error gyp ERR! System Linux 5.4.72-microsoft-standard-WSL2
189 error gyp ERR! command "/root/.nvm/versions/node/v14.17.6/bin/node" "/root/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
189 error gyp ERR! cwd /root/projects/GLSD/InformationEntry/node_modules/libpq
189 error gyp ERR! node -v v14.17.6
189 error gyp ERR! node-gyp -v v7.1.2
189 error gyp ERR! not ok
190 verbose exit 1
```

**Comment by brianc** [comment]
you need to figure out what's installing `libpq` - neither `pg` nor `pg-hstore` depends on `libpq` and that's what's failing to install.

**Comment by SaltFish001** [comment]
I got the reason. In the TaoBao registry ( https://registry.npm.taobao.org/) `pg` needs `libpq`.
