### ISSUE TITLE
Node-Postgres failing to run UPDATE queue.

### ISSUE THREAD

**Issue by hackermondev** [brianc/node-postgres#2624]
So I have this table on my database with some different columns & columns types but whenever I try to update a row in the table, node-postgres throw a weird error that isn't even from my code.

Here's is the code I'm using to create the table:

```js
await this.query(`CREATE TABLE IF NOT EXISTS ${constants.tables.orders} (
            ID TEXT PRIMARY KEY,
            owner_id TEXT NOT NULL,
            created_at timestamp NOT NULL,
            min_account_age integer,
            account_username varchar(20),
            account_avatar varchar(200),
            has_been_completed boolean NOT NULL,
            amount_of_bots_requested integer NOT NULL,
            bots text[]
        )`);
``` 
(And this code works perfect fine its just the other code that returns the error)

Here is the code I'm using to update the table:
```js
await this.db.query(
            `UPDATE ${constants.tables.orders} SET bots = $1 AND has_been_completed = $2 WHERE ID = $3`,
            [bots, true, orderData.id],
        );
```
And all the variables i'm putting are the correct types for the colum but I'm getting this error.

```js
/home/hackermon/e/node_modules/pg-protocol/dist/parser.js:287
        const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                 ^

error: column "bots" is of type text[] but expression is of type boolean
    at Parser.parseErrorMessage (/home/hackermon/e/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/hackermon/e/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/hackermon/e/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/home/hackermon/e/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23) {
  length: 191,
  severity: 'ERROR',
  code: '42804',
  detail: undefined,
  hint: 'You will need to rewrite or cast the expression.',
  position: '26',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '591',
  routine: 'transformAssignedExpr'
}
```

I have no idea what this is and it doesn't even look like it is coming from my code. 

@brianc 

### My Enviroment
- Node Version: v16.9.1
- Npm Version: 7.21.1
- Postgres Npm Version: ^8.7.1

**Comment by charmander** [comment]
You separate multiple updated columns in an `UPDATE` with a comma, not `AND`.
