### ISSUE TITLE
Cannot use `ssl: 'require'`

### ISSUE THREAD

**Issue by timja** [brianc/node-postgres#2659]
See https://github.com/brianc/node-postgres/issues/2406#issuecomment-849590132

(this used to work)

```
/usr/src/app/node_modules/pg/lib/connection.js:85
        if ('key' in self.ssl) {
                  ^

TypeError: Cannot use 'in' operator to search for 'key' in require
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:85:19)
    at Object.onceWrapper (events.js:520:26)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

Workaround: Set `PGSSLMODE` environment variable from https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#pg810

**Comment by charmander** [comment]
> (this used to work)

It used to not throw an error, but the `ssl` config option has never taken a string value. You should write `ssl: true` for that behaviour.

**Comment by timja** [comment]
It used to work at some point
