### ISSUE TITLE
AWS RDS password rotation with changing username

### ISSUE THREAD

**Issue by thijs** [brianc/node-postgres#2679]
The PR at https://github.com/brianc/node-postgres/pull/1926 solves part of my problem. In RDS I'm using password rotation with a secondary postgres user, which means that every rotation the username toggles between `username` and `username_clone`.

The dynamic password lookup function works, but in my case I need the same for the username, because with the rotation that will have changed as well.

Maybe the separate username and password should also be able to be provided through a credentials object, containing those both, that could be retrieved through a function?

Or am I missing an obvious way to solve this differently?

**Comment by thijs** [comment]
Should the current master checkout complete the test suite without errors?

I thought I might look into creating a pull request to implement this. However, if I follow the instructions under `Contributing`, my run of `yarn test` fails. Interestingly at the part that I'm interested in, namely the dynamic password function:

```
dynamic-password-tests.js
  Get password from a sync function FAILED!

AssertionError [ERR_ASSERTION]: Our password function should have been called
    at /home/thijs/code/node-postgres/packages/pg/test/integration/connection/dynamic-password-tests.js:26:12
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Should I be working from a different branch/tag?

**Comment by thijs** [comment]
Added pull request to solve this. See https://github.com/brianc/node-postgres/pull/2682

**Comment by thijs** [comment]
Is there anything (else) I need to do to get this PR applied? Except wait?
