### ISSUE TITLE
function lower(integer) does not exist

### ISSUE THREAD

**Issue by vineshraut** [brianc/node-postgres#2747]
i think while parsing the incoming data it tries to lower case the string but when data is Integer or number that case needs to be handle. basically it needs to avoid when data is number 
I am not sure but this could be one of the possiblity 

error error: function lower(integer) does not exist
    at Parser.parseErrorMessage (/home/ajency/vinesh/projects/GIT/dbs/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/ajency/vinesh/projectss/GIT/dbs/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/ajency/vinesh/projects/GIT/dbs/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/ajency/vinesh/projects/GIT/dbs/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
From previous event:
    at Client_PG._query (/home/ajency/vinesh/projects/GIT/dbs/node_modules/knex/lib/dialects/postgres/index.js:234:12)
    at Client_PG.query (/home/ajency/vinesh/projects/GIT/dbs/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/home/ajency/vinesh/projects/GIT/dbs/node_modules/knex/lib/runner.js:135:36)
    at /home/ajency/vinesh/projects/GIT/dbs/node_modules/knex/lib/runner.js:39:23
From previous event:
    at Runner.run (/home/ajency/vinesh/projects/GIT/dbs/node_modules/knex/lib/runner.js:25:16)
    at Builder.Target.then (/home/ajency/vinesh/projects/GIT/dbs/node_modules/knex/lib/interface.js:14:43)
    at processImmediate (internal/timers.js:461:21)

**Comment by vineshraut** [comment]
version:     "pg": "^8.7.3",

**Comment by boromisp** [comment]
This error comes from the database, not the driver. One of your queries is calling `lower()` on an integer.
Eg:
```sql
select lower(5);

ERROR:  function lower(integer) does not exist
LINE 1: select lower(5);
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by vineshraut** [comment]
@boromisp Thanks, have nice day..!
