### ISSUE TITLE
feature request: Allow raw strings as valid JSONs.

### ISSUE THREAD

**Issue by aviv-skillset** [brianc/node-postgres#2750]
According to [JSON specs](https://www.json.org/json-en.html), string is a valid JSON. Postgres also accepts string in json column. The package should allow this as well.
```js
error: invalid input syntax for type json
    at Parser.parseErrorMessage (DRIVE:\base_folder\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (DRIVE:\base_folder\node_modules\pg-protocol\dist\parser.js:126:29)     
    at Parser.parse (DRIVE:\base_folder\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (DRIVE:\base_folder\node_modules\pg-protocol\dist\index.js:11:42)        
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 155,
  severity: 'ERROR',
  code: '22P02',
  detail: 'Token "My Legit String" is invalid.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'JSON data, line 1: My Legit String',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'json.c',
  line: '1248',
  routine: 'report_invalid_token'
}
```

ping this issue if you want me to create PR and try to fix this myself

**Comment by charmander** [comment]
This isn’t possible to make work even if pg starts adding types to its parameters[^1], because the text serialization of `text` (what pg assumes you want when you pass a string) and `json` (/`jsonb`) is different. You need to pass `JSON.stringify(str)`. Arrays, numbers, and booleans have the same problem.

[^1]: the error message will be better, though.

**Comment by aviv-skillset** [comment]
isn't the library does `JSON.stringify` under the hood? because it accepts js objects which are not stringified.
so if I want to insert 
```js

const value = { validKey: 'string' };
pool.query({
    text: sql`INSERT INTO table_name( json_column )
        VALUES($1);
    `,
    values: [value.validKey]
});
```
I have to do:
```js
values: [JSON.stringify(value.validKey)]
```
?

**Comment by charmander** [comment]
Yes, JSON is the default for plain objects, so you can pass a plain object as a parameter without calling `JSON.stringify`. (It doesn’t hurt to call `JSON.stringify` unconditionally, though.)
