### ISSUE TITLE
ERR_INVALID_ARG_TYPE after upgrade from 7 to 8 using pg 11.15

### ISSUE THREAD

**Issue by Saver131** [brianc/node-postgres#2755]
Currently updating old app from node.js 10 to node.js 16, node-pg is also updated from 7 to 8. However, error below is shown when we use the new app with node.js 16 and node-pg 8 while the old app is fine. We are using pg 11.15.

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object
at new NodeError (node:internal/errors:372:5)
at Function.byteLength (node:buffer:735:11)
at Writer.addCString (/home/node/app/node_modules/pg-protocol/dist/buffer-writer.js:42:30)
at Object.startup (/home/node/app/node_modules/pg-protocol/dist/serializer.js:10:32)
at Connection.startup (/home/node/app/node_modules/pg/lib/connection.js:123:33)
at Connection.<anonymous> (/home/node/app/node_modules/pg/lib/client.js:126:11)
at Connection.emit (node:events:527:28)
at Connection.emit (node:domain:475:12)
at Socket.<anonymous> (/home/node/app/node_modules/pg/lib/connection.js:101:12)
at Object.onceWrapper (node:events:642:26)
at Socket.emit (node:events:527:28)
at Socket.emit (node:domain:475:12)
at addChunk (node:internal/streams/readable:315:12)
at readableAddChunk (node:internal/streams/readable:289:9)
at Socket.Readable.push (node:internal/streams/readable:228:10)
at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

Does anyone know how to resolve this issue?

Thanks in advance.

**Comment by charmander** [comment]
What does your pg configuration look like? It sounds like something’s an object that shouldn’t be.

Were you passing an unused key called `options`? pg 8.x supports `options`, and expects it to be a string. You should only pass supported options to pg in order to avoid name collisions in the future, because adding new options usually isn’t considered a (semver-major) breaking change.

**Comment by Saver131** [comment]
Thank you.
Looks like the options key that was passed to pg lib is the issue. We use sequelize with both mssql and pg and options key is for use with mssql. Everything is working correctly now.
