### ISSUE TITLE
How to get message raised in trigger exception?

### ISSUE THREAD

**Issue by GuiRitter** [brianc/node-postgres#2760]
Hi everyone.

First of all, many thanks for this project! For someone like me, who's not a fan of ORMs, this works perfectly.

But there are still a few details I need to sort out before it's fully working as I want it.

I've added a few triggers in my database that perform validations, and when the validation fails it does the following:

```sql
RAISE EXCEPTION 'My exception message.';
```

I've set up `pg` like this:

```javascript
const { Pool } = require('pg');

const pool = new Pool({
	connectionLimit: 10,
	host: process.env.DB_HOST,
	user: process.env.DB_USER,
	password: process.env.DB_PASSWORD,
	database: process.env.DB_DATABASE,
	port: process.env.DB_PORT,
})

export default pool;

export const postMethod = async (req, res) => {
	const { data } = req.body;
	const query = `bla bla bla`;
	try {
		const { rows } = await pool.query(query, [data]);
		return res.status(status.success).send(rows);
	} catch (error) {
		console.log(error);
		errorMessage.error = 'Unknown error.';
		return res.status(status.error).send(errorMessage);
	}
};
```

From that `console.log(error);`, I get:

```
error: error: My exception message.
    at Parser.parseErrorMessage (/home/guir/api/Bet1X2ManagerAPI/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/guir/api/Bet1X2ManagerAPI/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/guir/api/Bet1X2ManagerAPI/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/guir/api/Bet1X2ManagerAPI/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 193,
  severity: 'ERROR',
  code: 'P0001',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'função PL/pgSQL my_trigger() linha 7 em RAISE',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'pl_exec.c',
  line: '3841',
  routine: 'exec_stmt_raise'
}
```

However, I'm having trouble getting the `My exception message.` string to send to the front end. I tried `console.log({ keys: Object.keys(error), values: Object.values(error) });` but this is all I get:

```
{
keys: [
    'length',        'name',
    'severity',      'code',
    'detail',        'hint',
    'position',      'internalPosition',
    'internalQuery', 'where',
    'schema',        'table',
    'column',        'dataType',
    'constraint',    'file',
    'line',          'routine'
  ],
  values: [
    193,
    'error',
    'ERROR',
    'P0001',
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    'função PL/pgSQL my_trigger() linha 7 em RAISE',
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    'pl_exec.c',
    '3841',
    'exec_stmt_raise'
  ]
}
```

My only suspect is `name` because it's the only key not present in the first `console.log`, but `typeof error.name` is `string` and `error.name.constructor.name` is `String`. `error.constructor.name` is `DatabaseError` and that's what made me believe that this is the place to ask this question.

So, is it possible to get the exception message raised by the trigger?

Thanks in advance.

**Comment by boromisp** [comment]
The `DatabaseError` extends the built-in `Error` class, and passes the first constructor argument to the `Error` constructor:
https://github.com/brianc/node-postgres/blob/6121bd3bb0e0e8ef8ec8ad5d02f59fef86b2f992/packages/pg-protocol/src/messages.ts#L97-L117

You should be able to access it as `error.message` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error).
