### ISSUE TITLE
Cockroach: Cannot stream large datasets using QueryStream

### ISSUE THREAD

**Issue by markddrake** [brianc/node-postgres#2767]
First off, I fully understand you do not "Support" Cockroach.

However I was wondering if there is any workaround for using CopyStream with large data sets and Cockroach.

The following t/c works perfectly with Postgres 14.

```
import pg                             from 'pg';
const {Client,Pool} = pg;
import QueryStream                    from 'pg-query-stream'
import {
  Transform
}                                     from 'stream';

import {
  pipeline
}                                     from 'stream/promises';

const props = {
          user: 'postgres',
          host: 'yadamu-db2',
          database: 'yadamu',
          password: 'oracle',
          port: 5432
}

class t extends Transform {

  constructor() {
    super({objectMode: true });  
  }
  
  async doTransform(data) {
    return JSON.stringify(data)
  }

  _transform(data,enc,callback) {
    this.doTransform(data).then((row) => { this.push(row);callback()}).catch((e) => { callback(e)})
  }

}

async function main() {
              process.on('unhandledRejection', (err, p) => {
                            console.log(err);
                            process.exit()
                          })

                      const pgClient = new Client(props);
                      console.log('connecting')
                      await pgClient.connect();
                      console.log('connected')
                      const queryStream = new QueryStream(`select * from INFORMATION_SCHEMA.COLUMNS`,[],{rowMode : "array"})
                      const inputStream = await pgClient.query(queryStream)   					  
					  await pipeline(inputStream,new t,process.stdout,{end:false})
					  await pgClient.end();
                      console.log('disconnected')

}

main().then(() => {console.log('DONE')}).catch((e) => {console.log(e)});
```

Howerver it fails when run against cockroach

```
C:\Development\YADAMU>node src\scratch\postgres\pgTestStream.js
connecting
connected
error: unimplemented: multiple active portals not supported
    at Parser.parseErrorMessage (C:\Development\YADAMU\src\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (C:\Development\YADAMU\src\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Development\YADAMU\src\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Development\YADAMU\src\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 285,
  severity: 'ERROR',
  code: '0A000',
  detail: 'cannot perform operation sql.Flush while a different portal is open',
  hint: 'You have attempted to use a feature that is not yet implemented.\n' +
    'See: https://go.crdb.dev/issue-v/40195/v22.1',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'distsql_running.go',
  line: '1181',
  routine: 'init'
}
```

Cockroach clearly state that  'multiple active portals not supported' in their documentation, however as far as I can tell I am only running a single query in this testcase.

**Comment by markddrake** [comment]
https://github.com/cockroachdb/cockroach/issues/40195

**Comment by markddrake** [comment]
Looks like the Cockroach  guys think they can address this

https://github.com/cockroachdb/cockroach/issues/83613

**Comment by brianc** [comment]
yeah if there's a bug w/ cockroach the biggest issue is i don't really have tests set up for it & haven't really ventured to do that...I could see about getting it set up in CI to at least test the basics? Though I'm pretty sure a decent chunk of the tests here would fail against it since they do some pretty postgres specific things (some of them, like testing configs and specific errors and stuff) so i'd probably have to go through & turn various tests off.  Good to know they can fix this one on their end! 😅

**Comment by markddrake** [comment]
FWIW I was able to get their docker image up and running in about 5 mins.
