### ISSUE TITLE
pg-protocol throws an uncatchable error when it loses the connection to PostgreSQL server via TLS

### ISSUE THREAD

**Issue by yule-cao** [brianc/node-postgres#2820]
When the PostgreSQL server gets terminated, an uncatchable error is thrown from pg-protocol with following message
```
error: terminating connection due to administrator command
    at Parser.parseErrorMessage (/xxx/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/xxx/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/xxx/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/xxx/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

It seems that the errors in the on stream data listener here is not handled properly?
https://github.com/brianc/node-postgres/blob/9a95ee719b181341d381702a4404827ca906b036/packages/pg-protocol/src/index.ts#L7

**Comment by charmander** [comment]
https://github.com/brianc/node-postgres/blob/9a95ee719b181341d381702a4404827ca906b036/packages/pg/lib/connection.js#L47-L62

It’s not uncatchable. You need to add an `error` listener to any pools and clients you use.

**Comment by charmander** [comment]
Canonical issue for improving error ergonomics: https://github.com/brianc/node-postgres/issues/2439#issuecomment-757548659

**Comment by yule-cao** [comment]
Hi @charmander 

I'm pretty sure I've added the `error` listener on the pool as follows
```
  pool.on('error', (err, client) => {
    logger.error(`Unexpected error on idle client ${client}: ${err}`);
  });
```
and, all queries are emitted though `pool.query`. But, still, the error was not caught and the app crashed.

Do you mean the error thrown from the `data` listener should be caught by the `error` listener? I've tested with the following example and it fails to catch the error.
```
const stream = Readable.from(['hi pg']);
stream.on('error', () => {
  console.log('error caught');
});
stream.on('data', () => {
  throw new Error('some error');
});
```
It produces the error:
```
$ node main.js
file:///xxx/main.js:8
  throw new Error('some error');
  ^

Error: some error
    at Readable.<anonymous> (file:///home/ecuayox/workspace/cnom/cnom/server/main.js:8:9)
    at Readable.emit (node:events:527:28)
    at Readable.read (node:internal/streams/readable:527:10)
    at flow (node:internal/streams/readable:1011:34)
    at resume_ (node:internal/streams/readable:992:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by yule-cao** [comment]
It needs to catch possible errors from inside the `data` listener and emit them to `error` to make it work.
```
const stream = Readable.from(['hi pg']);
stream.on('error', () => {
  console.log('error caught');
});
stream.on('data', () => {
  try {
    throw new Error('some error');
  } catch (err) {
    stream.emit('error', err);
  }
});
```
```
$ node server/main.js
error caught
```

So I think the error happened in `parser.parse` here is uncatchable?
https://github.com/brianc/node-postgres/blob/9a95ee719b181341d381702a4404827ca906b036/packages/pg-protocol/src/index.ts#L7

**Comment by yule-cao** [comment]
> Canonical issue for improving error ergonomics: [#2439 (comment)](https://github.com/brianc/node-postgres/issues/2439#issuecomment-757548659)

Oh, sorry that I missed this information.

I'll try again with `error` listeners added to all the connected clients.
