### ISSUE TITLE
parser.ts - apparently unexpected error message format leading to reporting "syntax error at end of input"

### ISSUE THREAD

**Issue by leegee** [brianc/node-postgres#2922]
Re: pg-protocol version 1.6.0 on Node v18.4.0,

I'm getting errors when running a `client.query`, errors I wasn't getting a couple of hours ago: the SQL remains unchanged, the DB scheme is going through many changes. 

```
error: syntax error at end of input
    at Parser.parseErrorMessage (S:\\src\\xxx\
ode_modules\\pg-protocol\\src\\parser.ts:369:69)
    at Parser.handlePacket (S:\\src\\xxx\
ode_modules\\pg-protocol\\src\\parser.ts:188:21)
    at Parser.parse (S:\\src\\xxx\
ode_modules\\pg-protocol\\src\\parser.ts:103:30)
    at Socket.<anonymous> (S:\\src\\xxx\
ode_modules\\pg-protocol\\src\\index.ts:7:48)
    at Socket.emit (node:events:537:28)
    at Socket.emit (node:domain:482:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 91,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '73',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1172',
  routine: 'scanner_yyerror'
}
```

The first part of the stack trace points to the below line in `node_modules\pg-protocol\src\parser.ts`, in `parseErrorMessage`:

```
        const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new 
```

To try and get some insight, I replaced the above with the below:

```
         let message;
        try {
            message =
                name === 'notice' ? new NoticeMessage( length, messageValue ) : new DatabaseError( messageValue, length, name )
        } catch ( e ) {
            console.error( { name, messageValue } );
            throw ( e );
        }
```

Below is the output. Any idea what's going on? 

The column in question may well not exist, btw, but the SQL executed was `'ALTER TABLE public.dmz ADD COLUMN dmzid VARCHAR( 128 )'` ...

Just wondering why the program dies rather than errors nicely as elsewhere.

```
{ name: 'error', messageValue: 'column "dt_name" does not exist' }

S:\src\xxx\node_modules\pg-protocol\src\parser.ts:373
    } catch (e) {
                             ^
ReferenceError: DatabaseError is not defined
    at Parser.parseErrorMessage (S:\src\xxx\node_modules\pg-protocol\src\parser.ts:373:30)
    at Parser.handlePacket (S:\src\xxx\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (S:\src\xxx\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (S:\src\xxx\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:537:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by leegee** [comment]
Also found on stderr: `ReferenceError: NoticeMessage is not defined`

```
[10:33:52.261] WARN (12224): {"action":"TESTDATA-STDERR","stderr":"{\n  name: 'notice',\n  messageValue: 'table \"dmz\" does not exist, skipping'\n}\n"}
[10:33:52.270] WARN (12224): {"action":"TESTDATA-STDERR","stderr":"S:\\src\\xxx-foresite\\node_modules\\pg-protocol\\src\\parser.ts:373\n      message =\n                             ^\n"}
[10:33:52.270] WARN (12224): {"action":"TESTDATA-STDERR","stderr":"ReferenceError: NoticeMessage is not defined\n    at Parser.parseErrorMessage (S:\\src\\xxx-foresite\\node_modules\\pg-protocol\\src\\parser.ts:373:30)\n    at Parser.handlePacket (S:\\src\\xxx-foresite\\node_modules\\pg-protocol\\src\\parser.ts:190:21)\n    at Parser.parse (S:\\src\\xxx-foresite\\node_modules\\pg-protocol\\src\\parser.ts:103:30)\n    at Socket.<anonymous> (S:\\src\\xxx-foresite\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:537:28)\n    at Socket.emit (node:domain:482:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Socket.Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)\n"}
```

**Comment by leegee** [comment]
Re-installed everything, re-started the DB, problems vanish. Not good, but no longer an issue here.
