### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object

### ISSUE THREAD

**Issue by Jobin-S** [brianc/node-postgres#2960]
node:buffer:784
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object
    at new NodeError (node:internal/errors:399:5)
    at Function.byteLength (node:buffer:784:11)
    at Writer.addCString (/Users/jobinselvanose/Documents/projects/quantorix/tradephlo/admin-backend/node_modules/pg-protocol/dist/buffer-writer.js:42:30)
    at Object.startup (/Users/jobinselvanose/Documents/projects/quantorix/tradephlo/admin-backend/node_modules/pg-protocol/dist/serializer.js:10:32)
    at Connection.startup (/Users/jobinselvanose/Documents/projects/quantorix/tradephlo/admin-backend/node_modules/pg/lib/connection.js:125:33)
    at Connection.<anonymous> (/Users/jobinselvanose/Documents/projects/quantorix/tradephlo/admin-backend/node_modules/pg/lib/client.js:121:13)
    at Connection.emit (node:events:512:28)
    at Socket.<anonymous> (/Users/jobinselvanose/Documents/projects/quantorix/tradephlo/admin-backend/node_modules/pg/lib/connection.js:49:12)
    at Object.onceWrapper (node:events:626:28)
    at Socket.emit (node:events:524:35) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v19.8.1

**Comment by Anisha12311** [comment]
Same issue on  Node.js v19.8.1

**Comment by charmander** [comment]
Please provide enough code to reproduce the issue.

**Comment by Jobin-S** [comment]
The issue was due to wrong env mapping. Thanks for the supports @charmander
