### ISSUE TITLE
Question: Error position v. length

### ISSUE THREAD

**Issue by jcalfee** [brianc/node-postgres#3000]
What is the difference between the `position` and the `length` a thrown error?  Position is very accurate, if I get a position I can always pin-point the location of the error by using it as an offset in the original query.  In some cases though, even with the same type of error (I'm not sure really), the position is `undefined` and I get a `length` instead like in the error below.  Is there anything I can do make use of the length or something I can do to help guarantee I get a position back?

```js
error: relation "my_table" does not exist
    at Parser.parseErrorMessage (/app/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 105,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'namespace.c',
  line: '433',
  routine: 'RangeVarGetRelidExtended'
}
```

**Comment by charmander** [comment]
`length` is the number of bytes in the PostgreSQL-protocol packet containing the error. It isn’t part of the error information (and probably shouldn’t even be exposed, but can’t be removed without a breaking change).

If you’re still experiencing missing error information that isn’t missing when using other clients (like the psql CLI), please open a bug report with all the usual reproduction details.
