### ISSUE TITLE
INSERT INTO fails during import of about 7000 rows

### ISSUE THREAD

**Issue by dancesWithCycles** [brianc/node-postgres#3028]
Hi folks,
Thank you so much for providing and maintaining this repository. I would like to share a behavior of pg.js that I can not explain.

This `query` function

```
const { Pool } = require('pg');
const config = require('../config');
const pool = new Pool(config.db);

async function query(query, params) {
    const {rows, fields} = await pool.query(query, params);

    return rows;
}
```

is used in this ```create``` function.

```
const debug=require('debug')('debug');
const db = require('./db');

async function create(stop) {

    const query = `INSERT INTO tdb_stops (active, lon, location, lat, stop_long_name, stop_name, stop_name_extern, fare_zone_1, valid_from, valid_until, last_modified) VALUES (` + stop.active + `, '` + stop.lon + `', '` + stop.location + `', '`+ stop.lat + `', '` + stop.stop_long_name + `', '` + stop.stop_name + `', '` + stop.stop_name_extern + `', '` + stop.fare_zone_1 + `', CURRENT_TIMESTAMP, DEFAULT, DEFAULT);`;

    debug('stops-create:create() query: ' + query);
    const rsp = await db.query(query);
};
```

After inserting `2083` stop rows my logging stops at this position

```
  debug stops-create:create() query: INSERT INTO tdb_stops (active, lon, location, lat, stop_long_name, stop_name, stop_name_extern, fare_zone_1, valid_from, valid_until, last_modified) VALUES (true, '9,278445', 'Zeven Vitus-Platz', '53,2908', 'Zeven Vitus-Platz', 'Zeven Vitus-Platz', 'de:03357:9093956', '345', CURRENT_TIMESTAMP, DEFAULT, DEFAULT); +0ms
  debug stops-create:create() query: INSERT INTO tdb_stops (active, lon, location, lat, stop_long_name, stop_name, stop_name_extern, fare_zone_1, valid_from, valid_until, last_modified) VALUES (true, '9,292194', 'Zeven Zum Hochkamp', '53,276182', 'Zeven Zum Hochkamp', 'Zeven Zum Hochkamp', 'de:03357:99888', '345', CURRENT_TIMESTAMP, DEFAULT, DEFAULT); +0ms
  debug stops-create:create() query: INSERT INTO tdb_stops (active, lon, location, lat, stop_long_name, stop_name, stop_name_extern, fare_zone_1, valid_from, valid_until, last_modified) VALUES (true, '9,320183', 'Zeven-Wistedt', '53,259104', 'Zeven-Wistedt', 'Zeven-Wistedt', 'de:03357:100656', '345', CURRENT_TIMESTAMP, DEFAULT, DEFAULT); +0ms
```

complaining with this error.

```
/home/begerad/git/vbn/data/data-api/node_modules/pg-protocol/dist/parser.js:287
        const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                 ^

error: Syntaxfehler bei »n«
    at Parser.parseErrorMessage (/home/begerad/git/vbn/data/data-api/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/begerad/git/vbn/data/data-api/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/begerad/git/vbn/data/data-api/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/begerad/git/vbn/data/data-api/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 87,
  severity: 'FEHLER',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '196',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1133',
  routine: 'scanner_yyerror'
}
```

Any idea what happend? There are about 5000 stop row inserts to follow. Appreciate!

**Comment by charmander** [comment]
Probably №2084 is showing you that you have an SQL injection vulnerability. Use parameterized queries, always.
