### ISSUE TITLE
`yarn lint` fails

### ISSUE THREAD

**Issue by alxndrsn** [brianc/node-postgres#3076]
Commit: b1a8947738ce0af004cb926f79829bb2abc64aa6 (current `master`)

Running `yarn lint` fails:

```
Oops! Something went wrong! :(                                                  
                                                                                   
ESLint: 7.11.0                                                                     
                                                                                   
Error: Cannot read config file: /work/node-postgres/node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: /work/node-postgres/.eslintrc                                  
    at Object.<anonymous> (/work/node-postgres/node_modules/eslint-config-prettier/@typescript-eslint.js:1:69)
    at Module._compile (/work/node-postgres/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)           
    at Module.load (node:internal/modules/cjs/loader:1119:32)                      
    at Module._load (node:internal/modules/cjs/loader:960:12)                      
    at Module.require (node:internal/modules/cjs/loader:1143:19)                   
    at module.exports (/work/node-postgres/node_modules/import-fresh/index.js:31:59)
    at loadJSConfigFile (/work/node-postgres/node_modules/eslint/lib/cli-engine/config-array-factory.js:230:16)
    at loadConfigFile (/work/node-postgres/node_modules/eslint/lib/cli-engine/config-array-factory.js:314:20)
    at ConfigArrayFactory._loadConfigData (/work/node-postgres/node_modules/eslint/lib/cli-engine/config-array-factory.js:606:42)
error Command failed with exit code 2.                                          
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by brianc** [comment]
this is fixed now thanks to you! ❤️
