### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'handleRowDescription')

### ISSUE THREAD

**Issue by doug65536** [brianc/node-postgres#3082]
I can't even `SELECT 1;`

     Uncaught TypeError: Cannot read properties of undefined (reading 'handleRowDescription')
      at Client._handleRowDescription (node_modules/pg/lib/client.js:362:22)
      at Connection.emit (node:events:517:28)
      at /home/doug/code/pcsbox/pcsbox/node_modules/pg/lib/connection.js:117:12
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:40:17)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:335:12)
      at readableAddChunk (node:internal/streams/readable:308:9)
      at Readable.push (node:internal/streams/readable:245:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

```
doug@doug-dtA:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
doug@doug-dtA:~$ uname -r
6.2.0-35-generic
doug@doug-dtA:~$ pg_config --version
PostgreSQL 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
doug@doug-dtA:~$ 
```

```
  dependencies": {
    "compression": "^1.7.4",
    "express": "^4.18.1",
    "mysql": "^2.18.1",
    "nodemailer": "^6.9.6",
    "passport": "^0.6.0",
    "passport-google-oauth": "^2.0.0",
    "pg": "^8.11.3",
    "pg-cursor": "^2.10.3"
  },
  "devDependencies": {
    "@types/compression": "^1.7.3",
    "@types/mysql": "^2.15.22",
    "mocha": "^10.2.0",
    "nodemon": "^3.0.1"
  }
```

It crashes here:

```
  _handleRowDescription(msg) {
    // delegate rowDescription to active query
    this.activeQuery.handleRowDescription(msg)
  }

```

...because `this.activeQuery` is undefined.

It is green:

```
doug@doug-dtA:~/code/pcsbox/pcsbox$ systemctl status postgresql
● postgresql.service - PostgreSQL RDBMS
     Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor pr>
     Active: active (exited) since Sat 2023-10-21 09:09:54 EDT; 1h 42min ago
    Process: 143424 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 143424 (code=exited, status=0/SUCCESS)
        CPU: 1ms

Oct 21 09:09:54 doug-dtA systemd[1]: Starting PostgreSQL RDBMS...
Oct 21 09:09:54 doug-dtA systemd[1]: Finished PostgreSQL RDBMS.
```

I create the DB with this script:

```
#!/bin/bash

if [[ -z $1 || -z $2 || -z $3 ]]; then
	echo Usage: "$0" username password database
	exit 1
fi

cd /tmp || exit

username=$1
password=$2
database=$3
echo "username=$username"
echo "password=$password"
echo "database=$database"

declare -a postgres_cmds=(
	"CREATE ROLE \"$username\" WITH LOGIN PASSWORD '$password';"
	"ALTER ROLE \"$username\" CREATEDB;"
	"CREATE DATABASE $database OWNER = '$username';"
	"\\c \"$database\""$'\n'"DROP SCHEMA \"public\" CASCADE;"
	"\\c \"$database\""$'\n'"CREATE SCHEMA \"public\";"
	"\\c \"$database\""$'\n'"GRANT ALL ON ALL TABLES IN SCHEMA \"public\" TO \"$username\";"
	"\\c \"$database\""$'\n'"GRANT ALL ON DATABASE \"$database\" TO \"$username\";"
	"\\c \"$database\""$'\n'"GRANT USAGE,CREATE ON SCHEMA \"public\" TO \"$username\";"
)
declare -a user_cmds=(
	"\\c $database"$'\n'"CREATE TABLE \"public\".\"auth_tenant\" (
		\"id\" BIGSERIAL PRIMARY KEY NOT NULL,
		\"name\" VARCHAR(255) NOT NULL
	);"
	"CREATE TABLE \"public\".\"auth_user\" (
		\"id\" BIGSERIAL PRIMARY KEY NOT NULL,
		\"tenantid\" BIGINT NOT NULL,
		\"password_salt\" CHAR(64) NOT NULL,
		\"password_hash\" CHAR(128) NOT NULL,
		\"password_expire\" BIGINT NOT NULL,
		\"email\" VARCHAR(255) NOT NULL,
		\"email_verified\" BOOLEAN NOT NULL,
		UNIQUE (\"tenantid\", \"email\")
	);"
	"CREATE INDEX \"idx_auth_user_expire\"
		ON \"public\".\"auth_user\" (\"password_expire\");"
	"CREATE TABLE \"public\".\"auth_session\" (
		\"id\" BIGSERIAL PRIMARY KEY NOT NULL,
		\"userid\" BIGINT NOT NULL,
		\"token\" CHAR(64) NOT NULL,
		\"expiry\" BIGINT NOT NULL
	);"
	"CREATE TABLE \"public\".\"auth_access\" (
		\"id\" BIGSERIAL PRIMARY KEY NOT NULL,
		\"sessionid\" BIGINT NOT NULL,
		\"token\" CHAR(64) NOT NULL,
		\"expiry\" BIGINT NOT NULL,
		\"type\" CHAR(1) NOT NULL	
	);"
	# The null tenant is the public tenant
	"INSERT INTO \"public\".\"auth_tenant\" ( id, name )
	 VALUES ( 0, 'public' );"
)

# Run the postgres command list,
# then the "user" commands as the specified user
for user in postgres user; do
	useduser=postgres
	useddb=postgres
	[[ $user != "postgres" ]] && useduser=$username
	[[ $user != "postgres" ]] && useddb=$database
	cmdvar="${user}_cmds[@]"
	for cmd in "${!cmdvar}"; do
		echo -ne 'Executing \e[1m'
		cat < <(echo "$cmd")
		echo -e '\e[0m'
		sudo -u "$useduser" psql -U "$useduser" \
			-d "$useddb" < <(echo "$cmd")
		echo '--------------------'
	done
done

```

And I invoke the above as 'doug' (my username):

```
./create_dbs doug 'pepsi crystal' pcsbox
```

Which produces

```
doug@doug-dtA:~/code/pcsbox/pcsbox$ ./create_dbs doug 'pepsi crystal' pcsbox
username=doug
password=pepsi crystal
database=pcsbox
Executing CREATE ROLE "doug" WITH LOGIN PASSWORD 'pepsi crystal';

[sudo] password for doug: 
ERROR:  role "doug" already exists
--------------------
Executing ALTER ROLE "doug" CREATEDB;

ALTER ROLE
--------------------
Executing CREATE DATABASE pcsbox OWNER = 'doug';

ERROR:  database "pcsbox" already exists
--------------------
Executing \c "pcsbox"
DROP SCHEMA "public" CASCADE;

You are now connected to database "pcsbox" as user "postgres".
NOTICE:  drop cascades to 4 other objects
DETAIL:  drop cascades to table auth_tenant
drop cascades to table auth_user
drop cascades to table auth_session
drop cascades to table auth_access
DROP SCHEMA
--------------------
Executing \c "pcsbox"
CREATE SCHEMA "public";

You are now connected to database "pcsbox" as user "postgres".
CREATE SCHEMA
--------------------
Executing \c "pcsbox"
GRANT ALL ON ALL TABLES IN SCHEMA "public" TO "doug";

You are now connected to database "pcsbox" as user "postgres".
GRANT
--------------------
Executing \c "pcsbox"
GRANT ALL ON DATABASE "pcsbox" TO "doug";

You are now connected to database "pcsbox" as user "postgres".
GRANT
--------------------
Executing \c "pcsbox"
GRANT USAGE,CREATE ON SCHEMA "public" TO "doug";

You are now connected to database "pcsbox" as user "postgres".
GRANT
--------------------
Executing \c pcsbox
CREATE TABLE "public"."auth_tenant" (
                "id" BIGSERIAL PRIMARY KEY NOT NULL,
                "name" VARCHAR(255) NOT NULL
        );

You are now connected to database "pcsbox" as user "doug".
CREATE TABLE
--------------------
Executing CREATE TABLE "public"."auth_user" (
                "id" BIGSERIAL PRIMARY KEY NOT NULL,
                "tenantid" BIGINT NOT NULL,
                "password_salt" CHAR(64) NOT NULL,
                "password_hash" CHAR(128) NOT NULL,
                "password_expire" BIGINT NOT NULL,
                "email" VARCHAR(255) NOT NULL,
                "email_verified" BOOLEAN NOT NULL,
                UNIQUE ("tenantid", "email")
        );

CREATE TABLE
--------------------
Executing CREATE INDEX "idx_auth_user_expire"
                ON "public"."auth_user" ("password_expire");

CREATE INDEX
--------------------
Executing CREATE TABLE "public"."auth_session" (
                "id" BIGSERIAL PRIMARY KEY NOT NULL,
                "userid" BIGINT NOT NULL,
                "token" CHAR(64) NOT NULL,
                "expiry" BIGINT NOT NULL
        );

CREATE TABLE
--------------------
Executing CREATE TABLE "public"."auth_access" (
                "id" BIGSERIAL PRIMARY KEY NOT NULL,
                "sessionid" BIGINT NOT NULL,
                "token" CHAR(64) NOT NULL,
                "expiry" BIGINT NOT NULL,
                "type" CHAR(1) NOT NULL
        );

CREATE TABLE
--------------------
Executing INSERT INTO "public"."auth_tenant" ( id, name )
         VALUES ( 0, 'public' );

INSERT 0 1
--------------------
doug@doug-dtA:~/code/pcsbox/pcsbox$ 
```

This test crashes

```
const { Pool } = require('pg');

describe('sanity', () => {
    it('should work in the slightest', () => {
        let pool = new Pool({
            user: 'doug',
            host: 'localhost',
            database: 'pcsbox',
            password: 'pepsi crystal',
            port: 5432
        });
        let connPromise = pool.connect();
        return connPromise.then(({connection, release}) => {
            return new Promise((resolve, reject) => {
                connection.query('SELECT 1;', [], (err, result) => {
                    assert.equal('worked!', 'worked!');
                    !err ? resolve(result) : reject(err);
                });
            }).finally(release);
        }).catch((err) => {
            assert.equal('worked', 'nope');            
        });
    });
});
```

...with:

```
  1) sanity
       should work in the slightest:
     Uncaught TypeError: Cannot read properties of undefined (reading 'handleRowDescription')
      at Client._handleRowDescription (node_modules/pg/lib/client.js:362:22)
      at Connection.emit (node:events:517:28)
      at /home/doug/code/pcsbox/pcsbox/node_modules/pg/lib/connection.js:117:12
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:40:17)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:335:12)
      at readableAddChunk (node:internal/streams/readable:308:9)
      at Readable.push (node:internal/streams/readable:245:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

The tests run as 'doug' (my username).

```
doug@doug-dtA:~/code/pcsbox/pcsbox$ node --version
v18.18.0
```

```
doug@doug-dtA:~/code/pcsbox/pcsbox$ psql -d pcsbox
psql (14.9 (Ubuntu 14.9-0ubuntu0.22.04.1))
Type "help" for help.

pcsbox=> \dt
           List of relations
 Schema |     Name     | Type  | Owner 
--------+--------------+-------+-------
 public | auth_access  | table | doug
 public | auth_session | table | doug
 public | auth_tenant  | table | doug
 public | auth_user    | table | doug
(4 rows)

pcsbox=> select 1;
 ?column? 
----------
        1
(1 row)

pcsbox=> 
```

**Comment by doug65536** [comment]
Then I thought you wouldn't let me get away with the role and db existing, so:

```
doug@doug-dtA:~/code/pcsbox/pcsbox$ sudo -u postgres psql -d postgres
[sudo] password for doug: 
could not change directory to "/home/doug/code/pcsbox/pcsbox": Permission denied
psql (14.9 (Ubuntu 14.9-0ubuntu0.22.04.1))
Type "help" for help.

postgres=# drop schema public;
ERROR:  cannot drop schema public because other objects depend on it
DETAIL:  table auth_access depends on schema public
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
postgres=# drop schema public cascade;
NOTICE:  drop cascades to table auth_access
DROP SCHEMA
postgres=# \dt
Did not find any relations.
postgres=# \d
Did not find any relations.
postgres=# drop role doug;
ERROR:  role "doug" cannot be dropped because some objects depend on it
DETAIL:  owner of database pcsbox
9 objects in database pcsbox
postgres=# \c pcsbox
You are now connected to database "pcsbox" as user "postgres".
pcsbox=# drop schema public;
ERROR:  cannot drop schema public because other objects depend on it
DETAIL:  table auth_tenant depends on schema public
table auth_user depends on schema public
table auth_session depends on schema public
table auth_access depends on schema public
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
pcsbox=# drop schema public cascade;
NOTICE:  drop cascades to 4 other objects
DETAIL:  drop cascades to table auth_tenant
drop cascades to table auth_user
drop cascades to table auth_session
drop cascades to table auth_access
DROP SCHEMA
pcsbox=# \c pcsbox;
You are now connected to database "pcsbox" as user "postgres".
pcsbox=# drop role doug;
ERROR:  role "doug" cannot be dropped because some objects depend on it
DETAIL:  owner of database pcsbox
pcsbox=# drop database pcsbox;
ERROR:  cannot drop the currently open database
pcsbox=# \c postgres;
You are now connected to database "postgres" as user "postgres".
postgres=# drop database pcsbox;
ERROR:  database "pcsbox" is being accessed by other users
DETAIL:  There are 3 other sessions using the database.
postgres=# SELECT * FROM pg_stat_activity WHERE datname = 'pcsbox';
postgres=# SELECT pid FROM pg_stat_activity WHERE datname = 'pcsbox';
  pid   
--------
 201802
 202461
 202462
(3 rows)

postgres=# select pg_terminate_backend(201802);
 pg_terminate_backend 
----------------------
 t
(1 row)

postgres=# select pg_terminate_backend(202461);
WARNING:  PID 202461 is not a PostgreSQL server process
 pg_terminate_backend 
----------------------
 f
(1 row)

postgres=# SELECT pid FROM pg_stat_activity WHERE datname = 'pcsbox';
 pid 
-----
(0 rows)

postgres=# SELECT * FROM pg_stat_activity WHERE datname = 'pcsbox';^C
postgres=# drop database pcsbox;
DROP DATABASE
postgres=# \dt
Did not find any relations.
postgres=# drop role doug
postgres-# 
postgres-# ;
DROP ROLE
postgres=# 
\q
doug@doug-dtA:~/code/pcsbox/pcsbox$ ./create_dbs doug 'pepsi crystal' pcsbox
username=doug
password=pepsi crystal
database=pcsbox
Executing CREATE ROLE "doug" WITH LOGIN PASSWORD 'pepsi crystal';

CREATE ROLE
--------------------
Executing ALTER ROLE "doug" CREATEDB;

ALTER ROLE
--------------------
Executing CREATE DATABASE pcsbox OWNER = 'doug';

CREATE DATABASE
--------------------
Executing \c "pcsbox"
DROP SCHEMA "public" CASCADE;

You are now connected to database "pcsbox" as user "postgres".
DROP SCHEMA
--------------------
Executing \c "pcsbox"
CREATE SCHEMA "public";

You are now connected to database "pcsbox" as user "postgres".
CREATE SCHEMA
--------------------
Executing \c "pcsbox"
GRANT ALL ON ALL TABLES IN SCHEMA "public" TO "doug";

You are now connected to database "pcsbox" as user "postgres".
GRANT
--------------------
Executing \c "pcsbox"
GRANT ALL ON DATABASE "pcsbox" TO "doug";

You are now connected to database "pcsbox" as user "postgres".
GRANT
--------------------
Executing \c "pcsbox"
GRANT USAGE,CREATE ON SCHEMA "public" TO "doug";

You are now connected to database "pcsbox" as user "postgres".
GRANT
--------------------
Executing \c pcsbox
CREATE TABLE "public"."auth_tenant" (
                "id" BIGSERIAL PRIMARY KEY NOT NULL,
                "name" VARCHAR(255) NOT NULL
        );

You are now connected to database "pcsbox" as user "doug".
CREATE TABLE
--------------------
Executing CREATE TABLE "public"."auth_user" (
                "id" BIGSERIAL PRIMARY KEY NOT NULL,
                "tenantid" BIGINT NOT NULL,
                "password_salt" CHAR(64) NOT NULL,
                "password_hash" CHAR(128) NOT NULL,
                "password_expire" BIGINT NOT NULL,
                "email" VARCHAR(255) NOT NULL,
                "email_verified" BOOLEAN NOT NULL,
                UNIQUE ("tenantid", "email")
        );

CREATE TABLE
--------------------
Executing CREATE INDEX "idx_auth_user_expire"
                ON "public"."auth_user" ("password_expire");

CREATE INDEX
--------------------
Executing CREATE TABLE "public"."auth_session" (
                "id" BIGSERIAL PRIMARY KEY NOT NULL,
                "userid" BIGINT NOT NULL,
                "token" CHAR(64) NOT NULL,
                "expiry" BIGINT NOT NULL
        );

CREATE TABLE
--------------------
Executing CREATE TABLE "public"."auth_access" (
                "id" BIGSERIAL PRIMARY KEY NOT NULL,
                "sessionid" BIGINT NOT NULL,
                "token" CHAR(64) NOT NULL,
                "expiry" BIGINT NOT NULL,
                "type" CHAR(1) NOT NULL
        );

CREATE TABLE
--------------------
Executing INSERT INTO "public"."auth_tenant" ( id, name )
         VALUES ( 0, 'public' );

INSERT 0 1
--------------------

```

**Comment by sehrope** [comment]
You're referencing the internal `connection` of the client when you should be interacting with the client itself:

```
        let connPromise = pool.connect();
        return connPromise.then(({connection, release}) => {  // <== THIS IS WRONG
            return new Promise((resolve, reject) => {
                connection.query('SELECT 1;', [], (err, result) => { // <== THIS CAUSES THE CRASH AS "connection" should not be used directly
                    assert.equal('worked!', 'worked!');
                    !err ? resolve(result) : reject(err);
                });
            }).finally(release);
        }).catch((err) => {
            assert.equal('worked', 'nope');            
        });
```

Here's some async / await examples.

Either use the `pool.query(...)` interface as it's easier (and preferred unless you're explicitly managing things like transactions):

```
const result = await pool.query('SELECT 1', [])
console.log('Result: %j', result)
```

 or if you are using `pool.connect()` use the returned value directly as a client. Do not dereference the internal `connection` property:

```
const client = await pool.connect()
try {
  const result = await client.query('SELECT 1', [])
  console.log('Result: %j', result)
finally {
  client.release()
}
```

**Comment by doug65536** [comment]
That works. Thanks!
