### ISSUE TITLE
Connection terminated unexpectedly

### ISSUE THREAD

**Issue by joshkra** [brianc/node-postgres#3107]
I get the following error running this program. Everything runs fine for a few minutes, and then queries start slowing down until the service is no longer usable. 
It is not a problem with the db itself, I can run this query with psql and this table is empty (12 columns, no rows). The db doesn't show any active query, so apparently they are stuck somewhere upstream.

"pg" version 8.11.1, on node 16. 

```
import pg from "pg";
import format from "pg-format";

// Database connection parameters
const connectionParams = {
    host: "cloud_postgres", // Postgres ip address[es] or domain name[s]
    port: 5432, // Postgres server port[s]
    database: "DB", // Name of database to connect to
    user: "username", // Username of database user
    password: "****" // Password of database user
};

const pool = new pg.Pool(connectionParams);

pool.on("error", (err: Error, client: any /*Client*/) => {
    console.log(`Error received on db pool: ${err.message} \n ${err.stack}`);
});

const start = Date.now();

const query = format("SELECT * FROM %s", tableName);

pool.query(query, function (err: any, res: any) {
    console.log(`Query ${query} executed in ${Date.now() - start} ms`);
    if (err) {
        return callback(err, null);
    }
    return callback(null, res.rows);
});
```

```
ERROR at 2023-12-06@12:55:30:868: Database error: unknown, Connection terminated unexpectedly
 Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:627:28)
    at Connection.emit (node:events:513:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:63:12)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:301:12)
at logError (/usr/src/app/modules/postgres.js:89:26),at PendingItem.callback (/usr/src/app/modules/postgres.js:237:13),at Client._co
nnectionCallback (/usr/src/app/node_modules/pg-pool/index.js:254:23),at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/cli
ent.js:145:18),at Object.onceWrapper (node:events:627:28)
```

**Comment by charmander** [comment]
What is `callback`? This isn’t a complete enough program or environment description to reproduce any issues with.

Also, can you reproduce the problem with a local PostgreSQL instance?

**Comment by joshkra** [comment]
@charmander `callback` is just a function passed from outside.
yes, i have a local PostgreSQL instance, in fact everything is local.
the typical values are:
```
Pool has 1 clients, 0 idle clients, 0 queued waiting requests
Pool has 1 clients, 1 idle clients, 0 queued waiting requests
Pool has 0 clients, 0 idle clients, 0 queued waiting requests
```

thanks

**Comment by charmander** [comment]
I know it’s a function, but there’s no indication from the code you’ve provided of what the overall app is doing – from your description, you’re not just running one query. Please post a complete self-contained test case, or as close as possible to one.

Also, if `host: "cloud_postgres"` is local, is it vanilla PostgreSQL then? Which version?

**Comment by joshkra** [comment]
```
const getUsernameFromDB = function (
    username: string,
    callback: (err: any, data: any) => void
) {
    const query = format("SELECT * FROM %s WHERE %I = %L", "Users", "UserName", username);

    const start = Date.now();
    pool.query(query, function (err: any, res: any) {
        console.log(`Query ${query} executed in ${Date.now() - start} ms`);
        if (err) {
            return callback(err, null);
        }
        return callback(null, res.rows);
    });
};

const checkUsername = function (req: Request, res: Response) {
        const username = req.body.username;
        if (!username) {
            return res.status(400).json(`Invalid username: ${username}`);
        }


        getUsernameFromDB(username, (error, user) => {
            if (error) {
                return res.status(400).json(`Invalid username: ${username}`);
            } else if (user && !user.length) {
                return res.status(400).json(`Invalid username: ${username}`);
            }

            return res.status(200).json(`Valid username: ${username}`);
        });
};
```

PostgreSQL (ver. 15) is is a Red Hat flavor, but should be very close to vanilla:
https://catalog.redhat.com/software/containers/rhel8/postgresql-15/63d29a05fd1c4f5552a305b3

**Comment by charmander** [comment]
I assembled the following self-contained script out of the snippets above:

```js
import pg from "pg";
import format from "pg-format";
import { Mutex } from "async-mutex";

const pool = new pg.Pool();

pool.on("error", (err, client) => {
    console.log(`Error received on db pool: ${err.message} \n ${err.stack}`);
});

const getUsernameFromDB = function (username, callback) {
    const query = format("SELECT * FROM %s WHERE %I = %L", "Users", "UserName", username);

    const start = Date.now();
    pool.query(query, function (err, res) {
        console.log(`Query ${query} executed in ${Date.now() - start} ms`);
        if (err) {
            return callback(err, null);
        }
        return callback(null, res.rows);
    });
};

const stressTest = () => {
    const mutex = new Mutex();
    let count = 0;
    const limit = 10000;
    const timers = [];
    console.log("@@@@@@@@@@@@@@@@@ STRESS TEST STARTED @@@@@@@@@@@@@@@@@@@@");
    for (let i = 0; i < 100; ++i) {
        const t = setInterval(() => {
            if (count === limit) {
                return;
            }
            const start = Date.now();
            getUsernameFromDB("user", (err, data) => {
                if (err) {
                    console.log(`@@@@@@@@@@@@@@@@@ STRESS TEST FAILED @@@@@@@@@@@@@@@@@@@@\n${JSON.stringify(err)}`);
                    return;
                }
                console.log(`Stress test query executed in ${Date.now() - start} ms`);
                mutex.runExclusive(() => {
                    ++count;
                    if (count === limit) {
                        timers.forEach(timer => clearInterval(timer));
                    }
                });
            })
        }, 200);
        timers.push(t)
    }
};
 
stressTest();
```

with this 12-column empty table:

```sql
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    "UserName" varchar(255) NOT NULL,
    a int, b int, c int, d int, e int, f int, g int, h int, i int, j int
);
```

and couldn’t reproduce the issue using Node 16, PostgreSQL 15.4, and pg 8.11.1.

(Note that the mutex isn’t doing anything here; ideally it, pg-format, TypeScript, and more would be excluded from a minimal reproducer.)

If I make the query slow enough for the queue to pile up, then queries take increasingly longer to run relative to when they were enqueued as expected, but `pool.waitingCount` also grows as expected.

**Comment by nacho9900** [comment]
@joshkra did you fix the issue? were you running your code in AWS lambda? 

I'm facing the same issue running in a Lambda connecting to RDS proxy.

**Comment by joshkra** [comment]
@nacho9900 no AWS lamdba, and the issue was somewhere else.
