### ISSUE TITLE
Cursor seems to work incorrectly when used with multiple parallel connections

### ISSUE THREAD

**Issue by Teascade** [brianc/node-postgres#3136]
Hello! `Pg.Cursor` works fine for a project I'm working on, when I'm using `pg.Pool` with just one Client at a time, even when working with large datasets. However, when I parallelize a large dataset in a way that utilizes multiple `PoolClient`s at the same time, all creating a new `Cursor` for each query, I sometimes get the following error. It seems to happen when one of the clients is beginning a `read`, it does not seem to be very consistent and debugging to find further information would be difficult due to NodeJS's nature.

```
node:events:492
      throw er; // Unhandled 'error' event
      ^

error: portal "C_1" does not exist
    at Parser.parseErrorMessage (/<path-to>/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/<path-to>/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/<path-to>/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/<path-to>/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Emitted 'error' event on Client instance at:
    at Client._handleErrorEvent (/<path-to>/node_modules/pg/lib/client.js:341:10)
    at Client._handleErrorMessage (/<path-to>/node_modules/pg/lib/client.js:352:12)
    at Connection.emit (node:events:514:28)
    at /<path-to>/node_modules/pg/lib/connection.js:117:12
    at Parser.parse (/<path-to>/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/<path-to>/node_modules/pg-protocol/dist/index.js:11:42)
    [... lines matching original stack trace ...]
    at Readable.push (node:internal/streams/readable:375:5) {
  length: 95,
  severity: 'ERROR',
  code: '34000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1977',
  routine: 'exec_execute_message'
}
```

This project I'm working on is at work, so I'm unable to share any related code. This isn't critical for me to get solved, I'm able to simply use regular queries instead, but I'm hoping this will help out iron a wrinkle in the Cursor. Thanks for node-pg, and all the hard work gone into this!

**Comment by charmander** [comment]
I wouldn’t be surprised if there were a bug in pg-cursor, but it’s more likely you’re not returning clients to the pool at the correct time. You don’t need to share proprietary code, but please make a self-contained script that reproduces the issue.

**Comment by Teascade** [comment]
Unfortunately I don't really have time for that, figured it was better to still report something rather than leave it completely unreported.
