### ISSUE TITLE
Build is broken on master

### ISSUE THREAD

**Issue by alxndrsn** [brianc/node-postgres#3147]
![Screenshot_2024-02-19_09-28-37](https://github.com/brianc/node-postgres/assets/191496/34b25cc5-a609-4b54-ac78-041eabc50bf6)

From latest build (https://github.com/brianc/node-postgres/actions/runs/7852909425/job/21431903558):

```
TypeError: prettier.resolveConfig.sync is not a function
Occurred while linting /home/runner/work/node-postgres/node-postgres/docs/components/alert.tsx:1
    at Program (/home/runner/work/node-postgres/node-postgres/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:174:40)
    at /home/runner/work/node-postgres/node-postgres/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/node-postgres/node-postgres/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/node-postgres/node-postgres/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/node-postgres/node-postgres/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/home/runner/work/node-postgres/node-postgres/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/node-postgres/node-postgres/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /home/runner/work/node-postgres/node-postgres/node_modules/eslint/lib/linter/linter.js:952:32
    at Array.forEach (<anonymous>)
```

It looks like the problem was introduced in the prettier update made in 9c3ecdca6953b8cde01fcb6ab6042e8274dc2e9b.

**Comment by alxndrsn** [comment]
Now passing.
