### ISSUE TITLE
Fails creating pg client on FIPS environment

### ISSUE THREAD

**Issue by putmanoj** [brianc/node-postgres#3268]
When trying to create pg client, with user/password,  it fails on FIPS environment, as 'MD5'  algorithm is not supported.
https://github.com/brianc/node-postgres/blob/pg%408.12.0/packages/pg/lib/crypto/utils-webcrypto.js#L41

```
node:internal/per_context/domexception:53
    ErrorCaptureStackTrace(this);
    ^
DOMException [NotSupportedError]: Unrecognized algorithm name
    at new DOMException (node:internal/per_context/domexception:53:5)
    at __node_internal_ (node:internal/util:670:10)
    at normalizeAlgorithm (node:internal/crypto/util:321:11)
    at normalizeAlgorithm (node:internal/crypto/util:293:12)
    at SubtleCrypto.digest (node:internal/crypto/webcrypto:79:15)
    at md5 (/opt/app-root/src/node_modules/pg/lib/crypto/utils-webcrypto.js:41:37)
    at Object.postgresMd5PasswordHash (/opt/app-root/src/node_modules/pg/lib/crypto/utils-webcrypto.js:50:21)
    at /opt/app-root/src/node_modules/pg/lib/client.js:251:45
    at Client._checkPgPass (/opt/app-root/src/node_modules/pg/lib/client.js:226:7)
    at Client._handleAuthMD5Password (/opt/app-root/src/node_modules/pg/lib/client.js:249:10)
    at Connection.emit (node:events:517:28)
    at /opt/app-root/src/node_modules/pg/lib/connection.js:117:12
    at Parser.parse (/opt/app-root/src/node_modules/pg-protocol/dist/parser.js:40:17)
    at TLSSocket.<anonymous> (/opt/app-root/src/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
Emitted 'error' event on Client instance at:
    at /opt/app-root/src/node_modules/pg/lib/client.js:254:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Is there any other way to configure the pg client ?

**Comment by charmander** [comment]
You would need to configure your PostgreSQL server to not use MD5 password auth (for that user, at least). https://www.postgresql.org/docs/current/client-authentication.html
