### ISSUE TITLE
TypeError: this.stream.write is not a function when PGSSLMODE is set to use SSL

### ISSUE THREAD

**Issue by alinaliBQ** [brianc/node-postgres#3294]
When I set `PGSSLMODE` to `require`  or `prefer`, I get `TypeError: this.stream.write is not a function` error when I try to run the tests. What could be the cause of this error? This error message is very cryptic. Have others seen this before?

Error log: (replaced full project path with simplified path)
```
throw-in-type-parser-tests.js
  emits error FAILED!

TypeError: this.stream.write is not a function
    at Connection.requestSsl (AxdbJavascriptDriverTest/packages/pg/lib/connection.js:122:17)
    at Connection.<anonymous> (AxdbJavascriptDriverTest/packages/pg/lib/client.js:119:13)
    at Connection.emit (node:events:517:28)
    at Object.makeClient [as client] (AxdbJavascriptDriverTest/packages/pg/test/unit/client/test-helper.js:15:21)
    at Test.action (AxdbJavascriptDriverTest/packages/pg/test/unit/client/throw-in-type-parser-tests.js:39:23)
    at Test._run (AxdbJavascriptDriverTest/packages/pg/test/suite.js:32:19)
    at Test.run (AxdbJavascriptDriverTest/packages/pg/test/suite.js:14:12)
    at Suite.run (AxdbJavascriptDriverTest/packages/pg/test/suite.js:57:10)
    at AxdbJavascriptDriverTest/node_modules/async/dist/async.js:4099:9
    at Object.process (AxdbJavascriptDriverTest/node_modules/async/dist/async.js:2347:17)

xargs: node: exited with status 255; aborting
make: *** [test-unit] Error 124
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: pg@8.12.0 
npm ERR!   at location: AxdbJavascriptDriverTest/packages/pg 
```

Command to reproduce this error:
```
PGUSER=test \
PGPASSWORD=test \
PGHOST=localhost \
PGDATABASE=postgres \
PGPORT=5432 \
PGSSLMODE=require \
npm test
```

**Comment by alinaliBQ** [comment]
I found more information, the error is caused by `stream` being `undefined`

**Comment by charmander** [comment]
The tests aren’t currently written to be runnable with `PG*` environment variables. You might have better luck with `make test-all connectionString=postgres://localhost:5432/?sslmode=require`.

**Comment by alinaliBQ** [comment]
Ohh I see, thanks for letting me know

**Comment by alinaliBQ** [comment]
I realize this error seems to only be present with unit tests
