### ISSUE TITLE
Periodically getting a "socket ended" exception

### ISSUE THREAD

**Issue by DarrellBrogdon** [brianc/node-postgres#473]
When I run a query more than once in about 5-10 seconds I see this exception getting thrown:

Error: This socket has been ended by the other party

I'm running this on a MacBook Pro 15" Retina with PostgreSQL 9.3.1 and node 0.10.17.

The query I'm running is a very simple one.  "SELECT id, url FROM images"

**Comment by iamvp** [comment]
We are using node-postgres (PostgreSQL client for node.js) to connect Redshift from lambda function. The connection to Redshift works properly for 80% of times, but fails randomly. The error message we got was, 

2015-09-30T04:53:57.259Z	1d9361fc-672f-11e5-a760-31ab2e36abea	Error: This socket has been ended by the other party at Socket.writeAfterFIN [as write] (net.js:276:12) at Connection.query (/var/task/node_modules/pg/lib/connection.js:189:15) at Query.submit (/var/task/node_modules/pg/lib/query.js:115:16) at Client._pulseQueryQueue (/var/task/node_modules/pg/lib/client.js:298:24) at Client.query (/var/task/node_modules/pg/lib/client.js:326:8) at /var/task/index.js:98:20 at null.<anonymous> (/var/task/node_modules/pg/lib/client.js:184:7) at g (events.js:180:16) at emit (events.js:92:17) at Socket.<anonymous> (/var/task/node_modules/pg/lib/connection.js:66:10)

We are using multiple/parallel connections to Redhsift from Lambda functions.
