### ISSUE TITLE
in nodejs getting exception 'terminating connection due to administrator command'

### ISSUE THREAD

**Issue by boa86** [brianc/node-postgres#478]
Hello!
I get exeption in nodejs with error 'terminating connection due to administrator command'

Configuration: 
postgres 9.1
Ubuntu 13.04
node.js v0.10.22
latest pg library v2.8.3, installed via npm
## Stacktrace:

error: terminating connection due to administrator command
    at Connection.parseE (/home/boa/work/nm_sync/node_modules/pg/lib/connection.js:558:11)
    at Connection.parseMessage (/home/boa/work/nm_sync/node_modules/pg/lib/connection.js:387:17)
    at null.<anonymous> (/home/boa/work/nm_sync/node_modules/pg/lib/connection.js:92:20)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
## Stacktrace:

TypeError: Cannot call method 'sync' of undefined
    at Query.handleError (/home/boa/work/nm_sync/node_modules/pg/lib/query.js:92:16)
    at null.<anonymous> (/home/boa/work/nm_sync/node_modules/pg/lib/client.js:167:24)
    at g (events.js:175:14)
    at EventEmitter.emit (events.js:92:17)
    at Socket.<anonymous> (/home/boa/work/nm_sync/node_modules/pg/lib/connection.js:60:10)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

This error seems be somewhere in depth of pg library, so i dont know where and how catch it in my code

For reproducing it:
1. create PG pool and connect to PG from nodejs
2. find pid of PG process that serve current connection
 ps ax | grep postgress
3. kill it by pid
4. get exception in console.

What wanted: it's to be good to catch exception in library, and just throw err msg in user's code

**Comment by KoltonG** [comment]
@brianc @boa86 I get the same error when I test my api using mocha, when I shutdown Postgres it emits that error? It is because I still have a connection to the database that I did not close?

**Comment by brianc** [comment]
Yeah when you shut down postgres it sends an error message to every
connected client alerting them of that fact.

**Comment by mikesamuel** [comment]
@brianc, The docs you [linked earlier](https://github.com/brianc/node-postgres/issues/478#issuecomment-30146664) have moved.  Is the [caveat re pool.on('error')](https://node-postgres.com/api/pool#-code-pool-on-39-error-39-err-error-client-client-gt-void-gt-void-code-) what you linked to before?

> It is important you add an event listener to the pool to catch errors. Just like other event emitters, if a pool emits an error event and no listeners are added node will emit an uncaught error and potentially exit.

**Comment by MatteoGioioso** [comment]
The link does not exist anymore, could you please update it? Thanks
