### ISSUE TITLE
can't connect to heroku db server with SSL

### ISSUE THREAD

**Issue by tedjt** [brianc/node-postgres#553]
I'm probably doing something wrong.

I can connect to a DB hosted by Heroku from an EC2 box with`psql`, but the application crashes on startup attempting to make the SSL connection to the database.

What's odd is that the application runs fine from my machine.

``` js
Error: The server does not support SSL connections
    at Socket.<anonymous> (/home/bitnami/source/server/node_modules/pg.js/lib/connection.js:70:33)
    at g (events.js:175:14)
    at EventEmitter.emit (events.js:117:20)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)
```

looking at the code there - the response looks like this:

```
< RESPONSE CODE: 51S7����~vK8Uv\w�V����`1|��#�� �#����0��0��    �v�\��-�0
<       *�H��
< 0'1%0#Uip-<redacted-IP>.ec2.internal0
< 140318000523Z
< 240315000523Z0'1%0#Uip-<redacted-IP>.ec2.internal0�"0
<       *�H��
< �0�
< ��/�6�`1�޹�JJ/�Y ��kw:%Ί��4\����"ҹ~�v��&d�>�������}Y��ZCɰ�p�{�����Z6���"$�%3d�Q���<��&|7�Ýb�sf+
< :QwC�X6�%~�����,��0���T�).��*82�SXa�w�~ا����/g��w{�l@�>Q��j�X����i��P�����������Ε�m���&۞�����!�h/�     ��SJ�a�z�)� ff�Y&~C�0
<       *�H��
< ��]��"�0LSk#k��.��L����F�]"%Z_�
< ��Ic���|��6���~ٽ�2%3n0 ���    �3��m�����R5�!M`�,�SJ��W~�cm;~+�
< LnJaL�k���`X�Hc�a
< R�x����Z{���M����{�kK;�{��|,���#.-��š�I�w6����v�)���1r�������˞l����1a��&���<�4{@�����3�~X�zj�꽎z���X�#��d�W�����XNI�� ����6k3l8
< E|��|[-����#�C��[���U��]8�4�|WC�l�3!,�*�<��)@�|��
< rֆ��)zʕٖ���
< P�F=f�]A��|��K"&���^�U�/x����F��^��UP��տ�����%")ύ;�3zs��r^&����dT�f�xM�}�B���<�g���,�l{Y�d��GHw9a�"|���Z`�9��g�N���ɠ
< �u����Ӗz ����3w��ԅ��?.�q�Ol�n��%5�0��L(�u9�����;����k͍�Zv ���k����K�����Ns�FP�)%4�2�ABsg����&��mOA�X��C!D�]���d�I��iP"��8���*��5.s��J��Γ������e>B�GW������]�NO�2�
< �t��U$�NMV'%���V0�Z���Ǖq��HsG��CK�y�b5%���]2c��K�ۊzc.�%��~5y?2�9������
```

**Comment by junyada100** [comment]
I know this is an old closed issue but google leads me here when I tried to solve the same problem.
I noticed that the error will be raised if the heroku instance is in sleep (free tier insance), after wake it up, the error will be gone. Hope this comment can help.

**Comment by sevensfive** [comment]
> I know this is an old closed issue but google leads me here when I tried to solve the same problem.
> I noticed that the error will be raised if the heroku instance is in sleep (free tier insance), after wake it up, the error will be gone. Hope this comment can help.

Is there any way to solve this problem?
