### ISSUE TITLE
error-handling-tests.js not just failing on Travis

### ISSUE THREAD

**Issue by rngadam** [brianc/node-postgres#576]
The file has this test:

```
test('when connecting to invalid host', function() {
  //this test fails about 30% on travis and only on travis...
  //I'm not sure what the cause could be
  if(process.env.TRAVIS) return false;
```

However, I see this intermittent failure on my machine too:

```
error-handling-tests.js............?.....Message: When connecting to an invalid host the error event should be emitted but it has been 5000 and still no error event.
AssertionError: When connecting to an invalid host the error event should be emitted but it has been 5000 and still no error event.
    at Object._onTimeout (/home/rngadam/letsface/src/node-postgres/test/integration/client/error-handling-tests.js:128:5)
    at Timer.list.ontimeout (timers.js:101:19)

 AssertionError: When connecting to an invalid host the error event should be emitted but it has been 5000 and still no error event.
    at Object._onTimeout (/home/rngadam/letsface/src/node-postgres/test/integration/client/error-handling-tests.js:128:5)
    at Timer.list.ontimeout (timers.js:101:19)

xargs: node: exited with status 255; aborting
make: *** [test-integration] Error 124
```

**Comment by brianc** [comment]
I added a bit of code to help with this
