### ISSUE TITLE
Pool.js unhandled 'error' event for bad  DB login details

### ISSUE THREAD

**Issue by ipetrovic11** [brianc/node-postgres#599]
Hello, 

first thanks for good PostgreSQL client for node.js.
I found that each time i try to connect with wrong login details to postgresql nodejs crash.

error: password authentication failed for user "democlient4333333333333333333333
"
    at Connection.parseE (C:\Users\illu\Desktop\SpectatorServer\the-spectator-no
deserver\node_modules\pg\lib\connection.js:526:11)
    at Connection.parseMessage (C:\Users\illu\Desktop\SpectatorServer\the-specta
tor-nodeserver\node_modules\pg\lib\connection.js:356:17)
    at Socket.<anonymous> (C:\Users\illu\Desktop\SpectatorServer\the-spectator-n
odeserver\node_modules\pg\lib\connection.js:105:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)

**Comment by powerfear** [comment]
Any updates on this? I've just ran into this while testing wrong login error.
Windows 7 64 bits
iojs v1.5.1
pg 4.3.0

**Comment by MichaelTheriot** [comment]
I'm also getting this, when testing my db with a bad conString.

Windows 7 64 bit
Node v0.12.0

**Comment by crertel** [comment]
Also getting this.

Node: 0.10.33
Pg-node: 4.1.1

Note that this only happens when my query string ends in "?ssl=true".

**Comment by jackniu81** [comment]
Also getting this, hope it will fix soon

Node: v0.12.0
Pg-node: 4.3.0

**Comment by matteosirri** [comment]
Il problema è che no viene chiamato il metod end():
```javascript
client.connect(function (err) {
  if (err) {
    client.end();
    return cb(err, null);
  }
...
```

**Comment by brianc** [comment]
I'm open to a pull request to fix this if its causing you an issue.

**Comment by matteosirri** [comment]
Good.

**Comment by crertel** [comment]
Thank you sir!

**Comment by brianc** [comment]
I believe this has been fixed in recent versions of node-postgres.
