### ISSUE TITLE
npm install pg fails when Postgres isn't installed: /bin/sh: pg_config: command not found

### ISSUE THREAD

**Issue by humphd** [brianc/node-postgres#684]
```
$ npm install pg
/
> pg@3.6.3 install /private/tmp/node_modules/pg
> node-gyp rebuild || (exit 0)

/bin/sh: pg_config: command not found
gyp: Call to 'pg_config --libdir' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/node_modules/pg
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
pg@3.6.3 node_modules/pg
├── packet-reader@0.2.0
├── bindings@1.2.1
├── pg-connection-string@0.1.3
├── buffer-writer@1.0.0
├── generic-pool@2.1.1
├── pg-types@1.6.0
├── nan@1.3.0
└── pgpass@0.0.3 (split@0.3.1)
```

I recently rebuilt my dev environment, and don't have postgres installed yet, which is what I suspect this error is about.  It might seem obvious, but it would be nice to call that out in your docs early on.  Many modules end up requiring pg as a dep deep in their dependency chain, and users may not understand they need postgres in order to make this work.

**Comment by davisford** [comment]
Does anyone know if there is a postgres lib package that we can install to get past this?  I'd like to use the native bindings, and I'm trying to create a Docker image -- I'd prefer not to require to have full-blown postgres in the image just to get past the compilation of the driver.
