### ISSUE TITLE
Improved Error Handling

### ISSUE THREAD

**Issue by superclarkk** [brianc/node-postgres#785]
Note that I'm using node-postgres via [Sequelize](https://github.com/sequelize/sequelize/).

When the postgres server is down (service not started), an ECONNREFUSED rather than an ETIMEDOUT error is emitted. I may be wrong, but I can't find anywhere in node-postgres where this situation is being handled.

Hence, this ticket is a request to handle all the different error types correctly, to help reduce the downtime in production when there are problems with the postgres server.

``` text
Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED
    at /path/to/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:61:20
    at null.<anonymous> (/path/to/node_modules/pg/lib/client.js:171:5)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/path/to/node_modules/pg/lib/connection.js:59:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)
From previous event:
    at ConnectionManager.connect (/path/to/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:52:10)
    at ConnectionManager.$connect (/path/to/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:204:41)
    at Object.pool.Pooling.Pool.create (/path/to/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:74:14)
    at createResource (/path/to/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:261:13)
    at dispense (/path/to/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:253:9)
    at Object.me.acquire (/path/to/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:319:5)
    at /path/to/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:188:15
From previous event:
    at ConnectionManager.getConnection (/path/to/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:187:10)
    at module.exports.Sequelize.query (/path/to/node_modules/sequelize/lib/sequelize.js:705:85)
    at module.exports.QueryInterface.select (/path/to/node_modules/sequelize/lib/query-interface.js:675:27)
    at null.<anonymous> (/path/to/node_modules/sequelize/lib/model.js:755:34)
    at process._tickCallback (node.js:448:13)
From previous event:
    at Promise.then (/path/to/node_modules/sequelize/lib/promise.js:21:17)
    at module.exports.Model.findAll (/path/to/node_modules/sequelize/lib/model.js:753:8)
    at module.exports (/path/to/server/routes/index.js:7:13)
    at Layer.handle [as handle_request] (/path/to/node_modules/express/lib/router/layer.js:82:5)
    at next (/path/to/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/path/to/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/path/to/node_modules/express/lib/router/layer.js:82:5)
    at /path/to/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/path/to/node_modules/express/lib/router/index.js:321:12)
    at next (/path/to/node_modules/express/lib/router/index.js:261:10)
    at Function.proto.handle (/path/to/node_modules/express/lib/router/index.js:166:3)
    at router (/path/to/node_modules/express/lib/router/index.js:35:12)
    at Layer.handle [as handle_request] (/path/to/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/path/to/node_modules/express/lib/router/index.js:302:13)
    at /path/to/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/path/to/node_modules/express/lib/router/index.js:321:12)
    at next (/path/to/node_modules/express/lib/router/index.js:261:10)
    at SendStream.error (/path/to/node_modules/express/node_modules/serve-static/index.js:107:7)
    at SendStream.emit (events.js:95:17)
```

**Comment by brianc** [comment]
I'm not sure what you mean by 'handle all the error types correctly.'  node-postgres attempts to connect and if it cannot connect it returns whatever error node creates on the socket back to you, the user, to deal with in your system.  I think the correct way to handle the error in a library is to quickly propagate the error back to the caller with as little interference as possible.  What do you think it should do?
