### ISSUE TITLE
installing with io.js

### ISSUE THREAD

**Issue by timini** [brianc/node-postgres#810]
I'm trying to install pg with io.js 2.3.0 and getting an error:

```
root@eda40f91dd79:/app# npm --version
2.11.1
root@eda40f91dd79:/app# node --version
v2.3.0
root@eda40f91dd79:/app# npm install pg
npm WARN package.json api.repositive.io@0.0.1 No license field.
|
> pg@3.6.3 install /app/node_modules/pg
> node-gyp rebuild || (exit 0)

make: Entering directory `/app/node_modules/pg/build'
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cc:3:0:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)':
../node_modules/nan/nan.h:189:78: error: no matching function for call to 'v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)'
../node_modules/nan/nan.h:189:78: note: candidate is:
In file included from /root/.node-gyp/2.3.0/src/node.h:42:0,
                 from ../node_modules/nan/nan.h:23,
                 from ../src/binding.cc:3:
/root/.node-gyp/2.3.0/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
/root/.node-gyp/2.3.0/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../src/binding.cc:3:0:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:481:19: error: 'NanNew' declared as an 'inline' variable
../node_modules/nan/nan.h:481:19: warning: 'always_inline' attribute ignored [-Wattributes]
../node_modules/nan/nan.h:481:19: error: 'v8::Local<v8::String> NanNew' redeclared as different kind of symbol
../node_modules/nan/nan.h:475:36: error: previous declaration of 'v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)'
../node_modules/nan/nan.h:481:7: error: 'ExternalAsciiStringResource' is not a member of 'v8::String'
../node_modules/nan/nan.h:481:48: error: 'resource' was not declared in this scope
../node_modules/nan/nan.h: In function 'bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)':
../node_modules/nan/nan.h:2103:12: error: 'class v8::String' has no member named 'IsExternalAscii'
../node_modules/nan/nan.h:2104:11: error: 'ExternalAsciiStringResource' in 'class v8::String' does not name a type
../node_modules/nan/nan.h:2105:5: error: 'ext' was not declared in this scope
../node_modules/nan/nan.h:2105:16: error: 'class v8::String' has no member named 'GetExternalAsciiStringResource'
../src/binding.cc: In member function 'void Connection::Emit(int, v8::Handle<v8::Value>*)':
../src/binding.cc:769:24: warning: 'void node::FatalException(const v8::TryCatch&)' is deprecated (declared at /root/.node-gyp/2.3.0/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/app/node_modules/pg/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-229.1.2.el7.x86_64
gyp ERR! command "/nodejs/bin/iojs" "/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/pg
gyp ERR! node -v v2.3.0
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
pg@3.6.3 node_modules/pg
├── packet-reader@0.2.0
├── bindings@1.2.1
├── pg-connection-string@0.1.3
├── buffer-writer@1.0.0
├── generic-pool@2.1.1
├── pg-types@1.6.0
├── nan@1.3.0
└── pgpass@0.0.3 (split@0.3.3)
```

**Comment by Starefossen** [comment]
Hi @timini, are you experiencing this issue with the latest version of io.js v2.4.0?

**Comment by darkn3rd** [comment]
I have this issue with pg 3.6.3, which refers to nan 1.6.0 module's header file.  I am unfamilar with node-gyp or how it works, so I am unsure how to troubleshoot further.

**Comment by mariusa** [comment]
I get the same issue on Fedora 24

$ npm -v
2.15.5
$ node -v
v4.4.6
