### ISSUE TITLE
Dependency error using System.js.

### ISSUE THREAD

**Issue by lig** [brianc/node-postgres#816]
Tried to use `pg 4.4.0` with `nw.js 0.12.2` (`io.js 1.2.0`) and `aurelia-framework 0.12.0`.

The code

    import pg from 'pg';

results in the following error

	[22157:0718/185044:ERROR:nw_shell.cc(335)] TypeError: Module /lig/myProject/jspm_packages/npm/pg@4.4.0/lib/client not declared as a dependency.
	    at file:///home/lig/myProject/jspm_packages/system.js:1:6086
	    at file:///home/lig/myProject/jspm_packages/npm/pg@4.4.0/lib/index.js:5:16
	    at Object.<anonymous> (file:///home/lig/myProject/jspm_packages/npm/pg@4.4.0/lib/index.js:72:3)
	    at file:///home/lig/myProject/jspm_packages/npm/pg@4.4.0/lib/index.js:74:4
	    at doEval (file:///home/lig/myProject/jspm_packages/system.js:1:24301)
	    at __eval (file:///home/lig/myProject/jspm_packages/system.js:1:23865)
	    at x.a [as __exec] (file:///home/lig/myProject/jspm_packages/system.js:1:3202)
	    at cjs.n.metadata.format.n.metadata.execute (file:///home/lig/myProject/jspm_packages/system.js:1:13192)
	    at f (file:///home/lig/myProject/jspm_packages/system.js:1:5970)
	    at c (file:///home/lig/myProject/jspm_packages/system.js:1:5586)

I believe this is caused by `__dirname` in `require` in the line

      var Client = require(__dirname + '/client');

There is similar issue here https://github.com/systemjs/systemjs/issues/351

**Comment by guybedford** [comment]
This is a limitation in the way jspm interprets Node modules yes. It can be fixed by adding the dependency information through meta configuration in an override. Happy to continue to track at the jspm issue and suggest configuration for this.

**Comment by linpy** [comment]
I am out of the office until 2015/07/24.

I would on leave from 2015/1/22~1/25. Please drop me mail if anything.
Thanks.


Note: This is an automated response to your message  "Re: [node-postgres]
Dependency error using System.js. (#816)" sent on 20/07/2015 22:09:10.

This is the only notification you will receive while this person is away.
