### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by ben-ng** [brianc/node-postgres#836]
I've been sporadically getting these errors on Heroku postgres. After it happens, that process starts failing to respond to a high number of requests.

```
[DATABASE] could not receive data from client: Connection reset by peer

150811/074509.188, [error], message: 139747999672192:error:0906D06C:PEM routines:PEM_read_bio:no start line:../deps/openssl/openssl/crypto/pem/pem_lib.c:696:Expecting: CERTIFICATE
stack: SequelizeDatabaseError: 139747999672192:error:0906D06C:PEM routines:PEM_read_bio:no start line:../deps/openssl/openssl/crypto/pem/pem_lib.c:696:Expecting: CERTIFICATE

at [object Object].Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:429:14)
at [object Object].<anonymous> (/app/node_modules/sequelize/lib/dialects/postgres/query.js:108:19)
at [object Object].emit (events.js:107:17)
at [object Object].Query.handleError (/app/node_modules/pg/lib/query.js:108:8)
at [object Object].<anonymous> (/app/node_modules/pg/lib/client.js:171:26)
at [object Object].emit (events.js:107:17)
at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:94:12)
at TLSSocket.emit (events.js:107:17)
at TLSSocket._tlsError (_tls_wrap.js:430:10)
at TLSWrap.ssl.onerror (_tls_wrap.js:339:12)
```

I'm not very sure how to debug this.

**Comment by ben-ng** [comment]
I was able to resolve this issue by not using https://github.com/coolaj86/node-ssl-root-cas anymore.
