### ISSUE TITLE
when using babel, pg-native is always required (and fails if not present)

### ISSUE THREAD

**Issue by nahuel** [brianc/node-postgres#838]
I'm not sure if this is a Babel or a node-postgres bug, steps to reproduce:

```
export PATH=$PATH:/tmp/iojs-v3.0.0-linux-x64/bin/:./node_modules/.bin
mkdir t
cd t
npm install babel pg

# create a t.js file with this ES6 content:
import * as pg from "pg";
console.log(pg);

# now execute: 
babel t.js > t-es5.js
node t-es5.js 

Error: Cannot find module 'pg-native'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/tmp/o/node_modules/pg/lib/native/index.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Babel generates the following code in `t-es5.js`:

```
function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj["default"] = obj; return newObj; } }

var _pg = require("pg");

var pg = _interopRequireWildcard(_pg);

console.log(pg);
```

The exception is happening in the `_interopRequireWildcard(_pg)` call. This doesn't happens with other libraries, so I'm not sure if a Babel or a node-postgres bug.

**Comment by jmont** [comment]
:+1:

**Comment by olegsmetanin** [comment]
+1

**Comment by olegsmetanin** [comment]
comment this lines
// lazy require native module...the native module may not have installed
// module.exports.__defineGetter__("native", function() {
//   delete module.exports.native;
//   module.exports.native = new PG(require('./native'));
//   return module.exports.native;
// });

**Comment by artem1** [comment]
pg define getter in module.exports
https://github.com/brianc/node-postgres/blob/master/lib/index.js#L76

```
  //lazy require native module...the native module may not have installed
  module.exports.__defineGetter__("native", function() {
    delete module.exports.native;
    module.exports.native = new PG(require('./native'));
    return module.exports.native;
  });
```

when babel rewrite code, him not found __esModule property in module and make copy of module props to new hash. in copy process pg.native called unintentionally. has no idea, how to fix this
```
function _interopRequireWildcard(obj) { //obj is pg module
  if (obj && obj.__esModule) {  //<===== test to something
    return obj; 
  } else { 
    var newObj = {}; 
    if (obj != null) { 
      for (var key in obj) { 
        if (Object.prototype.hasOwnProperty.call(obj, key)) 
          newObj[key] = obj[key];  //<== call getter here
      } 
    } 
    newObj["default"] = obj; 
    return newObj; 
  } 
}
```

**Comment by thaumant** [comment]
This might help you:
```
import pg from 'pg'
```

**Comment by jmont** [comment]
Any progress with this issue?

**Comment by langpavel** [comment]
I'm not experiencing this issue. I also using `import pg from 'pg'`. This can be solution I think.

**Comment by nybble73** [comment]
import pg from 'pg' does *not* work for me - I am seeing the pg-native error.

**Comment by langpavel** [comment]
@nybble73 What code generates babel for `import pg from 'pg'? Which versions?

This issue can be fixed only by wrapping `pg.native` getter to try/catch.

**Comment by langpavel** [comment]
@brianc Should I prepare pull request? My suggestion is return `null` if `require('pg-native')` fail

**Comment by brianc** [comment]
sure thing - pull request always welcome!

**Comment by swarajgiri** [comment]
Still facing the same issue on `"pg": "^6.1.5"`.

**Comment by halt-hammerzeit** [comment]
I'm too facing it, using Webpack.
This comment workaround worked:
https://github.com/elastic-coders/serverless-webpack/issues/78#issuecomment-271336996

**Comment by ughitsaaron** [comment]
Still having this issue bundling with webpack. Installing pg-native fixes the issue.

**Comment by craigsnyders** [comment]
I also couldn't bundle `pg` in my Typescript + Webpack2 + Lambda project until I installed `pg-native` and set the webpack config `output: 'node'`. Small example project: https://github.com/craigsnyders/serverless-typescript-starter

I'm also unclear if this is an issue with node-postgres or webpack. Normally webpack will resolve all dependant modules perfectly.
For reference, here's the webpack error when I haven't got `pg-native` in my package.json
```
ERROR in ./~/pg/lib/native/index.js
Module not found: Error: Can't resolve 'pg-native' in '/Users/csnyders/workspace/serverless-typescript-starter/node_modules/pg/lib/native'
 @ ./~/pg/lib/native/index.js 9:13-33
 @ ./~/pg/lib/index.js
 @ ./src/hello.ts
 @ ./src/handler.ts
```

**Comment by Kuchiriel** [comment]
Put in your webpack config. 

```
  resolve: {
    extensions: ['.js'],
    alias: {
      'pg-native': path.join(__dirname, 'aliases/pg-native.js'),
    }
  },
```

Create aliases/pg-native.js with

**Comment by jonaskello** [comment]
I also get the same error with pg 7.4.3 using webpack and typescript.

```
 ModuleNotFoundError: Module not found: Error: Can't resolve 'pg-native' in '/xxx/node_modules/pg/lib/native'
```

**Comment by adieuadieu** [comment]
Another solution (if using webpack), is to add `new webpack.IgnorePlugin(/^pg-native$/)` to your webpack config's plugins array. E.g.

```
const webpackConfig = {
  ...
  resolve: { ... },
  plugins: [
    new webpack.IgnorePlugin(/^pg-native$/)
  ]
  output: { ... }
  ...
}
```

**Comment by amit-dhara** [comment]
@adieuadieu 's solution worked. need to make sure you have installed webpack and imported in config file. Also, give and comma ( , ) after "plugin [ ... ]" and before "output:"

npm install --save webpack

var webpack = require('webpack');

**Comment by marcoippolito** [comment]
@brianc @amit-dhara @adieuadieu 
I'm experiencing the same problem.
I installed 

    "pg": "^8.0.2",
    "pg-hstore": "^2.3.3",
    "sequelize": "^5.21.6",

npm@6.14.4  and Node: 12.15.0

this is the pg.js I'm using:

    const { Pool } = require('pg');
    const pool = new Pool();
    module.exports = {
      query: (text, params, callback) => {
        return pool.query(text, params, callback);
      },
    }

I also specified in webpack.config.js : 

    {
        "mode": "development",
        plugins: [
          new webpack.IgnorePlugin(/^pg-native$/, /^dns$)
        ],

When compiling: 

    npm run serve
     ERROR  Failed to compile with 2 errors                                         

    These dependencies were not found:

    * dns in ./node_modules/pg/lib/connection-parameters.js
    * pg-native in ./node_modules/pg/lib/native/client.js

    To install them, you can run: npm install --save dns pg-native


How to solve the problem?

Marco

**Comment by GeorgeWL** [comment]
This still seems to be an issue, so unsure why it was closed

**Comment by charmander** [comment]
@GeorgeWL The original issue was closed with a fix. If you’re seeing something new or something that appears to be the same, please include details.

**Comment by GeorgeWL** [comment]
Found out the why, vscode auto import still occasionally tries to auto import from sequelize/types for some reason.

I just had to edit it to the right location.

**Comment by GeorgeWL** [comment]
Seeing the same, using this alongside webpack, webpack fails to correctly compile it when using TypeScript.

The workaround of adding pg-native to a webpack ignorePlugin still seems to fix it.

**Comment by moltar** [comment]
I think the original issue asks about babel, which seems to be still an issue. E.g. when using `parcel`, get the same errors:

```
🚨  /.../node_modules/pg/lib/native/client.js:11:21: Cannot resolve dependency 'pg-native'
```

**Comment by antonycms** [comment]
Nothing worked for me, so I created a manual fix myself

create a fix.js file at the root of the project:
`
const fs = require ('fs');
const path = require ('path');

const pgClientPath = path.resolve (__ dirname, 'node_modules', 'pg', 'lib', 'native', 'client.js');

fs.readFile (pgClientPath, 'utf8', function (err, data) {
  if (err) {
    return console.log (err);
  }
  var result = data.replace ("var Native = require ('pg-native')", 'var Native = null');

  fs.writeFile (pgClientPath, result, 'utf8', function (err) {
    if (err) returns console.log (err);
  });
});
`

to run the patch file whenever you install or add a new dependency, add it to the package.json file:
`
"scripts:": {
  "postinstall": "node fix.js"
}
`

-------------------------------------------------- -------------------------------------------------- ---
If you are using sequelize, make the following configuration in the configuration part:
`
import * as 'pg' pg; // import pg

const database = 'myDB';
const dialect = 'postgres';
const host = 'locahost';
const port = 5432;
const username = 'myUser';
const password = 'myPass';

export standard {
  dialect,
  dialectModule: pg, // define pg manually
  username,
  password,
  data base,
  host,
  door,

  to define: {
    timestamps: true,
    underlined: true,
    underscoredAll: true,
  }
};
`

**Comment by antonycms** [comment]
Nothing worked for me, so I created a manual fix myself

create a fix.js file at the root of the project:
```
const fs = require ('fs');
const path = require ('path');

const pgClientPath = path.resolve (__ dirname, 'node_modules', 'pg', 'lib', 'native', 'client.js');

fs.readFile (pgClientPath, 'utf8', function (err, data) {
  if (err) {
    return console.log (err);
  }
  var result = data.replace ("var Native = require ('pg-native')", 'var Native = null');

  fs.writeFile (pgClientPath, result, 'utf8', function (err) {
    if (err) returns console.log (err);
  });
});
```

to run the patch file whenever you install or add a new dependency, add it to the package.json file:
```
"scripts:": {
  "postinstall": "node fix.js"
}
```

-------------------------------------------------- -------------------------------------------------- ---
If you are using sequelize, make the following configuration in the configuration part:

```
import * as 'pg' pg;  // import pg

const database = 'myDB';
const dialect = 'postgres';
const host = 'locahost';
const port = 5432;
const username = 'myUser';
const password = 'myPass';

export standard {
  dialect,
  dialectModule: pg, // define pg manually
  username,
  password,
  data base,
  host,
  door,

  to define: {
    timestamps: true,
    underlined: true,
    underscoredAll: true,
  }
};
```

**Comment by sdegroot** [comment]
An alternative workaround is to create a local pg-native package and reference it from your package.json
```
{
  "name": "your-module",
  "private": true,
  "dependencies": {
    "pg": "^8.3.3",
    "pg-native": "file:./modules/pg-native",
  }
}
```

The `index.js` file in the `pg-native` folder only has to contain
```
module.exports = null;
```

and a basic `package.json` file like this:

```
{
  "name": "pg-native",
  "private": true,
  "main": "index.js"
}
```

**Comment by GeorgeWL** [comment]
is this actually fixed? or has it been closed due to workarounds

**Comment by jaylattice** [comment]
`npm install --save pg-native` fixes this error, since `pg` specifies `pg-native` as an optional peer dependency. However if you are deploying to a serverless lambda, then this will fail at runtime. I am going to try using a stub module as mentioned by @sdegroot

**Comment by GeorgeWL** [comment]
> `npm install --save pg-native` fixes this error, since `pg` specifies `pg-native` as an optional peer dependency.

that's not a fix, that's a workaround.

**Comment by jaylattice** [comment]
¯\\_(ツ)\_/¯ anything that unblocks me is a fix.

**Comment by dj-doMains** [comment]
Just in case anyone is using `serverless-bundle` to use webpack with the serverless framework, here's the workaround:

```
custom:
  bundle:
    ignorePackages:
      - pg-native
```

**Comment by brianc** [comment]
The old api of using a getter to require the native bindings was __not__ a good idea, but it's been around for ages and ages.  Unfortunately it's a backwards compatiblity break to change it but one I'm happy to do - I've put this into the 9.0 milestone so it'll go out w/ our next major version release where we break backwards compatibility.

**Comment by louisbuchbinder** [comment]
Here is a workaround if you are using webpack

pg-native.js
```javascript
module.exports = null;
```

webpack.config.js
```javascript
   ...,
    resolve: {
      alias: {
        'pg-native': path.join(__dirname, 'pg-native'),
      },
    },
    ...,
```

**Comment by zhangyuwu123** [comment]
nice it‘s worked for me thx @antonycms

**Comment by larshp** [comment]
I added following in my webpack config to workaround the issue,

```js
    new IgnorePlugin({
      resourceRegExp: /^pg-native$/,
      contextRegExp: /./,
    }),
```

**Comment by merlinaudio** [comment]
> An alternative workaround is to create a local pg-native package and reference it from your package.json
> 
> ```
> {
>   "name": "your-module",
>   "private": true,
>   "dependencies": {
>     "pg": "^8.3.3",
>     "pg-native": "file:./modules/pg-native",
>   }
> }
> ```
> 
> The `index.js` file in the `pg-native` folder only has to contain
> 
> ```
> module.exports = null;
> ```
> 
> and a basic `package.json` file like this:
> 
> ```
> {
>   "name": "pg-native",
>   "private": true,
>   "main": "index.js"
> }
> ```

Thank you!!! Easiest way to do it, no webpack required.

**Comment by brianc** [comment]
I'm going to change the API in pg@9.0 [per this discussion thread](https://github.com/brianc/node-postgres/discussions/3598#discussioncomment-15942551) to fix this long standing ridiculousness.
