### ISSUE TITLE
(node) Possible eventEmitter memory leak detected. 11 listeners added.

### ISSUE THREAD

**Issue by jfeldstein** [brianc/node-postgres#86]
Getting this, with a stack trace back into pg. Any tips? 

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
    at [object Object].<anonymous> (events.js:123:17)
    at [object Object].<anonymous> (/Users/Jordan/Development/sway-nodes/node_modules/pg/lib/client.js:82:9)
    at [object Object].g (events.js:143:14)
    at [object Object].emit (events.js:81:20)
    at Socket.<anonymous> (/Users/Jordan/Development/sway-nodes/node_modules/pg/lib/connection.js:47:12)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:676:14)
----------------------------------------
    at EventEmitter.on
    at [object Object].once (events.js:147:8)
    at [object Object].connect (/Users/Jordan/Development/sway-nodes/node_modules/pg/lib/client.js:72:7)
    at new <anonymous> (/Users/Jordan/Development/sway-nodes/ServicesApi.js:22:11)
    at Object.<anonymous> (/Users/Jordan/Development/sway-nodes/update_server.js:28:17)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
```

**Comment by PritamUpadhyay** [comment]
Hello.
I am having same issue.
My code looks like
```javascript

var exports = module.exports = {};

var pg = require('pg');
var connectionString = "postgres://postgres:postgres@127.0.0.1:5432/postgres";

var client = new pg.Client(connectionString);

var connected = false;

function connect() {
    client.connect(function (err) {
        if (err) {
            connected = false;
        }
        else {
            connected = true;
        }
    });
}

exports.Insert = function (packet) {
    if (!connected) connect();    
    var tablename = packet.msgExchange.split('-')[1];

    client.query('CREATE TABLE IF NOT EXISTS ' + tablename + '(msgid serial NOT NULL, msgtxt character varying, "msgDateTime" timestamp with time zone DEFAULT now(), "msgChannel" character varying, "msgClient" character varying, CONSTRAINT ' + tablename + '_pkey PRIMARY KEY (msgid)) WITH ( OIDS=FALSE )');


    for (var i = 0; i < packet.msgChannel.length; i++) {
        client.query('INSERT INTO '+ tablename + '(msgTxt, "msgDateTime", "msgChannel", "msgClient") VALUES ($1, $2, $3, $4)', [packet.msgTxt.toString(), packet.msgDateTime, packet.msgChannel[i], packet.msgClient.toString()]);
    }
}
```
I have created separate file for to use _Insert_ function. When I call Insert function inside the _for_ loop, It is giving me same error given by @jfeldstein.
