### ISSUE TITLE
Connection.close() error TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by rbaindourov** [brianc/node-postgres#883]
I'm having some interesting issues with long running process not quitting in a timely fashion.

At first I tried calling `.close()` on the Client object only to realize that `.close()` call should be called on the connection object instead. Now I can't call `done()` during a successful callback as per your example because the script is doing a data migration job that will need a persistent connection, and wish to only close the connection after I have exhausted all tasks in the job.

But when I setup this small experiment with the structure I need, I get this error:

```sh
pro:salesforce-sync robert$ ./test.js
/Users/robert/dev/salesforce-sync/node_modules/pg/lib/connection.js:309
  this.writer.addCString(msg.type + (msg.name || ''));
                            ^

TypeError: Cannot read property 'type' of undefined
    at Connection.close (/Users/robert/dev/salesforce-sync/node_modules/pg/lib/connection.js:309:29)
    at /Users/robert/dev/salesforce-sync/test.js:18:21
    at null.<anonymous> (/Users/robert/dev/salesforce-sync/node_modules/pg/lib/client.js:149:7)
    at g (events.js:260:16)
    at emitOne (events.js:82:20)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/Users/robert/dev/salesforce-sync/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
```

Here is the code
```javascript
#!/usr/local/bin/node
'use strict'
let config = require('./conf/config.json')
let pg = require('pg');
let escape = require('pg-escape');
let pgdb = config.postgresdb;
let conString = config.postgres;

conString += pgdb;

let psql = new pg.Client(conString);

psql.connect(function(err, pCon) {
  if(err) {
    console.error('could not connect to postgres', err);
  } else {

    psql.connection.close();
    
  }

});
```

Is this because I am trying to close the connection without executing a query? Running node 4.2.1.

I can see how a simple defense statement can fix the issue, but first I wanted to get your eyes on it.

Thank you for help, and apologies if I made any simple error.

-Robert Baindourov

**Comment by rbaindourov** [comment]
Fixed. Apologies, I am not much of a reader, I prefer intuition and experience to be my main drivers.

Just out of curiosity, why did you choose the word `end()` instead of `close()`

Solution:
```javascripit
#!/usr/local/bin/node
'use strict'
let config = require('./conf/config.json')
let pg = require('pg');
let escape = require('pg-escape');
let pgdb = config.postgresdb;
let conString = config.postgres;
let psqlClose;

conString += pgdb;

let psql = new pg.Client(conString);

 psql.connect(function(err, pCon, done) {
  psqlClose = done;
  if(err) {
    console.error('could not connect to postgres', err);
  } else {


    psql.end();
  }

});
```

**Comment by rbaindourov** [comment]
Please consider creating an alias for `.end()` with `.close()`

Thank You!
