### ISSUE TITLE
Multi statement queries are treated as prepared statements

### ISSUE THREAD

**Issue by koistya** [brianc/node-postgres#946]
Sending a query with multiple SQL statements and parameters is not supported? This is not clear from the [documentation](https://github.com/brianc/node-postgres/wiki/Prepared-Statements#parameterized-queries).

```js
client.query('SELECT $1; SELECT $1;', [123], callback);
```
```js
client.query({ text: 'SELECT $1; SELECT $1;' }, [123], callback);
```
```
error: cannot insert multiple commands into a prepared statement
   at [object Object].Connection.parseE (.\node_modules\pg\lib\connection.js:539:11)
   at [object Object].Connection.parseMessage (.\node_modules\pg\lib\connection.js:366:17)
   at TLSSocket.<anonymous> (.\node_modules\pg\lib\connection.js:105:22)
   at emitOne (events.js:90:13)
   at TLSSocket.emit (events.js:182:7)
   at readableAddChunk (_stream_readable.js:153:18)
   at TLSSocket.Readable.push (_stream_readable.js:111:10)
   at TLSWrap.onread (net.js:529:20)
```

What is a workaround for this, split the query into multiple calls to `client.query(...)`?

**Comment by brianc** [comment]
Multi-statement parameterized queries are unfortunately not supported by postgres.  I suggest just doing 2 separate queries and using whatever type of async flow control you like to dispatch them.

**Comment by abenhamdine** [comment]
I took the liberty to edit the clarify the wiki : https://github.com/brianc/node-postgres/wiki/Prepared-Statements

**Comment by brianc** [comment]
Awesome!! Thank you! :dancer:

On Fri, Feb 26, 2016 at 3:19 AM, Arnaud Benhamdine <notifications@github.com
