### ISSUE TITLE
Error: %1 is not a valid Win32 application.   (caused by native bindings)

### ISSUE THREAD

**Issue by martinsookael** [brianc/node-postgres#965]
```
$ node app.js
C:\POST\node_modules\pg-native\node_modules\libpq\node_modules\bindings\bindings
.js:83
        throw e
        ^

Error: %1 is not a valid Win32 application.
\\?\C:\xxxx\node_modules\pg-native\node_modules\libpq\build\Release\addon.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (C:\xxxx\node_modules\pg-native\node_modules\libpq\node_modules\
bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\xxxx\node_modules\pg-native\node_modules\libpq\ind
ex.js:1:108)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

This is caused by native bindings and is fixed with removing ".native".
Found while debugging with a WIN 64 computer.

```
  , pg = require('pg').native  // throws this error
  , pg = require('pg') // does not throw this error

```

**Comment by charmander** [comment]
Is this still an issue?
