### ISSUE TITLE
crash in Result.prototype.parseRow

### ISSUE THREAD

**Issue by spollack** [brianc/node-postgres#970]
this is running pg 4.5.1 javascript, with PR #949 on top. crash happened in production (just once so far). we do not currently have a repro case. 

```
TypeError: object is not a function
    at Result.parseRow (/app/node_modules/pg/lib/result.js:61:10)
    at Query.handleDataRow (/app/node_modules/pg/lib/query.js:58:26)
    at null.<anonymous> (/app/node_modules/pg/lib/client.js:111:26)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

The offending bit of code is:

```
Result.prototype.parseRow = function(rowData) {
  return new this.RowCtor(this._parsers, rowData);
};
```

**Comment by charmander** [comment]
Is this another instance of https://github.com/brianc/node-postgres/issues/949#issuecomment-224101918?
